#if !defined(DRESSUP_ITEM_ID_HEROINE_HAIR_H)
#define DRESSUP_ITEM_ID_HEROINE_HAIR_H

#define DRESSUP_ITEM_ID_P2_HAIR_BOB 0
#define DRESSUP_ITEM_ID_P2_HAIR_BOB_MAE 1
#define DRESSUP_ITEM_ID_P2_HAIR_BOB_PATTUN 2
#define DRESSUP_ITEM_ID_P2_HAIR_SHORT 3
#define DRESSUP_ITEM_ID_P2_HAIR_SHORT_MAE 4
#define DRESSUP_ITEM_ID_P2_HAIR_SHORT_PATTUN 5
#define DRESSUP_ITEM_ID_P2_HAIR_LONG 6
#define DRESSUP_ITEM_ID_P2_HAIR_LONG_MAE 7
#define DRESSUP_ITEM_ID_P2_HAIR_LONG_PATTUN 8
#define DRESSUP_ITEM_ID_P2_HAIR_MIDIUM 9
#define DRESSUP_ITEM_ID_P2_HAIR_MIDIUM_MAE 10
#define DRESSUP_ITEM_ID_P2_HAIR_MIDIUM_PATTUN 11
#define DRESSUP_ITEM_ID_P2_HAIR_MATOME 12
#define DRESSUP_ITEM_ID_P2_HAIR_MATOME_MAE 13
#define DRESSUP_ITEM_ID_P2_HAIR_MATOME_PATTUN 14
#define DRESSUP_ITEM_ID_P2_HAIR_MAKI 15
#define DRESSUP_ITEM_ID_P2_HAIR_MAKI_MAE 16
#define DRESSUP_ITEM_ID_P2_HAIR_MAKI_PATTUN 17
#define DRESSUP_ITEM_ID_P2_HAIR_TWIN 18
#define DRESSUP_ITEM_ID_P2_HAIR_TWIN_MAE 19
#define DRESSUP_ITEM_ID_P2_HAIR_TWIN_PATTUN 20
#define DRESSUP_ITEM_ID_P2_HAIR_BRAIDS 21
#define DRESSUP_ITEM_ID_P2_HAIR_MMJ_SOTO 22
#define DRESSUP_ITEM_ID_P2_HAIR_MMJ_SOTO_MAE 23
#define DRESSUP_ITEM_ID_P2_HAIR_MMJ_SOTO_PATTUN 24
#define DRESSUP_ITEM_ID_P2_HAIR_MMJ_SPONY 25
#define DRESSUP_ITEM_ID_P2_HAIR_MMJ_SPONY_MAE 26
#define DRESSUP_ITEM_ID_P2_HAIR_MMJ_SPONY_PATTUN 27
#define DRESSUP_ITEM_ID_HEROINE_HAIR_COUNT 28

#endif // #if !defined(DRESSUP_ITEM_ID_HEROINE_HAIR_H)
