#if !defined(DRESSUP_COLOR_ID_H)
#define DRESSUP_COLOR_ID_H

#define DRESSUP_COLOR_ID_SKIN_SWH 0
#define DRESSUP_COLOR_ID_SKIN_SYE 1
#define DRESSUP_COLOR_ID_SKIN_SBR 2
#define DRESSUP_COLOR_ID_SKIN_SDB 3
#define DRESSUP_COLOR_ID_SKIN_COUNT 4

#define DRESSUP_COLOR_ID_CLOTH_WH 0
#define DRESSUP_COLOR_ID_CLOTH_BK 1
#define DRESSUP_COLOR_ID_CLOTH_RD 2
#define DRESSUP_COLOR_ID_CLOTH_YE 3
#define DRESSUP_COLOR_ID_CLOTH_GR 4
#define DRESSUP_COLOR_ID_CLOTH_BL 5
#define DRESSUP_COLOR_ID_CLOTH_OR 6
#define DRESSUP_COLOR_ID_CLOTH_NB 7
#define DRESSUP_COLOR_ID_CLOTH_PP 8
#define DRESSUP_COLOR_ID_CLOTH_PN 9
#define DRESSUP_COLOR_ID_CLOTH_GL 10
#define DRESSUP_COLOR_ID_CLOTH_BE 11
#define DRESSUP_COLOR_ID_CLOTH_RD1 12
#define DRESSUP_COLOR_ID_CLOTH_RD2 13
#define DRESSUP_COLOR_ID_CLOTH_RD3 14
#define DRESSUP_COLOR_ID_CLOTH_YE1 15
#define DRESSUP_COLOR_ID_CLOTH_YE2 16
#define DRESSUP_COLOR_ID_CLOTH_YE3 17
#define DRESSUP_COLOR_ID_CLOTH_GR1 18
#define DRESSUP_COLOR_ID_CLOTH_GR2 19
#define DRESSUP_COLOR_ID_CLOTH_GR3 20
#define DRESSUP_COLOR_ID_CLOTH_BL1 21
#define DRESSUP_COLOR_ID_CLOTH_BL2 22
#define DRESSUP_COLOR_ID_CLOTH_BL3 23
#define DRESSUP_COLOR_ID_CLOTH_OR1 24
#define DRESSUP_COLOR_ID_CLOTH_OR2 25
#define DRESSUP_COLOR_ID_CLOTH_OR3 26
#define DRESSUP_COLOR_ID_CLOTH_NB1 27
#define DRESSUP_COLOR_ID_CLOTH_NB2 28
#define DRESSUP_COLOR_ID_CLOTH_NB3 29
#define DRESSUP_COLOR_ID_CLOTH_PP1 30
#define DRESSUP_COLOR_ID_CLOTH_PP2 31
#define DRESSUP_COLOR_ID_CLOTH_PP3 32
#define DRESSUP_COLOR_ID_CLOTH_PN1 33
#define DRESSUP_COLOR_ID_CLOTH_PN2 34
#define DRESSUP_COLOR_ID_CLOTH_PN3 35
#define DRESSUP_COLOR_ID_CLOTH_LG 36
#define DRESSUP_COLOR_ID_CLOTH_COUNT 37

#define DRESSUP_COLOR_ID_HAIR_HBK 0
#define DRESSUP_COLOR_ID_HAIR_HGO 1
#define DRESSUP_COLOR_ID_HAIR_HDB 2
#define DRESSUP_COLOR_ID_HAIR_HAB 3
#define DRESSUP_COLOR_ID_HAIR_HLB 4
#define DRESSUP_COLOR_ID_HAIR_HPL 5
#define DRESSUP_COLOR_ID_HAIR_HPB 6
#define DRESSUP_COLOR_ID_HAIR_HRD 7
#define DRESSUP_COLOR_ID_HAIR_HWH 8
#define DRESSUP_COLOR_ID_HAIR_COUNT 9

#define DRESSUP_COLOR_ID_EYE_EHZ 0
#define DRESSUP_COLOR_ID_EYE_EGL 1
#define DRESSUP_COLOR_ID_EYE_EGR 2
#define DRESSUP_COLOR_ID_EYE_EBL 3
#define DRESSUP_COLOR_ID_EYE_EBK 4
#define DRESSUP_COLOR_ID_EYE_EYE 5
#define DRESSUP_COLOR_ID_EYE_ERD 6
#define DRESSUP_COLOR_ID_EYE_EPP 7
#define DRESSUP_COLOR_ID_EYE_EBR 8
#define DRESSUP_COLOR_ID_EYE_COUNT 9

#define DRESSUP_COLOR_ID_EYEBLOW_BBK 0
#define DRESSUP_COLOR_ID_EYEBLOW_BGO 1
#define DRESSUP_COLOR_ID_EYEBLOW_BDB 2
#define DRESSUP_COLOR_ID_EYEBLOW_BAB 3
#define DRESSUP_COLOR_ID_EYEBLOW_BLB 4
#define DRESSUP_COLOR_ID_EYEBLOW_BPL 5
#define DRESSUP_COLOR_ID_EYEBLOW_BPB 6
#define DRESSUP_COLOR_ID_EYEBLOW_BRD 7
#define DRESSUP_COLOR_ID_EYEBLOW_BWH 8
#define DRESSUP_COLOR_ID_EYEBLOW_COUNT 9

#define DRESSUP_COLOR_ID_LIP_LOF 0
#define DRESSUP_COLOR_ID_LIP_LLP 1
#define DRESSUP_COLOR_ID_LIP_LOR 2
#define DRESSUP_COLOR_ID_LIP_LPN 3
#define DRESSUP_COLOR_ID_LIP_LRD 4
#define DRESSUP_COLOR_ID_LIP_LBO 5
#define DRESSUP_COLOR_ID_LIP_LBL 6
#define DRESSUP_COLOR_ID_LIP_COUNT 7

#define DRESSUP_COLOR_ID_EXT_DBE 0
#define DRESSUP_COLOR_ID_EXT_DRD 1
#define DRESSUP_COLOR_ID_EXT_DPBK 2
#define DRESSUP_COLOR_ID_EXT_DPLBK 3
#define DRESSUP_COLOR_ID_EXT_COUNT 4


#endif // #if !defined(DRESSUP_COLOR_ID_H)
