#if !defined(DRESSUP_ITEM_ID_HERO_HAIR_H)
#define DRESSUP_ITEM_ID_HERO_HAIR_H

#define DRESSUP_ITEM_ID_P1_HAIR_MIDIUM 0
#define DRESSUP_ITEM_ID_P1_HAIR_MAE 1
#define DRESSUP_ITEM_ID_P1_HAIR_VSHORT 2
#define DRESSUP_ITEM_ID_P1_HAIR_PERM 3
#define DRESSUP_ITEM_ID_P1_HAIR_ALLBACK 4
#define DRESSUP_ITEM_ID_P1_HAIR_BRAIDS 5
#define DRESSUP_ITEM_ID_P1_HAIR_MMJ_SHORT 6
#define DRESSUP_ITEM_ID_P1_HAIR_MMJ_REGENT 7
#define DRESSUP_ITEM_ID_HERO_HAIR_COUNT 8

#endif // #if !defined(DRESSUP_ITEM_ID_HERO_HAIR_H)
