#if !defined(DRESSUP_ITEM_ID_HERO_BNGL_H)
#define DRESSUP_ITEM_ID_HERO_BNGL_H

#define DRESSUP_ITEM_ID_P1_BNGL_ZENBRESS01 0
#define DRESSUP_ITEM_ID_P1_BNGL_ZENBRESS_NIJI01 1
#define DRESSUP_ITEM_ID_HERO_BNGL_COUNT 2

#endif // #if !defined(DRESSUP_ITEM_ID_HERO_BNGL_H)
