// このファイルは tool/Binlinker/binlinder.rb から出力されています。
#ifndef __BLOOM_RESOURCE_PACK__
#define __BLOOM_RESOURCE_PACK__

enum {
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOM_HIGH_LUMINANCE_MODEL_RGBXA_CTR_GFBMDL,
	BL_IDX_BLOOM_RESOURCE_PACK_FILLSCREAN_CTR_GFBVSH,
	BL_IDX_BLOOM_RESOURCE_PACK_COMB1_MANUAL_CTR_GFBFSH,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOM_DUMMY_TEX_CTR_BTEX,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOM_BOARD_MODEL_CTR_GFBMDL,
	BL_IDX_BLOOM_RESOURCE_PACK_FILLSCREAN_CTR_GFBVSH,
	BL_IDX_BLOOM_RESOURCE_PACK_COMB1_MANUAL_CTR_GFBFSH,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOM_DUMMY_TEX_CTR_BTEX,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOM_SMALL_TEX_RGBA0_CTR_BTEX,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOM_SMALL_TEX_RGBA1_CTR_BTEX,
	BL_IDX_BLOOM_RESOURCE_PACK_MAX,
};



#endif // BLOOM_RESOURCE_PACK
