#if !defined(REDEFINE_MONSNO_DEF_H_INCLUDED)
#define REDEFINE_MONSNO_DEF_H_INCLUDED
#pragma once
//==============================================================================
/**
 * @file   redefine_monsno_def.h
 * @date   2016/12/05 Mon. 13:09:48
 * @author muto_yu
 * @brief  
 * @par Copyright
 * (C)1995-2015 GAME FREAK inc. All Rights Reserved.
 */
//==============================================================================


#include  "./redefineMacro.h"


/*  monsno_defはenumと#defineが混在する  */
namespace TestForJenkins  {
namespace VersionCompatibility  {
namespace NijiID  {
  #include  "./pokelib/monsno_def.h"
}
}
}



//別フォルム定義
//フシギバナ
TO_ENUM(FORMNO_HUSIGIBANA_NORMAL);
TO_ENUM(FORMNO_HUSIGIBANA_MEGA);
TO_ENUM(FORMNO_HUSIGIBANA_MAX);

//リザードン
TO_ENUM(FORMNO_RIZAADON_NORMAL);
TO_ENUM(FORMNO_RIZAADON_MEGAX);
TO_ENUM(FORMNO_RIZAADON_MEGAY);
TO_ENUM(FORMNO_RIZAADON_MAX);

//カメックス
TO_ENUM(FORMNO_KAMEKKUSU_NORMAL);
TO_ENUM(FORMNO_KAMEKKUSU_MEGA);
TO_ENUM(FORMNO_KAMEKKUSU_MAX);

//スピアー
TO_ENUM(FORMNO_SUPIAA_NORMAL);
TO_ENUM(FORMNO_SUPIAA_MEGA);
TO_ENUM(FORMNO_SUPIAA_MAX);

//ピジョット
TO_ENUM(FORMNO_PIZYOTTO_NORMAL);
TO_ENUM(FORMNO_PIZYOTTO_MEGA);
TO_ENUM(FORMNO_PIZYOTTO_MAX);

//コラッタ
TO_ENUM(FORMNO_KORATTA_NORMAL);
TO_ENUM(FORMNO_KORATTA_ALOLA);
TO_ENUM(FORMNO_KORATTA_MAX);

//ラッタ
TO_ENUM(FORMNO_RATTA_NORMAL);
TO_ENUM(FORMNO_RATTA_ALOLA);
TO_ENUM(FORMNO_RATTA_NUSHI);
TO_ENUM(FORMNO_RATTA_MAX);

//ピカチュウ
TO_ENUM(FORMNO_PIKATYUU_NORMAL);
TO_ENUM(FORMNO_PIKATYUU_SATOPIKAMU);
TO_ENUM(FORMNO_PIKATYUU_SATOPIKAAG);
TO_ENUM(FORMNO_PIKATYUU_SATOPIKADP);
TO_ENUM(FORMNO_PIKATYUU_SATOPIKABW);
TO_ENUM(FORMNO_PIKATYUU_SATOPIKAXY);
TO_ENUM(FORMNO_PIKATYUU_SATOPIKASM);
TO_ENUM(FORMNO_PIKATYUU_SATOPIKA20);
TO_ENUM(FORMNO_PIKATYUU_MAX);

//ライチュウ
TO_ENUM(FORMNO_RAITYUU_NORMAL);
TO_ENUM(FORMNO_RAITYUU_ALOLA);
TO_ENUM(FORMNO_RAITYUU_MAX);

//サンド
TO_ENUM(FORMNO_SANDO_NORMAL);
TO_ENUM(FORMNO_SANDO_ALOLA);
TO_ENUM(FORMNO_SANDO_MAX);

//サンドパン
TO_ENUM(FORMNO_SANDOPAN_NORMAL);
TO_ENUM(FORMNO_SANDOPAN_ALOLA);
TO_ENUM(FORMNO_SANDOPAN_MAX);

//ロコン
TO_ENUM(FORMNO_ROKON_NORMAL);
TO_ENUM(FORMNO_ROKON_ALOLA);
TO_ENUM(FORMNO_ROKON_MAX);

//キュウコン
TO_ENUM(FORMNO_KYUUKON_NORMAL);
TO_ENUM(FORMNO_KYUUKON_ALOLA);
TO_ENUM(FORMNO_KYUUKON_MAX);

//ディグダ
TO_ENUM(FORMNO_DHIGUDA_NORMAL);
TO_ENUM(FORMNO_DHIGUDA_ALOLA);
TO_ENUM(FORMNO_DHIGUDA_MAX);

//ダグトリオ
TO_ENUM(FORMNO_DAGUTORIO_NORMAL);
TO_ENUM(FORMNO_DAGUTORIO_ALOLA);
TO_ENUM(FORMNO_DAGUTORIO_MAX);

//ニャース
TO_ENUM(FORMNO_NYAASU_NORMAL);
TO_ENUM(FORMNO_NYAASU_ALOLA);
TO_ENUM(FORMNO_NYAASU_MAX);

//ペルシアン
TO_ENUM(FORMNO_PERUSIAN_NORMAL);
TO_ENUM(FORMNO_PERUSIAN_ALOLA);
TO_ENUM(FORMNO_PERUSIAN_MAX);

//フーディン
TO_ENUM(FORMNO_HUUDHIN_NORMAL);
TO_ENUM(FORMNO_HUUDHIN_MEGA);
TO_ENUM(FORMNO_HUUDHIN_MAX);

//イシツブテ
TO_ENUM(FORMNO_ISITUBUTE_NORMAL);
TO_ENUM(FORMNO_ISITUBUTE_ALOLA);
TO_ENUM(FORMNO_ISITUBUTE_MAX);

//ゴローン
TO_ENUM(FORMNO_GOROON_NORMAL);
TO_ENUM(FORMNO_GOROON_ALOLA);
TO_ENUM(FORMNO_GOROON_MAX);

//ゴローニャ
TO_ENUM(FORMNO_GOROONYA_NORMAL);
TO_ENUM(FORMNO_GOROONYA_ALOLA);
TO_ENUM(FORMNO_GOROONYA_MAX);

//ヤドラン
TO_ENUM(FORMNO_YADORAN_NORMAL);
TO_ENUM(FORMNO_YADORAN_MEGA);
TO_ENUM(FORMNO_YADORAN_MAX);

//ベトベター
TO_ENUM(FORMNO_BETOBETAA_NORMAL);
TO_ENUM(FORMNO_BETOBETAA_ALOLA);
TO_ENUM(FORMNO_BETOBETAA_MAX);

//ベトベトン
TO_ENUM(FORMNO_BETOBETON_NORMAL);
TO_ENUM(FORMNO_BETOBETON_ALOLA);
TO_ENUM(FORMNO_BETOBETON_MAX);

//ゲンガー
TO_ENUM(FORMNO_GENGAA_NORMAL);
TO_ENUM(FORMNO_GENGAA_MEGA);
TO_ENUM(FORMNO_GENGAA_MAX);

//ナッシー
TO_ENUM(FORMNO_NASSII_NORMAL);
TO_ENUM(FORMNO_NASSII_ALOLA);
TO_ENUM(FORMNO_NASSII_MAX);

//ガラガラ
TO_ENUM(FORMNO_GARAGARA_NORMAL);
TO_ENUM(FORMNO_GARAGARA_ALOLA);
TO_ENUM(FORMNO_GARAGARA_MAX);

//ガルーラ
TO_ENUM(FORMNO_GARUURA_NORMAL);
TO_ENUM(FORMNO_GARUURA_MEGA);
TO_ENUM(FORMNO_GARUURA_MAX);

//カイロス
TO_ENUM(FORMNO_KAIROSU_NORMAL);
TO_ENUM(FORMNO_KAIROSU_MEGA);
TO_ENUM(FORMNO_KAIROSU_MAX);

//ギャラドス
TO_ENUM(FORMNO_GYARADOSU_NORMAL);
TO_ENUM(FORMNO_GYARADOSU_MEGA);
TO_ENUM(FORMNO_GYARADOSU_MAX);

//プテラ
TO_ENUM(FORMNO_PUTERA_NORMAL);
TO_ENUM(FORMNO_PUTERA_MEGA);
TO_ENUM(FORMNO_PUTERA_MAX);

//ミュウツー
TO_ENUM(FORMNO_MYUUTUU_NORMAL);
TO_ENUM(FORMNO_MYUUTUU_MEGAX);
TO_ENUM(FORMNO_MYUUTUU_MEGAY);
TO_ENUM(FORMNO_MYUUTUU_MAX);

//デンリュウ
TO_ENUM(FORMNO_DENRYUU_NORMAL);
TO_ENUM(FORMNO_DENRYUU_MEGA);
TO_ENUM(FORMNO_DENRYUU_MAX);

//アンノーン
TO_ENUM(FORMNO_ANNOON_UNA);
TO_ENUM(FORMNO_ANNOON_UNB);
TO_ENUM(FORMNO_ANNOON_UNC);
TO_ENUM(FORMNO_ANNOON_UND);
TO_ENUM(FORMNO_ANNOON_UNE);
TO_ENUM(FORMNO_ANNOON_UNF);
TO_ENUM(FORMNO_ANNOON_UNG);
TO_ENUM(FORMNO_ANNOON_UNH);
TO_ENUM(FORMNO_ANNOON_UNI);
TO_ENUM(FORMNO_ANNOON_UNJ);
TO_ENUM(FORMNO_ANNOON_UNK);
TO_ENUM(FORMNO_ANNOON_UNL);
TO_ENUM(FORMNO_ANNOON_UNM);
TO_ENUM(FORMNO_ANNOON_UNN);
TO_ENUM(FORMNO_ANNOON_UNO);
TO_ENUM(FORMNO_ANNOON_UNP);
TO_ENUM(FORMNO_ANNOON_UNQ);
TO_ENUM(FORMNO_ANNOON_UNR);
TO_ENUM(FORMNO_ANNOON_UNS);
TO_ENUM(FORMNO_ANNOON_UNT);
TO_ENUM(FORMNO_ANNOON_UNU);
TO_ENUM(FORMNO_ANNOON_UNV);
TO_ENUM(FORMNO_ANNOON_UNW);
TO_ENUM(FORMNO_ANNOON_UNX);
TO_ENUM(FORMNO_ANNOON_UNY);
TO_ENUM(FORMNO_ANNOON_UNZ);
TO_ENUM(FORMNO_ANNOON_EXC);
TO_ENUM(FORMNO_ANNOON_QUE);
TO_ENUM(FORMNO_ANNOON_MAX);

//ハガネール
TO_ENUM(FORMNO_HAGANEERU_NORMAL);
TO_ENUM(FORMNO_HAGANEERU_MEGA);
TO_ENUM(FORMNO_HAGANEERU_MAX);

//ハッサム
TO_ENUM(FORMNO_HASSAMU_NORMAL);
TO_ENUM(FORMNO_HASSAMU_MEGA);
TO_ENUM(FORMNO_HASSAMU_MAX);

//ヘラクロス
TO_ENUM(FORMNO_HERAKUROSU_NORMAL);
TO_ENUM(FORMNO_HERAKUROSU_MEGA);
TO_ENUM(FORMNO_HERAKUROSU_MAX);

//ヘルガー
TO_ENUM(FORMNO_HERUGAA_NORMAL);
TO_ENUM(FORMNO_HERUGAA_MEGA);
TO_ENUM(FORMNO_HERUGAA_MAX);

//バンギラス
TO_ENUM(FORMNO_BANGIRASU_NORMAL);
TO_ENUM(FORMNO_BANGIRASU_MEGA);
TO_ENUM(FORMNO_BANGIRASU_MAX);

//ジュカイン
TO_ENUM(FORMNO_ZYUKAIN_NORMAL);
TO_ENUM(FORMNO_ZYUKAIN_MEGA);
TO_ENUM(FORMNO_ZYUKAIN_MAX);

//バシャーモ
TO_ENUM(FORMNO_BASYAAMO_NORMAL);
TO_ENUM(FORMNO_BASYAAMO_MEGA);
TO_ENUM(FORMNO_BASYAAMO_MAX);

//ラグラージ
TO_ENUM(FORMNO_RAGURAAZI_NORMAL);
TO_ENUM(FORMNO_RAGURAAZI_MEGA);
TO_ENUM(FORMNO_RAGURAAZI_MAX);

//サーナイト
TO_ENUM(FORMNO_SAANAITO_NORMAL);
TO_ENUM(FORMNO_SAANAITO_MEGA);
TO_ENUM(FORMNO_SAANAITO_MAX);

//ヤミラミ
TO_ENUM(FORMNO_YAMIRAMI_NORMAL);
TO_ENUM(FORMNO_YAMIRAMI_MEGA);
TO_ENUM(FORMNO_YAMIRAMI_MAX);

//クチート
TO_ENUM(FORMNO_KUTIITO_NORMAL);
TO_ENUM(FORMNO_KUTIITO_MEGA);
TO_ENUM(FORMNO_KUTIITO_MAX);

//ボスゴドラ
TO_ENUM(FORMNO_BOSUGODORA_NORMAL);
TO_ENUM(FORMNO_BOSUGODORA_MEGA);
TO_ENUM(FORMNO_BOSUGODORA_MAX);

//チャーレム
TO_ENUM(FORMNO_TYAAREMU_NORMAL);
TO_ENUM(FORMNO_TYAAREMU_MEGA);
TO_ENUM(FORMNO_TYAAREMU_MAX);

//ライボルト
TO_ENUM(FORMNO_RAIBORUTO_NORMAL);
TO_ENUM(FORMNO_RAIBORUTO_MEGA);
TO_ENUM(FORMNO_RAIBORUTO_MAX);

//サメハダー
TO_ENUM(FORMNO_SAMEHADAA_NORMAL);
TO_ENUM(FORMNO_SAMEHADAA_MEGA);
TO_ENUM(FORMNO_SAMEHADAA_MAX);

//バクーダ
TO_ENUM(FORMNO_BAKUUDA_NORMAL);
TO_ENUM(FORMNO_BAKUUDA_MEGA);
TO_ENUM(FORMNO_BAKUUDA_MAX);

//チルタリス
TO_ENUM(FORMNO_TIRUTARISU_NORMAL);
TO_ENUM(FORMNO_TIRUTARISU_MEGA);
TO_ENUM(FORMNO_TIRUTARISU_MAX);

//ポワルン
TO_ENUM(FORMNO_POWARUN_NORMAL);
TO_ENUM(FORMNO_POWARUN_SUN);
TO_ENUM(FORMNO_POWARUN_RAIN);
TO_ENUM(FORMNO_POWARUN_SNOW);
TO_ENUM(FORMNO_POWARUN_MAX);

//ジュペッタ
TO_ENUM(FORMNO_ZYUPETTA_NORMAL);
TO_ENUM(FORMNO_ZYUPETTA_MEGA);
TO_ENUM(FORMNO_ZYUPETTA_MAX);

//アブソル
TO_ENUM(FORMNO_ABUSORU_NORMAL);
TO_ENUM(FORMNO_ABUSORU_MEGA);
TO_ENUM(FORMNO_ABUSORU_MAX);

//オニゴーリ
TO_ENUM(FORMNO_ONIGOORI_NORMAL);
TO_ENUM(FORMNO_ONIGOORI_MEGA);
TO_ENUM(FORMNO_ONIGOORI_MAX);

//ボーマンダ
TO_ENUM(FORMNO_BOOMANDA_NORMAL);
TO_ENUM(FORMNO_BOOMANDA_MEGA);
TO_ENUM(FORMNO_BOOMANDA_MAX);

//メタグロス
TO_ENUM(FORMNO_METAGUROSU_NORMAL);
TO_ENUM(FORMNO_METAGUROSU_MEGA);
TO_ENUM(FORMNO_METAGUROSU_MAX);

//ラティアス
TO_ENUM(FORMNO_RATHIASU_NORMAL);
TO_ENUM(FORMNO_RATHIASU_MEGA);
TO_ENUM(FORMNO_RATHIASU_MAX);

//ラティオス
TO_ENUM(FORMNO_RATHIOSU_NORMAL);
TO_ENUM(FORMNO_RATHIOSU_MEGA);
TO_ENUM(FORMNO_RATHIOSU_MAX);

//カイオーガ
TO_ENUM(FORMNO_KAIOOGA_NORMAL);
TO_ENUM(FORMNO_KAIOOGA_ALPHA);
TO_ENUM(FORMNO_KAIOOGA_MAX);

//グラードン
TO_ENUM(FORMNO_GURAADON_NORMAL);
TO_ENUM(FORMNO_GURAADON_OMEGA);
TO_ENUM(FORMNO_GURAADON_MAX);

//レックウザ
TO_ENUM(FORMNO_REKKUUZA_NORMAL);
TO_ENUM(FORMNO_REKKUUZA_DELTA);
TO_ENUM(FORMNO_REKKUUZA_MAX);

//デオキシス
TO_ENUM(FORMNO_DEOKISISU_NORMAL);
TO_ENUM(FORMNO_DEOKISISU_ATTACK);
TO_ENUM(FORMNO_DEOKISISU_DEFENCE);
TO_ENUM(FORMNO_DEOKISISU_SPEED);
TO_ENUM(FORMNO_DEOKISISU_MAX);

//ミノムッチ
TO_ENUM(FORMNO_MINOMUTTI_KUSA);
TO_ENUM(FORMNO_MINOMUTTI_SUNA);
TO_ENUM(FORMNO_MINOMUTTI_GOMI);
TO_ENUM(FORMNO_MINOMUTTI_MAX);

//ミノマダム
TO_ENUM(FORMNO_MINOMADAMU_KUSA);
TO_ENUM(FORMNO_MINOMADAMU_JIMEN);
TO_ENUM(FORMNO_MINOMADAMU_HAGANE);
TO_ENUM(FORMNO_MINOMADAMU_MAX);

//チェリム
TO_ENUM(FORMNO_THERIMU_NEGA);
TO_ENUM(FORMNO_THERIMU_POSI);
TO_ENUM(FORMNO_THERIMU_MAX);

//カラナクシ
TO_ENUM(FORMNO_KARANAKUSI_WEST);
TO_ENUM(FORMNO_KARANAKUSI_EAST);
TO_ENUM(FORMNO_KARANAKUSI_MAX);

//トリトドン
TO_ENUM(FORMNO_TORITODON_WEST);
TO_ENUM(FORMNO_TORITODON_EAST);
TO_ENUM(FORMNO_TORITODON_MAX);

//ミミロップ
TO_ENUM(FORMNO_MIMIROPPU_NORMAL);
TO_ENUM(FORMNO_MIMIROPPU_MEGA);
TO_ENUM(FORMNO_MIMIROPPU_MAX);

//ガブリアス
TO_ENUM(FORMNO_GABURIASU_NORMAL);
TO_ENUM(FORMNO_GABURIASU_MEGA);
TO_ENUM(FORMNO_GABURIASU_MAX);

//ルカリオ
TO_ENUM(FORMNO_RUKARIO_NORMAL);
TO_ENUM(FORMNO_RUKARIO_MEGA);
TO_ENUM(FORMNO_RUKARIO_MAX);

//ユキノオー
TO_ENUM(FORMNO_YUKINOOO_NORMAL);
TO_ENUM(FORMNO_YUKINOOO_MEGA);
TO_ENUM(FORMNO_YUKINOOO_MAX);

//エルレイド
TO_ENUM(FORMNO_ERUREIDO_NORMAL);
TO_ENUM(FORMNO_ERUREIDO_MEGA);
TO_ENUM(FORMNO_ERUREIDO_MAX);

//ロトム
TO_ENUM(FORMNO_ROTOMU_NORMAL);
TO_ENUM(FORMNO_ROTOMU_HOT);
TO_ENUM(FORMNO_ROTOMU_WASH);
TO_ENUM(FORMNO_ROTOMU_COLD);
TO_ENUM(FORMNO_ROTOMU_FAN);
TO_ENUM(FORMNO_ROTOMU_CUT);
TO_ENUM(FORMNO_ROTOMU_MAX);

//ギラティナ
TO_ENUM(FORMNO_GIRATHINA_ANOTHER);
TO_ENUM(FORMNO_GIRATHINA_ORIGIN);
TO_ENUM(FORMNO_GIRATHINA_MAX);

//シェイミ
TO_ENUM(FORMNO_SHEIMI_LAND);
TO_ENUM(FORMNO_SHEIMI_SKY);
TO_ENUM(FORMNO_SHEIMI_MAX);

//アルセウス
TO_ENUM(FORMNO_ARUSEUSU_NORMAL);
TO_ENUM(FORMNO_ARUSEUSU_BATTLE);
TO_ENUM(FORMNO_ARUSEUSU_HIKOU);
TO_ENUM(FORMNO_ARUSEUSU_POISON);
TO_ENUM(FORMNO_ARUSEUSU_JIMEN);
TO_ENUM(FORMNO_ARUSEUSU_IWA);
TO_ENUM(FORMNO_ARUSEUSU_MUSHI);
TO_ENUM(FORMNO_ARUSEUSU_GHOST);
TO_ENUM(FORMNO_ARUSEUSU_METAL);
TO_ENUM(FORMNO_ARUSEUSU_FIRE);
TO_ENUM(FORMNO_ARUSEUSU_WATER);
TO_ENUM(FORMNO_ARUSEUSU_KUSA);
TO_ENUM(FORMNO_ARUSEUSU_ELECTRIC);
TO_ENUM(FORMNO_ARUSEUSU_ESPER);
TO_ENUM(FORMNO_ARUSEUSU_KOORI);
TO_ENUM(FORMNO_ARUSEUSU_DRAGON);
TO_ENUM(FORMNO_ARUSEUSU_AKU);
TO_ENUM(FORMNO_ARUSEUSU_FAIRY);
TO_ENUM(FORMNO_ARUSEUSU_MAX);

//タブンネ
TO_ENUM(FORMNO_TABUNNE_NORMAL);
TO_ENUM(FORMNO_TABUNNE_MEGA);
TO_ENUM(FORMNO_TABUNNE_MAX);

//バスラオ
TO_ENUM(FORMNO_BASURAO_BLACK);
TO_ENUM(FORMNO_BASURAO_WHITE);
TO_ENUM(FORMNO_BASURAO_MAX);

//ヒヒダルマ
TO_ENUM(FORMNO_HIHIDARUMA_ACTION);
TO_ENUM(FORMNO_HIHIDARUMA_MEDITATION);
TO_ENUM(FORMNO_HIHIDARUMA_MAX);

//シキジカ
TO_ENUM(FORMNO_SIKIZIKA_SPRING);
TO_ENUM(FORMNO_SIKIZIKA_SUMMER);
TO_ENUM(FORMNO_SIKIZIKA_AUTUMN);
TO_ENUM(FORMNO_SIKIZIKA_WINTER);
TO_ENUM(FORMNO_SIKIZIKA_MAX);

//メブキジカ
TO_ENUM(FORMNO_MEBUKIZIKA_SPRING);
TO_ENUM(FORMNO_MEBUKIZIKA_SUMMER);
TO_ENUM(FORMNO_MEBUKIZIKA_AUTUMN);
TO_ENUM(FORMNO_MEBUKIZIKA_WINTER);
TO_ENUM(FORMNO_MEBUKIZIKA_MAX);

//トルネロス
TO_ENUM(FORMNO_TORUNEROSU_NORMAL);
TO_ENUM(FORMNO_TORUNEROSU_AR);
TO_ENUM(FORMNO_TORUNEROSU_MAX);

//ボルトロス
TO_ENUM(FORMNO_BORUTOROSU_NORMAL);
TO_ENUM(FORMNO_BORUTOROSU_AR);
TO_ENUM(FORMNO_BORUTOROSU_MAX);

//ランドロス
TO_ENUM(FORMNO_RANDOROSU_NORMAL);
TO_ENUM(FORMNO_RANDOROSU_AR);
TO_ENUM(FORMNO_RANDOROSU_MAX);

//キュレム
TO_ENUM(FORMNO_KYUREMU_A);
TO_ENUM(FORMNO_KYUREMU_WHITE);
TO_ENUM(FORMNO_KYUREMU_BLACK);
TO_ENUM(FORMNO_KYUREMU_MAX);

//ケルディオ
TO_ENUM(FORMNO_KERUDHIO_NORMAL);
TO_ENUM(FORMNO_KERUDHIO_SWORD);
TO_ENUM(FORMNO_KERUDHIO_MAX);

//メロエッタ
TO_ENUM(FORMNO_MEROETTA_VOICE);
TO_ENUM(FORMNO_MEROETTA_STEP);
TO_ENUM(FORMNO_MEROETTA_MAX);

//ゲノセクト
TO_ENUM(FORMNO_GENOSEKUTO_NORMAL);
TO_ENUM(FORMNO_GENOSEKUTO_AQUA);
TO_ENUM(FORMNO_GENOSEKUTO_INAZUMA);
TO_ENUM(FORMNO_GENOSEKUTO_BLAZE);
TO_ENUM(FORMNO_GENOSEKUTO_FREEZE);
TO_ENUM(FORMNO_GENOSEKUTO_MAX);

//ゲッコウガ
TO_ENUM(FORMNO_GEKKOUGA_NORMAL);
TO_ENUM(FORMNO_GEKKOUGA_GEKKOUGA2);
TO_ENUM(FORMNO_GEKKOUGA_SATOSHI);
TO_ENUM(FORMNO_GEKKOUGA_MAX);

//ビビヨン
TO_ENUM(FORMNO_BIBIYON_AREA1);
TO_ENUM(FORMNO_BIBIYON_AREA2);
TO_ENUM(FORMNO_BIBIYON_AREA3);
TO_ENUM(FORMNO_BIBIYON_AREA4);
TO_ENUM(FORMNO_BIBIYON_AREA5);
TO_ENUM(FORMNO_BIBIYON_AREA6);
TO_ENUM(FORMNO_BIBIYON_AREA7);
TO_ENUM(FORMNO_BIBIYON_AREA8);
TO_ENUM(FORMNO_BIBIYON_AREA9);
TO_ENUM(FORMNO_BIBIYON_AREA10);
TO_ENUM(FORMNO_BIBIYON_AREA11);
TO_ENUM(FORMNO_BIBIYON_AREA12);
TO_ENUM(FORMNO_BIBIYON_AREA13);
TO_ENUM(FORMNO_BIBIYON_AREA14);
TO_ENUM(FORMNO_BIBIYON_AREA15);
TO_ENUM(FORMNO_BIBIYON_AREA16);
TO_ENUM(FORMNO_BIBIYON_AREA17);
TO_ENUM(FORMNO_BIBIYON_AREA18);
TO_ENUM(FORMNO_BIBIYON_AREA19);
TO_ENUM(FORMNO_BIBIYON_AREA20);
TO_ENUM(FORMNO_BIBIYON_MAX);

//フラベベ
TO_ENUM(FORMNO_HURABEBE_RED);
TO_ENUM(FORMNO_HURABEBE_YELLOW);
TO_ENUM(FORMNO_HURABEBE_ORANGE);
TO_ENUM(FORMNO_HURABEBE_BLUE);
TO_ENUM(FORMNO_HURABEBE_WHITE);
TO_ENUM(FORMNO_HURABEBE_MAX);

//フラエッテ
TO_ENUM(FORMNO_HURAETTE_RED);
TO_ENUM(FORMNO_HURAETTE_YELLOW);
TO_ENUM(FORMNO_HURAETTE_ORANGE);
TO_ENUM(FORMNO_HURAETTE_BLUE);
TO_ENUM(FORMNO_HURAETTE_WHITE);
TO_ENUM(FORMNO_HURAETTE_HAKAI);
TO_ENUM(FORMNO_HURAETTE_MAX);

//フラージェス
TO_ENUM(FORMNO_HURAAJESU_RED);
TO_ENUM(FORMNO_HURAAJESU_YELLOW);
TO_ENUM(FORMNO_HURAAJESU_ORANGE);
TO_ENUM(FORMNO_HURAAJESU_BLUE);
TO_ENUM(FORMNO_HURAAJESU_WHITE);
TO_ENUM(FORMNO_HURAAJESU_MAX);

//トリミアン
TO_ENUM(FORMNO_TORIMIAN_NORMAL);
TO_ENUM(FORMNO_TORIMIAN_HEART);
TO_ENUM(FORMNO_TORIMIAN_STAR);
TO_ENUM(FORMNO_TORIMIAN_DIAMOND);
TO_ENUM(FORMNO_TORIMIAN_YOUNGLADY);
TO_ENUM(FORMNO_TORIMIAN_LADY);
TO_ENUM(FORMNO_TORIMIAN_GENTLEMAN);
TO_ENUM(FORMNO_TORIMIAN_ANTOINETTE);
TO_ENUM(FORMNO_TORIMIAN_RENJISHI);
TO_ENUM(FORMNO_TORIMIAN_SPHINX);
TO_ENUM(FORMNO_TORIMIAN_MAX);

//ニャオニクス
TO_ENUM(FORMNO_NYAONIKUSU_MALE);
TO_ENUM(FORMNO_NYAONIKUSU_FEMALE);
TO_ENUM(FORMNO_NYAONIKUSU_MAX);

//ギルガルド
TO_ENUM(FORMNO_GIRUGARUDO_TATE);
TO_ENUM(FORMNO_GIRUGARUDO_HOKO);
TO_ENUM(FORMNO_GIRUGARUDO_MAX);

//バケッチャ
TO_ENUM(FORMNO_BAKETTYA_NORMAL);
TO_ENUM(FORMNO_BAKETTYA_SMALL);
TO_ENUM(FORMNO_BAKETTYA_BIG);
TO_ENUM(FORMNO_BAKETTYA_KING);
TO_ENUM(FORMNO_BAKETTYA_MAX);

//パンプジン
TO_ENUM(FORMNO_PANPUZIN_NORMAL);
TO_ENUM(FORMNO_PANPUZIN_SMALL);
TO_ENUM(FORMNO_PANPUZIN_BIG);
TO_ENUM(FORMNO_PANPUZIN_KING);
TO_ENUM(FORMNO_PANPUZIN_MAX);

//ゼルネアス
TO_ENUM(FORMNO_ZERUNEASU_NORMAL);
TO_ENUM(FORMNO_ZERUNEASU_RADIATION);
TO_ENUM(FORMNO_ZERUNEASU_MAX);

//ジガルデ
TO_ENUM(FORMNO_ZIGARUDE_50PER);
TO_ENUM(FORMNO_ZIGARUDE_10PER);
TO_ENUM(FORMNO_ZIGARUDE_SW10PER);
TO_ENUM(FORMNO_ZIGARUDE_SW50PER);
TO_ENUM(FORMNO_ZIGARUDE_100PER);
TO_ENUM(FORMNO_ZIGARUDE_MAX);

//ディアンシー
TO_ENUM(FORMNO_DHIANSII_NORMAL);
TO_ENUM(FORMNO_DHIANSII_MEGA);
TO_ENUM(FORMNO_DHIANSII_MAX);

//フーパ
TO_ENUM(FORMNO_HUUPA_NORMAL);
TO_ENUM(FORMNO_HUUPA_EARNEST);
TO_ENUM(FORMNO_HUUPA_MAX);

//デカグース
TO_ENUM(FORMNO_MANGUUSU2_NORMAL);
TO_ENUM(FORMNO_MANGUUSU2_NUSHI);
TO_ENUM(FORMNO_MANGUUSU2_MAX);

//クワガノン
TO_ENUM(FORMNO_KUWAGATA3_NORMAL);
TO_ENUM(FORMNO_KUWAGATA3_NUSHI);
TO_ENUM(FORMNO_KUWAGATA3_MAX);

//オドリドリ
TO_ENUM(FORMNO_MITUSUI_FLAMENCO);
TO_ENUM(FORMNO_MITUSUI_CHEER);
TO_ENUM(FORMNO_MITUSUI_HULA);
TO_ENUM(FORMNO_MITUSUI_NICHIBU);
TO_ENUM(FORMNO_MITUSUI_MAX);

//アブリボン
TO_ENUM(FORMNO_ABU2_NORMAL);
TO_ENUM(FORMNO_ABU2_NUSHI);
TO_ENUM(FORMNO_ABU2_MAX);

//ルガルガン
TO_ENUM(FORMNO_OOKAMI2_MIDDAY);
TO_ENUM(FORMNO_OOKAMI2_MIDNIGHT);
TO_ENUM(FORMNO_OOKAMI2_MAX);

//ヨワシ
TO_ENUM(FORMNO_YOWASI_NORMAL);
TO_ENUM(FORMNO_YOWASI_GYOGUN_L);
TO_ENUM(FORMNO_YOWASI_MAX);

//オニシズクモ
TO_ENUM(FORMNO_MIZUGUMO2_NORMAL);
TO_ENUM(FORMNO_MIZUGUMO2_NUSHI);
TO_ENUM(FORMNO_MIZUGUMO2_MAX);

//ラランテス
TO_ENUM(FORMNO_HANAKAMA2_NORMAL);
TO_ENUM(FORMNO_HANAKAMA2_NUSHI);
TO_ENUM(FORMNO_HANAKAMA2_MAX);

//エンニュート
TO_ENUM(FORMNO_DOKUTOKAGE2_NORMAL);
TO_ENUM(FORMNO_DOKUTOKAGE2_NUSHI);
TO_ENUM(FORMNO_DOKUTOKAGE2_MAX);

//シルヴァディ
TO_ENUM(FORMNO_GURIPUSU2_NORMAL);
TO_ENUM(FORMNO_GURIPUSU2_BATTLE);
TO_ENUM(FORMNO_GURIPUSU2_HIKOU);
TO_ENUM(FORMNO_GURIPUSU2_POISON);
TO_ENUM(FORMNO_GURIPUSU2_JIMEN);
TO_ENUM(FORMNO_GURIPUSU2_IWA);
TO_ENUM(FORMNO_GURIPUSU2_MUSHI);
TO_ENUM(FORMNO_GURIPUSU2_GHOST);
TO_ENUM(FORMNO_GURIPUSU2_METAL);
TO_ENUM(FORMNO_GURIPUSU2_FIRE);
TO_ENUM(FORMNO_GURIPUSU2_WATER);
TO_ENUM(FORMNO_GURIPUSU2_KUSA);
TO_ENUM(FORMNO_GURIPUSU2_ELECTRIC);
TO_ENUM(FORMNO_GURIPUSU2_ESPER);
TO_ENUM(FORMNO_GURIPUSU2_KOORI);
TO_ENUM(FORMNO_GURIPUSU2_DRAGON);
TO_ENUM(FORMNO_GURIPUSU2_AKU);
TO_ENUM(FORMNO_GURIPUSU2_FAIRY);
TO_ENUM(FORMNO_GURIPUSU2_MAX);

//メテノ
TO_ENUM(FORMNO_NAGAREBOSI_M_RED);
TO_ENUM(FORMNO_NAGAREBOSI_M_ORANGE);
TO_ENUM(FORMNO_NAGAREBOSI_M_YELLOW);
TO_ENUM(FORMNO_NAGAREBOSI_M_GREEN);
TO_ENUM(FORMNO_NAGAREBOSI_M_BLUE);
TO_ENUM(FORMNO_NAGAREBOSI_M_INDIGO);
TO_ENUM(FORMNO_NAGAREBOSI_M_PURPLE);
TO_ENUM(FORMNO_NAGAREBOSI_RED);
TO_ENUM(FORMNO_NAGAREBOSI_ORANGE);
TO_ENUM(FORMNO_NAGAREBOSI_YELLOW);
TO_ENUM(FORMNO_NAGAREBOSI_GREEN);
TO_ENUM(FORMNO_NAGAREBOSI_BLUE);
TO_ENUM(FORMNO_NAGAREBOSI_INDIGO);
TO_ENUM(FORMNO_NAGAREBOSI_PURPLE);
TO_ENUM(FORMNO_NAGAREBOSI_MAX);

//ミミッキュ
TO_ENUM(FORMNO_HORAA_NORMAL);
TO_ENUM(FORMNO_HORAA_KUBIORE);
TO_ENUM(FORMNO_HORAA_NORMAL_NUSHI);
TO_ENUM(FORMNO_HORAA_KUBIORE_NUSHI);
TO_ENUM(FORMNO_HORAA_MAX);

//ジャラランガ
TO_ENUM(FORMNO_UROKO3_NORMAL);
TO_ENUM(FORMNO_UROKO3_NUSHI);
TO_ENUM(FORMNO_UROKO3_MAX);

//ネクロズマ
TO_ENUM(FORMNO_PURIZUMU_NORMAL);
TO_ENUM(FORMNO_PURIZUMU_FORM_S);
TO_ENUM(FORMNO_PURIZUMU_FORM_L);
TO_ENUM(FORMNO_PURIZUMU_FORM_N);
TO_ENUM(FORMNO_PURIZUMU_MAX);

//マギアナ
TO_ENUM(FORMNO_MABOROSI16_PRESENT);
TO_ENUM(FORMNO_MABOROSI16_PAST);
TO_ENUM(FORMNO_MABOROSI16_MAX);

TO_ENUM(FORMNO_TAMAGO_NORMAL);
TO_ENUM(FORMNO_TAMAGO_MANAFI);
TO_ENUM(FORMNO_TAMAGO_MAX);

TO_ENUM(OTHER_FORM_MAX);

// １種族あたりのフォルム数の最大値
TO_ENUM(MAX_FORM_NUM);



//別フォルム定義
//フシギバナ
#undef  FORMNO_HUSIGIBANA_NORMAL
#undef  FORMNO_HUSIGIBANA_MEGA
#undef  FORMNO_HUSIGIBANA_MAX

//リザードン
#undef  FORMNO_RIZAADON_NORMAL
#undef  FORMNO_RIZAADON_MEGAX
#undef  FORMNO_RIZAADON_MEGAY
#undef  FORMNO_RIZAADON_MAX

//カメックス
#undef  FORMNO_KAMEKKUSU_NORMAL
#undef  FORMNO_KAMEKKUSU_MEGA
#undef  FORMNO_KAMEKKUSU_MAX

//スピアー
#undef  FORMNO_SUPIAA_NORMAL
#undef  FORMNO_SUPIAA_MEGA
#undef  FORMNO_SUPIAA_MAX

//ピジョット
#undef  FORMNO_PIZYOTTO_NORMAL
#undef  FORMNO_PIZYOTTO_MEGA
#undef  FORMNO_PIZYOTTO_MAX

//コラッタ
#undef  FORMNO_KORATTA_NORMAL
#undef  FORMNO_KORATTA_ALOLA
#undef  FORMNO_KORATTA_MAX

//ラッタ
#undef  FORMNO_RATTA_NORMAL
#undef  FORMNO_RATTA_ALOLA
#undef  FORMNO_RATTA_NUSHI
#undef  FORMNO_RATTA_MAX

//ピカチュウ
#undef  FORMNO_PIKATYUU_NORMAL
#undef  FORMNO_PIKATYUU_SATOPIKAMU
#undef  FORMNO_PIKATYUU_SATOPIKAAG
#undef  FORMNO_PIKATYUU_SATOPIKADP
#undef  FORMNO_PIKATYUU_SATOPIKABW
#undef  FORMNO_PIKATYUU_SATOPIKAXY
#undef  FORMNO_PIKATYUU_SATOPIKASM
#undef  FORMNO_PIKATYUU_SATOPIKA20
#undef  FORMNO_PIKATYUU_MAX

//ライチュウ
#undef  FORMNO_RAITYUU_NORMAL
#undef  FORMNO_RAITYUU_ALOLA
#undef  FORMNO_RAITYUU_MAX

//サンド
#undef  FORMNO_SANDO_NORMAL
#undef  FORMNO_SANDO_ALOLA
#undef  FORMNO_SANDO_MAX

//サンドパン
#undef  FORMNO_SANDOPAN_NORMAL
#undef  FORMNO_SANDOPAN_ALOLA
#undef  FORMNO_SANDOPAN_MAX

//ロコン
#undef  FORMNO_ROKON_NORMAL
#undef  FORMNO_ROKON_ALOLA
#undef  FORMNO_ROKON_MAX

//キュウコン
#undef  FORMNO_KYUUKON_NORMAL
#undef  FORMNO_KYUUKON_ALOLA
#undef  FORMNO_KYUUKON_MAX

//ディグダ
#undef  FORMNO_DHIGUDA_NORMAL
#undef  FORMNO_DHIGUDA_ALOLA
#undef  FORMNO_DHIGUDA_MAX

//ダグトリオ
#undef  FORMNO_DAGUTORIO_NORMAL
#undef  FORMNO_DAGUTORIO_ALOLA
#undef  FORMNO_DAGUTORIO_MAX

//ニャース
#undef  FORMNO_NYAASU_NORMAL
#undef  FORMNO_NYAASU_ALOLA
#undef  FORMNO_NYAASU_MAX

//ペルシアン
#undef  FORMNO_PERUSIAN_NORMAL
#undef  FORMNO_PERUSIAN_ALOLA
#undef  FORMNO_PERUSIAN_MAX

//フーディン
#undef  FORMNO_HUUDHIN_NORMAL
#undef  FORMNO_HUUDHIN_MEGA
#undef  FORMNO_HUUDHIN_MAX

//イシツブテ
#undef  FORMNO_ISITUBUTE_NORMAL
#undef  FORMNO_ISITUBUTE_ALOLA
#undef  FORMNO_ISITUBUTE_MAX

//ゴローン
#undef  FORMNO_GOROON_NORMAL
#undef  FORMNO_GOROON_ALOLA
#undef  FORMNO_GOROON_MAX

//ゴローニャ
#undef  FORMNO_GOROONYA_NORMAL
#undef  FORMNO_GOROONYA_ALOLA
#undef  FORMNO_GOROONYA_MAX

//ヤドラン
#undef  FORMNO_YADORAN_NORMAL
#undef  FORMNO_YADORAN_MEGA
#undef  FORMNO_YADORAN_MAX

//ベトベター
#undef  FORMNO_BETOBETAA_NORMAL
#undef  FORMNO_BETOBETAA_ALOLA
#undef  FORMNO_BETOBETAA_MAX

//ベトベトン
#undef  FORMNO_BETOBETON_NORMAL
#undef  FORMNO_BETOBETON_ALOLA
#undef  FORMNO_BETOBETON_MAX

//ゲンガー
#undef  FORMNO_GENGAA_NORMAL
#undef  FORMNO_GENGAA_MEGA
#undef  FORMNO_GENGAA_MAX

//ナッシー
#undef  FORMNO_NASSII_NORMAL
#undef  FORMNO_NASSII_ALOLA
#undef  FORMNO_NASSII_MAX

//ガラガラ
#undef  FORMNO_GARAGARA_NORMAL
#undef  FORMNO_GARAGARA_ALOLA
#undef  FORMNO_GARAGARA_MAX

//ガルーラ
#undef  FORMNO_GARUURA_NORMAL
#undef  FORMNO_GARUURA_MEGA
#undef  FORMNO_GARUURA_MAX

//カイロス
#undef  FORMNO_KAIROSU_NORMAL
#undef  FORMNO_KAIROSU_MEGA
#undef  FORMNO_KAIROSU_MAX

//ギャラドス
#undef  FORMNO_GYARADOSU_NORMAL
#undef  FORMNO_GYARADOSU_MEGA
#undef  FORMNO_GYARADOSU_MAX

//プテラ
#undef  FORMNO_PUTERA_NORMAL
#undef  FORMNO_PUTERA_MEGA
#undef  FORMNO_PUTERA_MAX

//ミュウツー
#undef  FORMNO_MYUUTUU_NORMAL
#undef  FORMNO_MYUUTUU_MEGAX
#undef  FORMNO_MYUUTUU_MEGAY
#undef  FORMNO_MYUUTUU_MAX

//デンリュウ
#undef  FORMNO_DENRYUU_NORMAL
#undef  FORMNO_DENRYUU_MEGA
#undef  FORMNO_DENRYUU_MAX

//アンノーン
#undef  FORMNO_ANNOON_UNA
#undef  FORMNO_ANNOON_UNB
#undef  FORMNO_ANNOON_UNC
#undef  FORMNO_ANNOON_UND
#undef  FORMNO_ANNOON_UNE
#undef  FORMNO_ANNOON_UNF
#undef  FORMNO_ANNOON_UNG
#undef  FORMNO_ANNOON_UNH
#undef  FORMNO_ANNOON_UNI
#undef  FORMNO_ANNOON_UNJ
#undef  FORMNO_ANNOON_UNK
#undef  FORMNO_ANNOON_UNL
#undef  FORMNO_ANNOON_UNM
#undef  FORMNO_ANNOON_UNN
#undef  FORMNO_ANNOON_UNO
#undef  FORMNO_ANNOON_UNP
#undef  FORMNO_ANNOON_UNQ
#undef  FORMNO_ANNOON_UNR
#undef  FORMNO_ANNOON_UNS
#undef  FORMNO_ANNOON_UNT
#undef  FORMNO_ANNOON_UNU
#undef  FORMNO_ANNOON_UNV
#undef  FORMNO_ANNOON_UNW
#undef  FORMNO_ANNOON_UNX
#undef  FORMNO_ANNOON_UNY
#undef  FORMNO_ANNOON_UNZ
#undef  FORMNO_ANNOON_EXC
#undef  FORMNO_ANNOON_QUE
#undef  FORMNO_ANNOON_MAX

//ハガネール
#undef  FORMNO_HAGANEERU_NORMAL
#undef  FORMNO_HAGANEERU_MEGA
#undef  FORMNO_HAGANEERU_MAX

//ハッサム
#undef  FORMNO_HASSAMU_NORMAL
#undef  FORMNO_HASSAMU_MEGA
#undef  FORMNO_HASSAMU_MAX

//ヘラクロス
#undef  FORMNO_HERAKUROSU_NORMAL
#undef  FORMNO_HERAKUROSU_MEGA
#undef  FORMNO_HERAKUROSU_MAX

//ヘルガー
#undef  FORMNO_HERUGAA_NORMAL
#undef  FORMNO_HERUGAA_MEGA
#undef  FORMNO_HERUGAA_MAX

//バンギラス
#undef  FORMNO_BANGIRASU_NORMAL
#undef  FORMNO_BANGIRASU_MEGA
#undef  FORMNO_BANGIRASU_MAX

//ジュカイン
#undef  FORMNO_ZYUKAIN_NORMAL
#undef  FORMNO_ZYUKAIN_MEGA
#undef  FORMNO_ZYUKAIN_MAX

//バシャーモ
#undef  FORMNO_BASYAAMO_NORMAL
#undef  FORMNO_BASYAAMO_MEGA
#undef  FORMNO_BASYAAMO_MAX

//ラグラージ
#undef  FORMNO_RAGURAAZI_NORMAL
#undef  FORMNO_RAGURAAZI_MEGA
#undef  FORMNO_RAGURAAZI_MAX

//サーナイト
#undef  FORMNO_SAANAITO_NORMAL
#undef  FORMNO_SAANAITO_MEGA
#undef  FORMNO_SAANAITO_MAX

//ヤミラミ
#undef  FORMNO_YAMIRAMI_NORMAL
#undef  FORMNO_YAMIRAMI_MEGA
#undef  FORMNO_YAMIRAMI_MAX

//クチート
#undef  FORMNO_KUTIITO_NORMAL
#undef  FORMNO_KUTIITO_MEGA
#undef  FORMNO_KUTIITO_MAX

//ボスゴドラ
#undef  FORMNO_BOSUGODORA_NORMAL
#undef  FORMNO_BOSUGODORA_MEGA
#undef  FORMNO_BOSUGODORA_MAX

//チャーレム
#undef  FORMNO_TYAAREMU_NORMAL
#undef  FORMNO_TYAAREMU_MEGA
#undef  FORMNO_TYAAREMU_MAX

//ライボルト
#undef  FORMNO_RAIBORUTO_NORMAL
#undef  FORMNO_RAIBORUTO_MEGA
#undef  FORMNO_RAIBORUTO_MAX

//サメハダー
#undef  FORMNO_SAMEHADAA_NORMAL
#undef  FORMNO_SAMEHADAA_MEGA
#undef  FORMNO_SAMEHADAA_MAX

//バクーダ
#undef  FORMNO_BAKUUDA_NORMAL
#undef  FORMNO_BAKUUDA_MEGA
#undef  FORMNO_BAKUUDA_MAX

//チルタリス
#undef  FORMNO_TIRUTARISU_NORMAL
#undef  FORMNO_TIRUTARISU_MEGA
#undef  FORMNO_TIRUTARISU_MAX

//ポワルン
#undef  FORMNO_POWARUN_NORMAL
#undef  FORMNO_POWARUN_SUN
#undef  FORMNO_POWARUN_RAIN
#undef  FORMNO_POWARUN_SNOW
#undef  FORMNO_POWARUN_MAX

//ジュペッタ
#undef  FORMNO_ZYUPETTA_NORMAL
#undef  FORMNO_ZYUPETTA_MEGA
#undef  FORMNO_ZYUPETTA_MAX

//アブソル
#undef  FORMNO_ABUSORU_NORMAL
#undef  FORMNO_ABUSORU_MEGA
#undef  FORMNO_ABUSORU_MAX

//オニゴーリ
#undef  FORMNO_ONIGOORI_NORMAL
#undef  FORMNO_ONIGOORI_MEGA
#undef  FORMNO_ONIGOORI_MAX

//ボーマンダ
#undef  FORMNO_BOOMANDA_NORMAL
#undef  FORMNO_BOOMANDA_MEGA
#undef  FORMNO_BOOMANDA_MAX

//メタグロス
#undef  FORMNO_METAGUROSU_NORMAL
#undef  FORMNO_METAGUROSU_MEGA
#undef  FORMNO_METAGUROSU_MAX

//ラティアス
#undef  FORMNO_RATHIASU_NORMAL
#undef  FORMNO_RATHIASU_MEGA
#undef  FORMNO_RATHIASU_MAX

//ラティオス
#undef  FORMNO_RATHIOSU_NORMAL
#undef  FORMNO_RATHIOSU_MEGA
#undef  FORMNO_RATHIOSU_MAX

//カイオーガ
#undef  FORMNO_KAIOOGA_NORMAL
#undef  FORMNO_KAIOOGA_ALPHA
#undef  FORMNO_KAIOOGA_MAX

//グラードン
#undef  FORMNO_GURAADON_NORMAL
#undef  FORMNO_GURAADON_OMEGA
#undef  FORMNO_GURAADON_MAX

//レックウザ
#undef  FORMNO_REKKUUZA_NORMAL
#undef  FORMNO_REKKUUZA_DELTA
#undef  FORMNO_REKKUUZA_MAX

//デオキシス
#undef  FORMNO_DEOKISISU_NORMAL
#undef  FORMNO_DEOKISISU_ATTACK
#undef  FORMNO_DEOKISISU_DEFENCE
#undef  FORMNO_DEOKISISU_SPEED
#undef  FORMNO_DEOKISISU_MAX

//ミノムッチ
#undef  FORMNO_MINOMUTTI_KUSA
#undef  FORMNO_MINOMUTTI_SUNA
#undef  FORMNO_MINOMUTTI_GOMI
#undef  FORMNO_MINOMUTTI_MAX

//ミノマダム
#undef  FORMNO_MINOMADAMU_KUSA
#undef  FORMNO_MINOMADAMU_JIMEN
#undef  FORMNO_MINOMADAMU_HAGANE
#undef  FORMNO_MINOMADAMU_MAX

//チェリム
#undef  FORMNO_THERIMU_NEGA
#undef  FORMNO_THERIMU_POSI
#undef  FORMNO_THERIMU_MAX

//カラナクシ
#undef  FORMNO_KARANAKUSI_WEST
#undef  FORMNO_KARANAKUSI_EAST
#undef  FORMNO_KARANAKUSI_MAX

//トリトドン
#undef  FORMNO_TORITODON_WEST
#undef  FORMNO_TORITODON_EAST
#undef  FORMNO_TORITODON_MAX

//ミミロップ
#undef  FORMNO_MIMIROPPU_NORMAL
#undef  FORMNO_MIMIROPPU_MEGA
#undef  FORMNO_MIMIROPPU_MAX

//ガブリアス
#undef  FORMNO_GABURIASU_NORMAL
#undef  FORMNO_GABURIASU_MEGA
#undef  FORMNO_GABURIASU_MAX

//ルカリオ
#undef  FORMNO_RUKARIO_NORMAL
#undef  FORMNO_RUKARIO_MEGA
#undef  FORMNO_RUKARIO_MAX

//ユキノオー
#undef  FORMNO_YUKINOOO_NORMAL
#undef  FORMNO_YUKINOOO_MEGA
#undef  FORMNO_YUKINOOO_MAX

//エルレイド
#undef  FORMNO_ERUREIDO_NORMAL
#undef  FORMNO_ERUREIDO_MEGA
#undef  FORMNO_ERUREIDO_MAX

//ロトム
#undef  FORMNO_ROTOMU_NORMAL
#undef  FORMNO_ROTOMU_HOT
#undef  FORMNO_ROTOMU_WASH
#undef  FORMNO_ROTOMU_COLD
#undef  FORMNO_ROTOMU_FAN
#undef  FORMNO_ROTOMU_CUT
#undef  FORMNO_ROTOMU_MAX

//ギラティナ
#undef  FORMNO_GIRATHINA_ANOTHER
#undef  FORMNO_GIRATHINA_ORIGIN
#undef  FORMNO_GIRATHINA_MAX

//シェイミ
#undef  FORMNO_SHEIMI_LAND
#undef  FORMNO_SHEIMI_SKY
#undef  FORMNO_SHEIMI_MAX

//アルセウス
#undef  FORMNO_ARUSEUSU_NORMAL
#undef  FORMNO_ARUSEUSU_BATTLE
#undef  FORMNO_ARUSEUSU_HIKOU
#undef  FORMNO_ARUSEUSU_POISON
#undef  FORMNO_ARUSEUSU_JIMEN
#undef  FORMNO_ARUSEUSU_IWA
#undef  FORMNO_ARUSEUSU_MUSHI
#undef  FORMNO_ARUSEUSU_GHOST
#undef  FORMNO_ARUSEUSU_METAL
#undef  FORMNO_ARUSEUSU_FIRE
#undef  FORMNO_ARUSEUSU_WATER
#undef  FORMNO_ARUSEUSU_KUSA
#undef  FORMNO_ARUSEUSU_ELECTRIC
#undef  FORMNO_ARUSEUSU_ESPER
#undef  FORMNO_ARUSEUSU_KOORI
#undef  FORMNO_ARUSEUSU_DRAGON
#undef  FORMNO_ARUSEUSU_AKU
#undef  FORMNO_ARUSEUSU_FAIRY
#undef  FORMNO_ARUSEUSU_MAX

//タブンネ
#undef  FORMNO_TABUNNE_NORMAL
#undef  FORMNO_TABUNNE_MEGA
#undef  FORMNO_TABUNNE_MAX

//バスラオ
#undef  FORMNO_BASURAO_BLACK
#undef  FORMNO_BASURAO_WHITE
#undef  FORMNO_BASURAO_MAX

//ヒヒダルマ
#undef  FORMNO_HIHIDARUMA_ACTION
#undef  FORMNO_HIHIDARUMA_MEDITATION
#undef  FORMNO_HIHIDARUMA_MAX

//シキジカ
#undef  FORMNO_SIKIZIKA_SPRING
#undef  FORMNO_SIKIZIKA_SUMMER
#undef  FORMNO_SIKIZIKA_AUTUMN
#undef  FORMNO_SIKIZIKA_WINTER
#undef  FORMNO_SIKIZIKA_MAX

//メブキジカ
#undef  FORMNO_MEBUKIZIKA_SPRING
#undef  FORMNO_MEBUKIZIKA_SUMMER
#undef  FORMNO_MEBUKIZIKA_AUTUMN
#undef  FORMNO_MEBUKIZIKA_WINTER
#undef  FORMNO_MEBUKIZIKA_MAX

//トルネロス
#undef  FORMNO_TORUNEROSU_NORMAL
#undef  FORMNO_TORUNEROSU_AR
#undef  FORMNO_TORUNEROSU_MAX

//ボルトロス
#undef  FORMNO_BORUTOROSU_NORMAL
#undef  FORMNO_BORUTOROSU_AR
#undef  FORMNO_BORUTOROSU_MAX

//ランドロス
#undef  FORMNO_RANDOROSU_NORMAL
#undef  FORMNO_RANDOROSU_AR
#undef  FORMNO_RANDOROSU_MAX

//キュレム
#undef  FORMNO_KYUREMU_A
#undef  FORMNO_KYUREMU_WHITE
#undef  FORMNO_KYUREMU_BLACK
#undef  FORMNO_KYUREMU_MAX

//ケルディオ
#undef  FORMNO_KERUDHIO_NORMAL
#undef  FORMNO_KERUDHIO_SWORD
#undef  FORMNO_KERUDHIO_MAX

//メロエッタ
#undef  FORMNO_MEROETTA_VOICE
#undef  FORMNO_MEROETTA_STEP
#undef  FORMNO_MEROETTA_MAX

//ゲノセクト
#undef  FORMNO_GENOSEKUTO_NORMAL
#undef  FORMNO_GENOSEKUTO_AQUA
#undef  FORMNO_GENOSEKUTO_INAZUMA
#undef  FORMNO_GENOSEKUTO_BLAZE
#undef  FORMNO_GENOSEKUTO_FREEZE
#undef  FORMNO_GENOSEKUTO_MAX

//ゲッコウガ
#undef  FORMNO_GEKKOUGA_NORMAL
#undef  FORMNO_GEKKOUGA_GEKKOUGA2
#undef  FORMNO_GEKKOUGA_SATOSHI
#undef  FORMNO_GEKKOUGA_MAX

//ビビヨン
#undef  FORMNO_BIBIYON_AREA1
#undef  FORMNO_BIBIYON_AREA2
#undef  FORMNO_BIBIYON_AREA3
#undef  FORMNO_BIBIYON_AREA4
#undef  FORMNO_BIBIYON_AREA5
#undef  FORMNO_BIBIYON_AREA6
#undef  FORMNO_BIBIYON_AREA7
#undef  FORMNO_BIBIYON_AREA8
#undef  FORMNO_BIBIYON_AREA9
#undef  FORMNO_BIBIYON_AREA10
#undef  FORMNO_BIBIYON_AREA11
#undef  FORMNO_BIBIYON_AREA12
#undef  FORMNO_BIBIYON_AREA13
#undef  FORMNO_BIBIYON_AREA14
#undef  FORMNO_BIBIYON_AREA15
#undef  FORMNO_BIBIYON_AREA16
#undef  FORMNO_BIBIYON_AREA17
#undef  FORMNO_BIBIYON_AREA18
#undef  FORMNO_BIBIYON_AREA19
#undef  FORMNO_BIBIYON_AREA20
#undef  FORMNO_BIBIYON_MAX

//フラベベ
#undef  FORMNO_HURABEBE_RED
#undef  FORMNO_HURABEBE_YELLOW
#undef  FORMNO_HURABEBE_ORANGE
#undef  FORMNO_HURABEBE_BLUE
#undef  FORMNO_HURABEBE_WHITE
#undef  FORMNO_HURABEBE_MAX

//フラエッテ
#undef  FORMNO_HURAETTE_RED
#undef  FORMNO_HURAETTE_YELLOW
#undef  FORMNO_HURAETTE_ORANGE
#undef  FORMNO_HURAETTE_BLUE
#undef  FORMNO_HURAETTE_WHITE
#undef  FORMNO_HURAETTE_HAKAI
#undef  FORMNO_HURAETTE_MAX

//フラージェス
#undef  FORMNO_HURAAJESU_RED
#undef  FORMNO_HURAAJESU_YELLOW
#undef  FORMNO_HURAAJESU_ORANGE
#undef  FORMNO_HURAAJESU_BLUE
#undef  FORMNO_HURAAJESU_WHITE
#undef  FORMNO_HURAAJESU_MAX

//トリミアン
#undef  FORMNO_TORIMIAN_NORMAL
#undef  FORMNO_TORIMIAN_HEART
#undef  FORMNO_TORIMIAN_STAR
#undef  FORMNO_TORIMIAN_DIAMOND
#undef  FORMNO_TORIMIAN_YOUNGLADY
#undef  FORMNO_TORIMIAN_LADY
#undef  FORMNO_TORIMIAN_GENTLEMAN
#undef  FORMNO_TORIMIAN_ANTOINETTE
#undef  FORMNO_TORIMIAN_RENJISHI
#undef  FORMNO_TORIMIAN_SPHINX
#undef  FORMNO_TORIMIAN_MAX

//ニャオニクス
#undef  FORMNO_NYAONIKUSU_MALE
#undef  FORMNO_NYAONIKUSU_FEMALE
#undef  FORMNO_NYAONIKUSU_MAX

//ギルガルド
#undef  FORMNO_GIRUGARUDO_TATE
#undef  FORMNO_GIRUGARUDO_HOKO
#undef  FORMNO_GIRUGARUDO_MAX

//バケッチャ
#undef  FORMNO_BAKETTYA_NORMAL
#undef  FORMNO_BAKETTYA_SMALL
#undef  FORMNO_BAKETTYA_BIG
#undef  FORMNO_BAKETTYA_KING
#undef  FORMNO_BAKETTYA_MAX

//パンプジン
#undef  FORMNO_PANPUZIN_NORMAL
#undef  FORMNO_PANPUZIN_SMALL
#undef  FORMNO_PANPUZIN_BIG
#undef  FORMNO_PANPUZIN_KING
#undef  FORMNO_PANPUZIN_MAX

//ゼルネアス
#undef  FORMNO_ZERUNEASU_NORMAL
#undef  FORMNO_ZERUNEASU_RADIATION
#undef  FORMNO_ZERUNEASU_MAX

//ジガルデ
#undef  FORMNO_ZIGARUDE_50PER
#undef  FORMNO_ZIGARUDE_10PER
#undef  FORMNO_ZIGARUDE_SW10PER
#undef  FORMNO_ZIGARUDE_SW50PER
#undef  FORMNO_ZIGARUDE_100PER
#undef  FORMNO_ZIGARUDE_MAX

//ディアンシー
#undef  FORMNO_DHIANSII_NORMAL
#undef  FORMNO_DHIANSII_MEGA
#undef  FORMNO_DHIANSII_MAX

//フーパ
#undef  FORMNO_HUUPA_NORMAL
#undef  FORMNO_HUUPA_EARNEST
#undef  FORMNO_HUUPA_MAX

//デカグース
#undef  FORMNO_MANGUUSU2_NORMAL
#undef  FORMNO_MANGUUSU2_NUSHI
#undef  FORMNO_MANGUUSU2_MAX

//クワガノン
#undef  FORMNO_KUWAGATA3_NORMAL
#undef  FORMNO_KUWAGATA3_NUSHI
#undef  FORMNO_KUWAGATA3_MAX

//オドリドリ
#undef  FORMNO_MITUSUI_FLAMENCO
#undef  FORMNO_MITUSUI_CHEER
#undef  FORMNO_MITUSUI_HULA
#undef  FORMNO_MITUSUI_NICHIBU
#undef  FORMNO_MITUSUI_MAX

//アブリボン
#undef  FORMNO_ABU2_NORMAL
#undef  FORMNO_ABU2_NUSHI
#undef  FORMNO_ABU2_MAX

//ルガルガン
#undef  FORMNO_OOKAMI2_MIDDAY
#undef  FORMNO_OOKAMI2_MIDNIGHT
#undef  FORMNO_OOKAMI2_MAX

//ヨワシ
#undef  FORMNO_YOWASI_NORMAL
#undef  FORMNO_YOWASI_GYOGUN_L
#undef  FORMNO_YOWASI_MAX

//オニシズクモ
#undef  FORMNO_MIZUGUMO2_NORMAL
#undef  FORMNO_MIZUGUMO2_NUSHI
#undef  FORMNO_MIZUGUMO2_MAX

//ラランテス
#undef  FORMNO_HANAKAMA2_NORMAL
#undef  FORMNO_HANAKAMA2_NUSHI
#undef  FORMNO_HANAKAMA2_MAX

//エンニュート
#undef  FORMNO_DOKUTOKAGE2_NORMAL
#undef  FORMNO_DOKUTOKAGE2_NUSHI
#undef  FORMNO_DOKUTOKAGE2_MAX

//シルヴァディ
#undef  FORMNO_GURIPUSU2_NORMAL
#undef  FORMNO_GURIPUSU2_BATTLE
#undef  FORMNO_GURIPUSU2_HIKOU
#undef  FORMNO_GURIPUSU2_POISON
#undef  FORMNO_GURIPUSU2_JIMEN
#undef  FORMNO_GURIPUSU2_IWA
#undef  FORMNO_GURIPUSU2_MUSHI
#undef  FORMNO_GURIPUSU2_GHOST
#undef  FORMNO_GURIPUSU2_METAL
#undef  FORMNO_GURIPUSU2_FIRE
#undef  FORMNO_GURIPUSU2_WATER
#undef  FORMNO_GURIPUSU2_KUSA
#undef  FORMNO_GURIPUSU2_ELECTRIC
#undef  FORMNO_GURIPUSU2_ESPER
#undef  FORMNO_GURIPUSU2_KOORI
#undef  FORMNO_GURIPUSU2_DRAGON
#undef  FORMNO_GURIPUSU2_AKU
#undef  FORMNO_GURIPUSU2_FAIRY
#undef  FORMNO_GURIPUSU2_MAX

//メテノ
#undef  FORMNO_NAGAREBOSI_M_RED
#undef  FORMNO_NAGAREBOSI_M_ORANGE
#undef  FORMNO_NAGAREBOSI_M_YELLOW
#undef  FORMNO_NAGAREBOSI_M_GREEN
#undef  FORMNO_NAGAREBOSI_M_BLUE
#undef  FORMNO_NAGAREBOSI_M_INDIGO
#undef  FORMNO_NAGAREBOSI_M_PURPLE
#undef  FORMNO_NAGAREBOSI_RED
#undef  FORMNO_NAGAREBOSI_ORANGE
#undef  FORMNO_NAGAREBOSI_YELLOW
#undef  FORMNO_NAGAREBOSI_GREEN
#undef  FORMNO_NAGAREBOSI_BLUE
#undef  FORMNO_NAGAREBOSI_INDIGO
#undef  FORMNO_NAGAREBOSI_PURPLE
#undef  FORMNO_NAGAREBOSI_MAX

//ミミッキュ
#undef  FORMNO_HORAA_NORMAL
#undef  FORMNO_HORAA_KUBIORE
#undef  FORMNO_HORAA_NORMAL_NUSHI
#undef  FORMNO_HORAA_KUBIORE_NUSHI
#undef  FORMNO_HORAA_MAX

//ジャラランガ
#undef  FORMNO_UROKO3_NORMAL
#undef  FORMNO_UROKO3_NUSHI
#undef  FORMNO_UROKO3_MAX

//ネクロズマ
#undef  FORMNO_PURIZUMU_NORMAL
#undef  FORMNO_PURIZUMU_FORM_S
#undef  FORMNO_PURIZUMU_FORM_L
#undef  FORMNO_PURIZUMU_FORM_N
#undef  FORMNO_PURIZUMU_MAX

//マギアナ
#undef  FORMNO_MABOROSI16_PRESENT
#undef  FORMNO_MABOROSI16_PAST
#undef  FORMNO_MABOROSI16_MAX

#undef  FORMNO_TAMAGO_NORMAL
#undef  FORMNO_TAMAGO_MANAFI
#undef  FORMNO_TAMAGO_MAX

#undef  OTHER_FORM_MAX

// １種族あたりのフォルム数の最大値
#undef  MAX_FORM_NUM




/*  break include-gurad */
#undef  __MONSNODEF_H__



#endif  /*  #if !defined(REDEFINE_MONSNO_DEF_H_INCLUDED)  */
