#if !defined(REDEFINE_ITEMSYM_H_INCLUDED)
#define REDEFINE_ITEMSYM_H_INCLUDED
#pragma once
//==============================================================================
/**
 * @file   redefine_itemsym.h
 * @date   2016/12/05 Mon. 12:49:11
 * @author muto_yu
 * @brief  
 * @par Copyright
 * (C)1995-2015 GAME FREAK inc. All Rights Reserved.
 */
//==============================================================================


#include  "./pokelib/itemsym.h"

#include  "./redefineMacro.h"



TO_ENUM(ITEM_DUMMY_DATA);
TO_ENUM(ITEM_MASUTAABOORU);
TO_ENUM(ITEM_HAIPAABOORU);
TO_ENUM(ITEM_SUUPAABOORU);
TO_ENUM(ITEM_MONSUTAABOORU);
TO_ENUM(ITEM_SAFARIBOORU);
TO_ENUM(ITEM_NETTOBOORU);
TO_ENUM(ITEM_DAIBUBOORU);
TO_ENUM(ITEM_NESUTOBOORU);
TO_ENUM(ITEM_RIPIITOBOORU);
TO_ENUM(ITEM_TAIMAABOORU);
TO_ENUM(ITEM_GOOZYASUBOORU);
TO_ENUM(ITEM_PUREMIABOORU);
TO_ENUM(ITEM_DAAKUBOORU);
TO_ENUM(ITEM_HIIRUBOORU);
TO_ENUM(ITEM_KUIKKUBOORU);
TO_ENUM(ITEM_PURESYASUBOORU);
TO_ENUM(ITEM_KIZUGUSURI);
TO_ENUM(ITEM_DOKUKESI);
TO_ENUM(ITEM_YAKEDONAOSI);
TO_ENUM(ITEM_KOORINAOSI);
TO_ENUM(ITEM_NEMUKEZAMASI);
TO_ENUM(ITEM_MAHINAOSI);
TO_ENUM(ITEM_KAIHUKUNOKUSURI);
TO_ENUM(ITEM_MANTANNOKUSURI);
TO_ENUM(ITEM_SUGOIKIZUGUSURI);
TO_ENUM(ITEM_IIKIZUGUSURI);
TO_ENUM(ITEM_NANDEMONAOSI);
TO_ENUM(ITEM_GENKINOKAKERA);
TO_ENUM(ITEM_GENKINOKATAMARI);
TO_ENUM(ITEM_OISIIMIZU);
TO_ENUM(ITEM_SAIKOSOODA);
TO_ENUM(ITEM_MIKKUSUORE);
TO_ENUM(ITEM_MOOMOOMIRUKU);
TO_ENUM(ITEM_TIKARANOKONA);
TO_ENUM(ITEM_TIKARANONEKKO);
TO_ENUM(ITEM_BANNOUGONA);
TO_ENUM(ITEM_HUKKATUSOU);
TO_ENUM(ITEM_PIIPIIEIDO);
TO_ENUM(ITEM_PIIPIIRIKABAA);
TO_ENUM(ITEM_PIIPIIEIDAA);
TO_ENUM(ITEM_PIIPIIMAKKUSU);
TO_ENUM(ITEM_HUENSENBEI);
TO_ENUM(ITEM_KINOMIZYUUSU);
TO_ENUM(ITEM_SEINARUHAI);
TO_ENUM(ITEM_MAKKUSUAPPU);
TO_ENUM(ITEM_TAURIN);
TO_ENUM(ITEM_BUROMUHEKISIN);
TO_ENUM(ITEM_INDOMETASIN);
TO_ENUM(ITEM_RIZOTIUMU);
TO_ENUM(ITEM_HUSIGINAAME);
TO_ENUM(ITEM_POINTOAPPU);
TO_ENUM(ITEM_KITOSAN);
TO_ENUM(ITEM_POINTOMAKKUSU);
TO_ENUM(ITEM_MORINOYOUKAN);
TO_ENUM(ITEM_EFEKUTOGAADO);
TO_ENUM(ITEM_KURITHIKATTO);
TO_ENUM(ITEM_PURASUPAWAA);
TO_ENUM(ITEM_DHIFENDAA);
TO_ENUM(ITEM_SUPIIDAA);
TO_ENUM(ITEM_YOKUATAARU);
TO_ENUM(ITEM_SUPESYARUAPPU);
TO_ENUM(ITEM_SUPESYARUGAADO);
TO_ENUM(ITEM_PIPPININGYOU);
TO_ENUM(ITEM_ENEKONOSIPPO);
TO_ENUM(ITEM_AOIBIIDORO);
TO_ENUM(ITEM_KIIROBIIDORO);
TO_ENUM(ITEM_AKAIBIIDORO);
TO_ENUM(ITEM_KUROIBIIDORO);
TO_ENUM(ITEM_SIROIBIIDORO);
TO_ENUM(ITEM_ASASENOSIO);
TO_ENUM(ITEM_ASASENOKAIGARA);
TO_ENUM(ITEM_AKAIKAKERA);
TO_ENUM(ITEM_AOIKAKERA);
TO_ENUM(ITEM_KIIROIKAKERA);
TO_ENUM(ITEM_MIDORINOKAKERA);
TO_ENUM(ITEM_SIRUBAASUPUREE);
TO_ENUM(ITEM_GOORUDOSUPUREE);
TO_ENUM(ITEM_ANANUKENOHIMO);
TO_ENUM(ITEM_MUSIYOKESUPUREE);
TO_ENUM(ITEM_TAIYOUNOISI);
TO_ENUM(ITEM_TUKINOISI);
TO_ENUM(ITEM_HONOONOISI);
TO_ENUM(ITEM_KAMINARINOISI);
TO_ENUM(ITEM_MIZUNOISI);
TO_ENUM(ITEM_RIIHUNOISI);
TO_ENUM(ITEM_TIISANAKINOKO);
TO_ENUM(ITEM_OOKINAKINOKO);
TO_ENUM(ITEM_SINZYU);
TO_ENUM(ITEM_OOKINASINZYU);
TO_ENUM(ITEM_HOSINOSUNA);
TO_ENUM(ITEM_HOSINOKAKERA);
TO_ENUM(ITEM_KINNOTAMA);
TO_ENUM(ITEM_HAATONOUROKO);
TO_ENUM(ITEM_AMAIMITU);
TO_ENUM(ITEM_SUKUSUKUKOYASI);
TO_ENUM(ITEM_ZIMEZIMEKOYASI);
TO_ENUM(ITEM_NAGANAGAKOYASI);
TO_ENUM(ITEM_NEBANEBAKOYASI);
TO_ENUM(ITEM_NEKKONOKASEKI);
TO_ENUM(ITEM_TUMENOKASEKI);
TO_ENUM(ITEM_KAINOKASEKI);
TO_ENUM(ITEM_KOURANOKASEKI);
TO_ENUM(ITEM_HIMITUNOKOHAKU);
TO_ENUM(ITEM_TATENOKASEKI);
TO_ENUM(ITEM_ZUGAINOKASEKI);
TO_ENUM(ITEM_KITYOUNAHONE);
TO_ENUM(ITEM_HIKARINOISI);
TO_ENUM(ITEM_YAMINOISI);
TO_ENUM(ITEM_MEZAMEISI);
TO_ENUM(ITEM_MANMARUISI);
TO_ENUM(ITEM_KANAMEISI);
TO_ENUM(ITEM_HAKKINDAMA);
TO_ENUM(ITEM_AKUAKASETTO);
TO_ENUM(ITEM_INAZUMAKASETTO);
TO_ENUM(ITEM_BUREIZUKASETTO);
TO_ENUM(ITEM_HURIIZUKASETTO);
TO_ENUM(ITEM_HAATOSUIITU);
TO_ENUM(ITEM_KONGOUDAMA);
TO_ENUM(ITEM_SIRATAMA);
TO_ENUM(ITEM_HAZIMETEMEERU);
TO_ENUM(ITEM_DAISUKIMEERU);
TO_ENUM(ITEM_OSASOIMEERU);
TO_ENUM(ITEM_KANSYAMEERU);
TO_ENUM(ITEM_SITUMONMEERU);
TO_ENUM(ITEM_OSUSUMEMEERU);
TO_ENUM(ITEM_OKAESIMEERU);
TO_ENUM(ITEM_BURIZZIMEERUs);
TO_ENUM(ITEM_BURIZZIMEERUh);
TO_ENUM(ITEM_BURIZZIMEERUc);
TO_ENUM(ITEM_BURIZZIMEERUv);
TO_ENUM(ITEM_BURIZZIMEERUw);
TO_ENUM(ITEM_KURABONOMI);
TO_ENUM(ITEM_KAGONOMI);
TO_ENUM(ITEM_MOMONNOMI);
TO_ENUM(ITEM_TIIGONOMI);
TO_ENUM(ITEM_NANASINOMI);
TO_ENUM(ITEM_HIMERINOMI);
TO_ENUM(ITEM_ORENNOMI);
TO_ENUM(ITEM_KIINOMI);
TO_ENUM(ITEM_RAMUNOMI);
TO_ENUM(ITEM_OBONNOMI);
TO_ENUM(ITEM_FIRANOMI);
TO_ENUM(ITEM_UINOMI);
TO_ENUM(ITEM_MAGONOMI);
TO_ENUM(ITEM_BANZINOMI);
TO_ENUM(ITEM_IANOMI);
TO_ENUM(ITEM_ZURINOMI);
TO_ENUM(ITEM_BURIINOMI);
TO_ENUM(ITEM_NANANOMI);
TO_ENUM(ITEM_SESINANOMI);
TO_ENUM(ITEM_PAIRUNOMI);
TO_ENUM(ITEM_ZAROKUNOMI);
TO_ENUM(ITEM_NEKOBUNOMI);
TO_ENUM(ITEM_TAPORUNOMI);
TO_ENUM(ITEM_ROMENOMI);
TO_ENUM(ITEM_UBUNOMI);
TO_ENUM(ITEM_MATOMANOMI);
TO_ENUM(ITEM_MOKOSINOMI);
TO_ENUM(ITEM_GOSUNOMI);
TO_ENUM(ITEM_RABUTANOMI);
TO_ENUM(ITEM_NOMERUNOMI);
TO_ENUM(ITEM_NOWAKINOMI);
TO_ENUM(ITEM_SIIYANOMI);
TO_ENUM(ITEM_KAISUNOMI);
TO_ENUM(ITEM_DORINOMI);
TO_ENUM(ITEM_BERIBUNOMI);
TO_ENUM(ITEM_OKKANOMI);
TO_ENUM(ITEM_ITOKENOMI);
TO_ENUM(ITEM_SOKUNONOMI);
TO_ENUM(ITEM_RINDONOMI);
TO_ENUM(ITEM_YATHENOMI);
TO_ENUM(ITEM_YOPUNOMI);
TO_ENUM(ITEM_BIAANOMI);
TO_ENUM(ITEM_SYUKANOMI);
TO_ENUM(ITEM_BAKOUNOMI);
TO_ENUM(ITEM_UTANNOMI);
TO_ENUM(ITEM_TANGANOMI);
TO_ENUM(ITEM_YOROGINOMI);
TO_ENUM(ITEM_KASIBUNOMI);
TO_ENUM(ITEM_HABANNOMI);
TO_ENUM(ITEM_NAMONOMI);
TO_ENUM(ITEM_RIRIBANOMI);
TO_ENUM(ITEM_HOZUNOMI);
TO_ENUM(ITEM_TIIRANOMI);
TO_ENUM(ITEM_RYUGANOMI);
TO_ENUM(ITEM_KAMURANOMI);
TO_ENUM(ITEM_YATAPINOMI);
TO_ENUM(ITEM_ZUANOMI);
TO_ENUM(ITEM_SANNOMI);
TO_ENUM(ITEM_SUTAANOMI);
TO_ENUM(ITEM_NAZONOMI);
TO_ENUM(ITEM_MIKURUNOMI);
TO_ENUM(ITEM_IBANNOMI);
TO_ENUM(ITEM_ZYAPONOMI);
TO_ENUM(ITEM_RENBUNOMI);
TO_ENUM(ITEM_HIKARINOKONA);
TO_ENUM(ITEM_SIROIHAABU);
TO_ENUM(ITEM_KYOUSEIGIPUSU);
TO_ENUM(ITEM_GAKUSYUUSOUTI);
TO_ENUM(ITEM_SENSEINOTUME);
TO_ENUM(ITEM_YASURAGINOSUZU);
TO_ENUM(ITEM_MENTARUHAABU);
TO_ENUM(ITEM_KODAWARIHATIMAKI);
TO_ENUM(ITEM_OUZYANOSIRUSI);
TO_ENUM(ITEM_GINNOKONA);
TO_ENUM(ITEM_OMAMORIKOBAN);
TO_ENUM(ITEM_KIYOMENOOHUDA);
TO_ENUM(ITEM_KOKORONOSIZUKU);
TO_ENUM(ITEM_SINKAINOKIBA);
TO_ENUM(ITEM_SINKAINOUROKO);
TO_ENUM(ITEM_KEMURIDAMA);
TO_ENUM(ITEM_KAWARAZUNOISI);
TO_ENUM(ITEM_KIAINOHATIMAKI);
TO_ENUM(ITEM_SIAWASETAMAGO);
TO_ENUM(ITEM_PINTORENZU);
TO_ENUM(ITEM_METARUKOOTO);
TO_ENUM(ITEM_TABENOKOSI);
TO_ENUM(ITEM_RYUUNOUROKO);
TO_ENUM(ITEM_DENKIDAMA);
TO_ENUM(ITEM_YAWARAKAISUNA);
TO_ENUM(ITEM_KATAIISI);
TO_ENUM(ITEM_KISEKINOTANE);
TO_ENUM(ITEM_KUROIMEGANE);
TO_ENUM(ITEM_KUROOBI);
TO_ENUM(ITEM_ZISYAKU);
TO_ENUM(ITEM_SINPINOSIZUKU);
TO_ENUM(ITEM_SURUDOIKUTIBASI);
TO_ENUM(ITEM_DOKUBARI);
TO_ENUM(ITEM_TOKENAIKOORI);
TO_ENUM(ITEM_NOROINOOHUDA);
TO_ENUM(ITEM_MAGATTASUPUUN);
TO_ENUM(ITEM_MOKUTAN);
TO_ENUM(ITEM_RYUUNOKIBA);
TO_ENUM(ITEM_SIRUKUNOSUKAAHU);
TO_ENUM(ITEM_APPUGUREEDO);
TO_ENUM(ITEM_KAIGARANOSUZU);
TO_ENUM(ITEM_USIONOOKOU);
TO_ENUM(ITEM_NONKINOOKOU);
TO_ENUM(ITEM_RAKKIIPANTI);
TO_ENUM(ITEM_METARUPAUDAA);
TO_ENUM(ITEM_HUTOIHONE);
TO_ENUM(ITEM_NAGANEGI);
TO_ENUM(ITEM_AKAIBANDANA);
TO_ENUM(ITEM_AOIBANDANA);
TO_ENUM(ITEM_PINKUNOBANDANA);
TO_ENUM(ITEM_MIDORINOBANDANA);
TO_ENUM(ITEM_KIIRONOBANDANA);
TO_ENUM(ITEM_KOUKAKURENZU);
TO_ENUM(ITEM_TIKARANOHATIMAKI);
TO_ENUM(ITEM_MONOSIRIMEGANE);
TO_ENUM(ITEM_TATUZINNOOBI);
TO_ENUM(ITEM_HIKARINONENDO);
TO_ENUM(ITEM_INOTINOTAMA);
TO_ENUM(ITEM_PAWAHURUHAABU);
TO_ENUM(ITEM_DOKUDOKUDAMA);
TO_ENUM(ITEM_KAENDAMA);
TO_ENUM(ITEM_SUPIIDOPAUDAA);
TO_ENUM(ITEM_KIAINOTASUKI);
TO_ENUM(ITEM_FOOKASURENZU);
TO_ENUM(ITEM_METORONOOMU);
TO_ENUM(ITEM_KUROITEKKYUU);
TO_ENUM(ITEM_KOUKOUNOSIPPO);
TO_ENUM(ITEM_AKAIITO);
TO_ENUM(ITEM_KUROIHEDORO);
TO_ENUM(ITEM_TUMETAIIWA);
TO_ENUM(ITEM_SARASARAIWA);
TO_ENUM(ITEM_ATUIIWA);
TO_ENUM(ITEM_SIMETTAIWA);
TO_ENUM(ITEM_NEBARINOKAGIDUME);
TO_ENUM(ITEM_KODAWARISUKAAHU);
TO_ENUM(ITEM_KUTTUKIBARI);
TO_ENUM(ITEM_PAWAARISUTO);
TO_ENUM(ITEM_PAWAABERUTO);
TO_ENUM(ITEM_PAWAARENZU);
TO_ENUM(ITEM_PAWAABANDO);
TO_ENUM(ITEM_PAWAAANKURU);
TO_ENUM(ITEM_PAWAAUEITO);
TO_ENUM(ITEM_KIREINANUKEGARA);
TO_ENUM(ITEM_OOKINANEKKO);
TO_ENUM(ITEM_KODAWARIMEGANE);
TO_ENUM(ITEM_HINOTAMAPUREETO);
TO_ENUM(ITEM_SIZUKUPUREETO);
TO_ENUM(ITEM_IKAZUTIPUREETO);
TO_ENUM(ITEM_MIDORINOPUREETO);
TO_ENUM(ITEM_TURARANOPUREETO);
TO_ENUM(ITEM_KOBUSINOPUREETO);
TO_ENUM(ITEM_MOUDOKUPUREETO);
TO_ENUM(ITEM_DAITINOPUREETO);
TO_ENUM(ITEM_AOZORAPUREETO);
TO_ENUM(ITEM_HUSIGINOPUREETO);
TO_ENUM(ITEM_TAMAMUSIPUREETO);
TO_ENUM(ITEM_GANSEKIPUREETO);
TO_ENUM(ITEM_MONONOKEPUREETO);
TO_ENUM(ITEM_RYUUNOPUREETO);
TO_ENUM(ITEM_KOWAMOTEPUREETO);
TO_ENUM(ITEM_KOUTETUPUREETO);
TO_ENUM(ITEM_AYASIIOKOU);
TO_ENUM(ITEM_GANSEKIOKOU);
TO_ENUM(ITEM_MANPUKUOKOU);
TO_ENUM(ITEM_SAZANAMINOOKOU);
TO_ENUM(ITEM_OHANANOOKOU);
TO_ENUM(ITEM_KOUUNNOOKOU);
TO_ENUM(ITEM_KIYOMENOOKOU);
TO_ENUM(ITEM_PUROTEKUTAA);
TO_ENUM(ITEM_EREKIBUUSUTAA);
TO_ENUM(ITEM_MAGUMABUUSUTAA);
TO_ENUM(ITEM_AYASIIPATTI);
TO_ENUM(ITEM_REIKAINONUNO);
TO_ENUM(ITEM_SURUDOITUME);
TO_ENUM(ITEM_SURUDOIKIBA);
TO_ENUM(ITEM_WAZAMASIN01);
TO_ENUM(ITEM_WAZAMASIN02);
TO_ENUM(ITEM_WAZAMASIN03);
TO_ENUM(ITEM_WAZAMASIN04);
TO_ENUM(ITEM_WAZAMASIN05);
TO_ENUM(ITEM_WAZAMASIN06);
TO_ENUM(ITEM_WAZAMASIN07);
TO_ENUM(ITEM_WAZAMASIN08);
TO_ENUM(ITEM_WAZAMASIN09);
TO_ENUM(ITEM_WAZAMASIN10);
TO_ENUM(ITEM_WAZAMASIN11);
TO_ENUM(ITEM_WAZAMASIN12);
TO_ENUM(ITEM_WAZAMASIN13);
TO_ENUM(ITEM_WAZAMASIN14);
TO_ENUM(ITEM_WAZAMASIN15);
TO_ENUM(ITEM_WAZAMASIN16);
TO_ENUM(ITEM_WAZAMASIN17);
TO_ENUM(ITEM_WAZAMASIN18);
TO_ENUM(ITEM_WAZAMASIN19);
TO_ENUM(ITEM_WAZAMASIN20);
TO_ENUM(ITEM_WAZAMASIN21);
TO_ENUM(ITEM_WAZAMASIN22);
TO_ENUM(ITEM_WAZAMASIN23);
TO_ENUM(ITEM_WAZAMASIN24);
TO_ENUM(ITEM_WAZAMASIN25);
TO_ENUM(ITEM_WAZAMASIN26);
TO_ENUM(ITEM_WAZAMASIN27);
TO_ENUM(ITEM_WAZAMASIN28);
TO_ENUM(ITEM_WAZAMASIN29);
TO_ENUM(ITEM_WAZAMASIN30);
TO_ENUM(ITEM_WAZAMASIN31);
TO_ENUM(ITEM_WAZAMASIN32);
TO_ENUM(ITEM_WAZAMASIN33);
TO_ENUM(ITEM_WAZAMASIN34);
TO_ENUM(ITEM_WAZAMASIN35);
TO_ENUM(ITEM_WAZAMASIN36);
TO_ENUM(ITEM_WAZAMASIN37);
TO_ENUM(ITEM_WAZAMASIN38);
TO_ENUM(ITEM_WAZAMASIN39);
TO_ENUM(ITEM_WAZAMASIN40);
TO_ENUM(ITEM_WAZAMASIN41);
TO_ENUM(ITEM_WAZAMASIN42);
TO_ENUM(ITEM_WAZAMASIN43);
TO_ENUM(ITEM_WAZAMASIN44);
TO_ENUM(ITEM_WAZAMASIN45);
TO_ENUM(ITEM_WAZAMASIN46);
TO_ENUM(ITEM_WAZAMASIN47);
TO_ENUM(ITEM_WAZAMASIN48);
TO_ENUM(ITEM_WAZAMASIN49);
TO_ENUM(ITEM_WAZAMASIN50);
TO_ENUM(ITEM_WAZAMASIN51);
TO_ENUM(ITEM_WAZAMASIN52);
TO_ENUM(ITEM_WAZAMASIN53);
TO_ENUM(ITEM_WAZAMASIN54);
TO_ENUM(ITEM_WAZAMASIN55);
TO_ENUM(ITEM_WAZAMASIN56);
TO_ENUM(ITEM_WAZAMASIN57);
TO_ENUM(ITEM_WAZAMASIN58);
TO_ENUM(ITEM_WAZAMASIN59);
TO_ENUM(ITEM_WAZAMASIN60);
TO_ENUM(ITEM_WAZAMASIN61);
TO_ENUM(ITEM_WAZAMASIN62);
TO_ENUM(ITEM_WAZAMASIN63);
TO_ENUM(ITEM_WAZAMASIN64);
TO_ENUM(ITEM_WAZAMASIN65);
TO_ENUM(ITEM_WAZAMASIN66);
TO_ENUM(ITEM_WAZAMASIN67);
TO_ENUM(ITEM_WAZAMASIN68);
TO_ENUM(ITEM_WAZAMASIN69);
TO_ENUM(ITEM_WAZAMASIN70);
TO_ENUM(ITEM_WAZAMASIN71);
TO_ENUM(ITEM_WAZAMASIN72);
TO_ENUM(ITEM_WAZAMASIN73);
TO_ENUM(ITEM_WAZAMASIN74);
TO_ENUM(ITEM_WAZAMASIN75);
TO_ENUM(ITEM_WAZAMASIN76);
TO_ENUM(ITEM_WAZAMASIN77);
TO_ENUM(ITEM_WAZAMASIN78);
TO_ENUM(ITEM_WAZAMASIN79);
TO_ENUM(ITEM_WAZAMASIN80);
TO_ENUM(ITEM_WAZAMASIN81);
TO_ENUM(ITEM_WAZAMASIN82);
TO_ENUM(ITEM_WAZAMASIN83);
TO_ENUM(ITEM_WAZAMASIN84);
TO_ENUM(ITEM_WAZAMASIN85);
TO_ENUM(ITEM_WAZAMASIN86);
TO_ENUM(ITEM_WAZAMASIN87);
TO_ENUM(ITEM_WAZAMASIN88);
TO_ENUM(ITEM_WAZAMASIN89);
TO_ENUM(ITEM_WAZAMASIN90);
TO_ENUM(ITEM_WAZAMASIN91);
TO_ENUM(ITEM_WAZAMASIN92);
TO_ENUM(ITEM_HIDENMASIN01);
TO_ENUM(ITEM_HIDENMASIN02);
TO_ENUM(ITEM_HIDENMASIN03);
TO_ENUM(ITEM_HIDENMASIN04);
TO_ENUM(ITEM_HIDENMASIN05);
TO_ENUM(ITEM_HIDENMASIN06);
TO_ENUM(ITEM_TANKENSETTO);
TO_ENUM(ITEM_TAKARABUKURO);
TO_ENUM(ITEM_RUURUBUKKU);
TO_ENUM(ITEM_POKETORE);
TO_ENUM(ITEM_POINTOKAADO);
TO_ENUM(ITEM_BOUKENNOOTO);
TO_ENUM(ITEM_SIIRUIRE);
TO_ENUM(ITEM_AKUSESARIIIRE);
TO_ENUM(ITEM_SIIRUBUKURO);
TO_ENUM(ITEM_TOMODATITETYOU);
TO_ENUM(ITEM_HATUDENSYOKII);
TO_ENUM(ITEM_KODAINOOMAMORI);
TO_ENUM(ITEM_GINGADANNOKAGI);
TO_ENUM(ITEM_AKAIKUSARI);
TO_ENUM(ITEM_TAUNMAPPU);
TO_ENUM(ITEM_BATORUSAATYAA);
TO_ENUM(ITEM_KOINKEESU);
TO_ENUM(ITEM_BORONOTURIZAO);
TO_ENUM(ITEM_IITURIZAO);
TO_ENUM(ITEM_SUGOITURIZAO);
TO_ENUM(ITEM_KODAKKUZYOURO);
TO_ENUM(ITEM_POFINKEESU);
TO_ENUM(ITEM_ZITENSYA);
TO_ENUM(ITEM_RUUMUKII);
TO_ENUM(ITEM_OOKIDONOTEGAMI);
TO_ENUM(ITEM_MIKADUKINOHANE);
TO_ENUM(ITEM_MENBAAZUKAADO);
TO_ENUM(ITEM_TENKAINOHUE);
TO_ENUM(ITEM_HUNENOTIKETTO);
TO_ENUM(ITEM_KONTESUTOPASU);
TO_ENUM(ITEM_KAZANNOOKIISI);
TO_ENUM(ITEM_OTODOKEMONO);
TO_ENUM(ITEM_HIKIKAEKEN1);
TO_ENUM(ITEM_HIKIKAEKEN2);
TO_ENUM(ITEM_HIKIKAEKEN3);
TO_ENUM(ITEM_SOUKONOKAGI);
TO_ENUM(ITEM_HIDENNOKUSURI);
TO_ENUM(ITEM_BATORUREKOODAA);
TO_ENUM(ITEM_GURASIDEANOHANA);
TO_ENUM(ITEM_HIMITUNOKAGI);
TO_ENUM(ITEM_BONGURIKEESU);
TO_ENUM(ITEM_ANNOONNOOTO);
TO_ENUM(ITEM_KINOMIPURANTAA);
TO_ENUM(ITEM_DAUZINGUMASIN);
TO_ENUM(ITEM_BURUUKAADO);
TO_ENUM(ITEM_OISIISIPPO);
TO_ENUM(ITEM_TOUMEINASUZU);
TO_ENUM(ITEM_KAADOKII);
TO_ENUM(ITEM_TIKANOKAGI);
TO_ENUM(ITEM_ZENIGAMEZYOURO);
TO_ENUM(ITEM_AKAIUROKO);
TO_ENUM(ITEM_OTOSIMONO);
TO_ENUM(ITEM_RINIAPASU);
TO_ENUM(ITEM_KIKAINOBUHIN);
TO_ENUM(ITEM_GINIRONOHANE);
TO_ENUM(ITEM_NIZIIRONOHANE);
TO_ENUM(ITEM_HUSIGINATAMAGO);
TO_ENUM(ITEM_AKABONGURI);
TO_ENUM(ITEM_AOBONGURI);
TO_ENUM(ITEM_KIBONGURI);
TO_ENUM(ITEM_MIDOBONGURI);
TO_ENUM(ITEM_MOMOBONGURI);
TO_ENUM(ITEM_SIROBONGURI);
TO_ENUM(ITEM_KUROBONGURI);
TO_ENUM(ITEM_SUPIIDOBOORU);
TO_ENUM(ITEM_REBERUBOORU);
TO_ENUM(ITEM_RUAABOORU);
TO_ENUM(ITEM_HEBIIBOORU);
TO_ENUM(ITEM_RABURABUBOORU);
TO_ENUM(ITEM_HURENDOBOORU);
TO_ENUM(ITEM_MUUNBOORU);
TO_ENUM(ITEM_KONPEBOORU);
TO_ENUM(ITEM_PAAKUBOORU);
TO_ENUM(ITEM_FOTOARUBAMU);
TO_ENUM(ITEM_gbPUREIYAA);
TO_ENUM(ITEM_UMINARINOSUZU);
TO_ENUM(ITEM_IKARIMANZYUU);
TO_ENUM(ITEM_DEETAKAADO01);
TO_ENUM(ITEM_DEETAKAADO02);
TO_ENUM(ITEM_DEETAKAADO03);
TO_ENUM(ITEM_DEETAKAADO04);
TO_ENUM(ITEM_DEETAKAADO05);
TO_ENUM(ITEM_DEETAKAADO06);
TO_ENUM(ITEM_DEETAKAADO07);
TO_ENUM(ITEM_DEETAKAADO08);
TO_ENUM(ITEM_DEETAKAADO09);
TO_ENUM(ITEM_DEETAKAADO10);
TO_ENUM(ITEM_DEETAKAADO11);
TO_ENUM(ITEM_DEETAKAADO12);
TO_ENUM(ITEM_DEETAKAADO13);
TO_ENUM(ITEM_DEETAKAADO14);
TO_ENUM(ITEM_DEETAKAADO15);
TO_ENUM(ITEM_DEETAKAADO16);
TO_ENUM(ITEM_DEETAKAADO17);
TO_ENUM(ITEM_DEETAKAADO18);
TO_ENUM(ITEM_DEETAKAADO19);
TO_ENUM(ITEM_DEETAKAADO20);
TO_ENUM(ITEM_DEETAKAADO21);
TO_ENUM(ITEM_DEETAKAADO22);
TO_ENUM(ITEM_DEETAKAADO23);
TO_ENUM(ITEM_DEETAKAADO24);
TO_ENUM(ITEM_DEETAKAADO25);
TO_ENUM(ITEM_DEETAKAADO26);
TO_ENUM(ITEM_DEETAKAADO27);
TO_ENUM(ITEM_MOEGIIRONOTAMA);
TO_ENUM(ITEM_ROKKUKAPUSERU);
TO_ENUM(ITEM_BENIIRONOTAMA);
TO_ENUM(ITEM_AIIRONOTAMA);
TO_ENUM(ITEM_NAZONOSUISYOU);
TO_ENUM(ITEM_KIREINAUROKO);
TO_ENUM(ITEM_SINKANOKISEKI);
TO_ENUM(ITEM_KARUISI);
TO_ENUM(ITEM_GOTUGOTUMETTO);
TO_ENUM(ITEM_HUUSEN);
TO_ENUM(ITEM_REDDOKAADO);
TO_ENUM(ITEM_NERAINOMATO);
TO_ENUM(ITEM_SIMETUKEBANDO);
TO_ENUM(ITEM_KYUUKON);
TO_ENUM(ITEM_ZYUUDENTI);
TO_ENUM(ITEM_DASSYUTUBOTAN);
TO_ENUM(ITEM_HONOONOZYUERU);
TO_ENUM(ITEM_MIZUNOZYUERU);
TO_ENUM(ITEM_DENKINOZYUERU);
TO_ENUM(ITEM_KUSANOZYUERU);
TO_ENUM(ITEM_KOORINOZYUERU);
TO_ENUM(ITEM_KAKUTOUZYUERU);
TO_ENUM(ITEM_DOKUNOZYUERU);
TO_ENUM(ITEM_ZIMENNOZYUERU);
TO_ENUM(ITEM_HIKOUNOZYUERU);
TO_ENUM(ITEM_ESUPAAZYUERU);
TO_ENUM(ITEM_MUSINOZYUERU);
TO_ENUM(ITEM_IWANOZYUERU);
TO_ENUM(ITEM_GOOSUTOZYUERU);
TO_ENUM(ITEM_DORAGONZYUERU);
TO_ENUM(ITEM_AKUNOZYUERU);
TO_ENUM(ITEM_HAGANENOZYUERU);
TO_ENUM(ITEM_NOOMARUZYUERU);
TO_ENUM(ITEM_TAIRYOKUNOHANE);
TO_ENUM(ITEM_KINRYOKUNOHANE);
TO_ENUM(ITEM_TEIKOUNOHANE);
TO_ENUM(ITEM_TIRYOKUNOHANE);
TO_ENUM(ITEM_SEISINNOHANE);
TO_ENUM(ITEM_SYUNPATUNOHANE);
TO_ENUM(ITEM_KIREINAHANE);
TO_ENUM(ITEM_HUTANOKASEKI);
TO_ENUM(ITEM_HANENOKASEKI);
TO_ENUM(ITEM_RIBATHITIKETTO);
TO_ENUM(ITEM_DERUDAMA);
TO_ENUM(ITEM_DORIIMUBOORU);
TO_ENUM(ITEM_POKEZYARASI);
TO_ENUM(ITEM_GUZZUKEESU);
TO_ENUM(ITEM_DORAGONNOHONE);
TO_ENUM(ITEM_KAORUKINOKO);
TO_ENUM(ITEM_DEKAIKINNOTAMA);
TO_ENUM(ITEM_ODANGOSINZYU);
TO_ENUM(ITEM_SUISEINOKAKERA);
TO_ENUM(ITEM_KODAINODOUKA);
TO_ENUM(ITEM_KODAINOGINKA);
TO_ENUM(ITEM_KODAINOKINKA);
TO_ENUM(ITEM_KODAINOTUBO);
TO_ENUM(ITEM_KODAINOUDEWA);
TO_ENUM(ITEM_KODAINOSEKIZOU);
TO_ENUM(ITEM_KODAINOOUKAN);
TO_ENUM(ITEM_HIUNAISU);
TO_ENUM(ITEM_KURITHIKATTO2);
TO_ENUM(ITEM_SUPIIDAA2);
TO_ENUM(ITEM_spAPPU2);
TO_ENUM(ITEM_spGAADO2);
TO_ENUM(ITEM_DHIFENDAA2);
TO_ENUM(ITEM_PURASUPAWAA2);
TO_ENUM(ITEM_YOKUATAARU2);
TO_ENUM(ITEM_SUPIIDAA3);
TO_ENUM(ITEM_spAPPU3);
TO_ENUM(ITEM_spGAADO3);
TO_ENUM(ITEM_DHIFENDAA3);
TO_ENUM(ITEM_PURASUPAWAA3);
TO_ENUM(ITEM_YOKUATAARU3);
TO_ENUM(ITEM_SUPIIDAA6);
TO_ENUM(ITEM_spAPPU6);
TO_ENUM(ITEM_spGAADO6);
TO_ENUM(ITEM_DHIFENDAA6);
TO_ENUM(ITEM_PURASUPAWAA6);
TO_ENUM(ITEM_YOKUATAARU6);
TO_ENUM(ITEM_SUKIRUKOORU);
TO_ENUM(ITEM_AITEMUDOROPPU);
TO_ENUM(ITEM_AITEMUKOORU);
TO_ENUM(ITEM_HURATTOKOORU);
TO_ENUM(ITEM_KURITHIKATTO3);
TO_ENUM(ITEM_RAITOSUTOON);
TO_ENUM(ITEM_DAAKUSUTOON);
TO_ENUM(ITEM_WAZAMASIN93);
TO_ENUM(ITEM_WAZAMASIN94);
TO_ENUM(ITEM_WAZAMASIN95);
TO_ENUM(ITEM_RAIBUKYASUTAA);
TO_ENUM(ITEM_GODDOSUTOON);
TO_ENUM(ITEM_HAITATUBUTU1);
TO_ENUM(ITEM_HAITATUBUTU2);
TO_ENUM(ITEM_HAITATUBUTU3);
TO_ENUM(ITEM_RAIBUKYASUTAA_1);
TO_ENUM(ITEM_MEDARUBOKKUSU);
TO_ENUM(ITEM_IDENSINOKUSABI);
TO_ENUM(ITEM_IDENSINOKUSABI_1);
TO_ENUM(ITEM_KYOKASYOU);
TO_ENUM(ITEM_MARUIOMAMORI);
TO_ENUM(ITEM_HIKARUOMAMORI);
TO_ENUM(ITEM_PURAZUMAKAADO);
TO_ENUM(ITEM_YOGORETAHANKATI);
TO_ENUM(ITEM_AKUROMAMASIIN);
TO_ENUM(ITEM_WASUREMONO);
TO_ENUM(ITEM_WASUREMONO_1);
TO_ENUM(ITEM_UTUSIKAGAMI);
TO_ENUM(ITEM_ZYAKUTENHOKEN);
TO_ENUM(ITEM_TOTUGEKITYOKKI);
TO_ENUM(ITEM_HOROKYASUTAA);
TO_ENUM(ITEM_HAKASENOTEGAMI);
TO_ENUM(ITEM_ROORAASUKEETO);
TO_ENUM(ITEM_SEIREIPUREETO);
TO_ENUM(ITEM_TOKUSEIKAPUSERU);
TO_ENUM(ITEM_HOIPPUPOPPU);
TO_ENUM(ITEM_NIOIBUKURO);
TO_ENUM(ITEM_HIKARIGOKE);
TO_ENUM(ITEM_YUKIDAMA);
TO_ENUM(ITEM_BOUZINGOOGURU);
TO_ENUM(ITEM_POKEMONNOHUE);
TO_ENUM(ITEM_TAWAWAKOYASI);
TO_ENUM(ITEM_BIKKURIKOYASI);
TO_ENUM(ITEM_GUNGUNKOYASI);
TO_ENUM(ITEM_TONDEMOKOYASI);
TO_ENUM(ITEM_GENGANAITO);
TO_ENUM(ITEM_SAANAITONAITO);
TO_ENUM(ITEM_DENRYUUNAITO);
TO_ENUM(ITEM_HUSIGIBANAITO);
TO_ENUM(ITEM_RIZAADONAITOx);
TO_ENUM(ITEM_KAMEKKUSUNAITO);
TO_ENUM(ITEM_MYUUTUNAITOx);
TO_ENUM(ITEM_MYUUTUNAITOy);
TO_ENUM(ITEM_BASYAAMONAITO);
TO_ENUM(ITEM_TYAAREMUNAITO);
TO_ENUM(ITEM_HERUGANAITO);
TO_ENUM(ITEM_BOSUGODORANAITO);
TO_ENUM(ITEM_ZYUPETTANAITO);
TO_ENUM(ITEM_BANGIRASUNAITO);
TO_ENUM(ITEM_HASSAMUNAITO);
TO_ENUM(ITEM_KAIROSUNAITO);
TO_ENUM(ITEM_PUTERANAITO);
TO_ENUM(ITEM_RUKARIONAITO);
TO_ENUM(ITEM_YUKINOONAITO);
TO_ENUM(ITEM_GARUURANAITO);
TO_ENUM(ITEM_GYARADOSUNAITO);
TO_ENUM(ITEM_ABUSORUNAITO);
TO_ENUM(ITEM_RIZAADONAITOy);
TO_ENUM(ITEM_HUUDHINAITO);
TO_ENUM(ITEM_HERAKUROSUNAITO);
TO_ENUM(ITEM_KUTIITONAITO);
TO_ENUM(ITEM_RAIBORUTONAITO);
TO_ENUM(ITEM_GABURIASUNAITO);
TO_ENUM(ITEM_RATHIASUNAITO);
TO_ENUM(ITEM_RATHIOSUNAITO);
TO_ENUM(ITEM_ROZERUNOMI);
TO_ENUM(ITEM_AKKINOMI);
TO_ENUM(ITEM_TARAPUNOMI);
TO_ENUM(ITEM_HASUBOOZYOURO);
TO_ENUM(ITEM_WAZAMASIN96);
TO_ENUM(ITEM_WAZAMASIN97);
TO_ENUM(ITEM_WAZAMASIN98);
TO_ENUM(ITEM_WAZAMASIN99);
TO_ENUM(ITEM_WAZAMASIN100);
TO_ENUM(ITEM_HATUDENSYOPASU);
TO_ENUM(ITEM_MEGARINGU);
TO_ENUM(ITEM_SUGOSOUNAISI);
TO_ENUM(ITEM_ARIHURETAISI);
TO_ENUM(ITEM_BAAGENTIKETTO);
TO_ENUM(ITEM_EREBEETANOKII);
TO_ENUM(ITEM_tmvPASU);
TO_ENUM(ITEM_KAROSUENBUREMU);
TO_ENUM(ITEM_TANKENKOKOROE);
TO_ENUM(ITEM_HUSIGINAOKIMONO);
TO_ENUM(ITEM_RENZUKEESU);
TO_ENUM(ITEM_KOSUMEPOOTI);
TO_ENUM(ITEM_ISYOUTORANKU);
TO_ENUM(ITEM_MIAREGARETTO);
TO_ENUM(ITEM_SYARASABURE);
TO_ENUM(ITEM_AGONOKASEKI);
TO_ENUM(ITEM_HIRENOKASEKI);
TO_ENUM(ITEM_HANSAMUTIKETTO);
TO_ENUM(ITEM_ZITENSYA_1);
TO_ENUM(ITEM_HOROKYASUTAA_1);
TO_ENUM(ITEM_YOUSEIZYUERU);
TO_ENUM(ITEM_MEGATYAAMU);
TO_ENUM(ITEM_MEGAGUROOBU);
TO_ENUM(ITEM_MAHHAZITENSYA);
TO_ENUM(ITEM_DAATOZITENSYA);
TO_ENUM(ITEM_HOERUKOZYOURO);
TO_ENUM(ITEM_DEBONNONIMOTU);
TO_ENUM(ITEM_HAIBUKURO);
TO_ENUM(ITEM_TIKANOKAGI_1);
TO_ENUM(ITEM_POROKKUKITTO);
TO_ENUM(ITEM_DAIGOHENOTEGAMI);
TO_ENUM(ITEM_MUGENNOTIKETTO);
TO_ENUM(ITEM_TANTIKI);
TO_ENUM(ITEM_GOOGOOGOOGURU);
TO_ENUM(ITEM_INSEKI);
TO_ENUM(ITEM_1GOUSITUNOKAGI);
TO_ENUM(ITEM_2GOUSITUNOKAGI);
TO_ENUM(ITEM_4GOUSITUNOKAGI);
TO_ENUM(ITEM_6GOUSITUNOKAGI);
TO_ENUM(ITEM_SOUKONOKAGI_1);
TO_ENUM(ITEM_DEBONSUKOOPU);
TO_ENUM(ITEM_HUNENOTIKETTO_1);
TO_ENUM(ITEM_HIDENMASIN07);
TO_ENUM(ITEM_DEBONBONBE);
TO_ENUM(ITEM_RAIBUSUUTU);
TO_ENUM(ITEM_RAIBUDORESU);
TO_ENUM(ITEM_MAGUMASUUTU);
TO_ENUM(ITEM_AKUASUUTU);
TO_ENUM(ITEM_PEATIKETTO);
TO_ENUM(ITEM_MEGABANGURU);
TO_ENUM(ITEM_MEGANEKKURESU);
TO_ENUM(ITEM_MEGAGURASU);
TO_ENUM(ITEM_MEGAANKAA);
TO_ENUM(ITEM_MEGARABERUPIN);
TO_ENUM(ITEM_MEGATHIARA);
TO_ENUM(ITEM_MEGAANKURETTO);
TO_ENUM(ITEM_INSEKI_1);
TO_ENUM(ITEM_RAGURAAZINAITO);
TO_ENUM(ITEM_ZYUKAINNAITO);
TO_ENUM(ITEM_YAMIRAMINAITO);
TO_ENUM(ITEM_TIRUTARISUNAITO);
TO_ENUM(ITEM_ERUREIDONAITO);
TO_ENUM(ITEM_TABUNNENAITO);
TO_ENUM(ITEM_METAGUROSUNAITO);
TO_ENUM(ITEM_SAMEHADANAITO);
TO_ENUM(ITEM_YADORANNAITO);
TO_ENUM(ITEM_HAGANEERUNAITO);
TO_ENUM(ITEM_PIZYOTTONAITO);
TO_ENUM(ITEM_ONIGOORINAITO);
TO_ENUM(ITEM_DHIANSINAITO);
TO_ENUM(ITEM_IMASIMENOTUBO);
TO_ENUM(ITEM_MEGABURESU);
TO_ENUM(ITEM_BAKUUDANAITO);
TO_ENUM(ITEM_MIMIROPPUNAITO);
TO_ENUM(ITEM_BOOMANDANAITO);
TO_ENUM(ITEM_SUPIANAITO);
TO_ENUM(ITEM_INSEKI_2);
TO_ENUM(ITEM_INSEKI_3);
TO_ENUM(ITEM_KIISUTOON);
TO_ENUM(ITEM_INSEKINOKAKERA);
TO_ENUM(ITEM_MUGENNOHUE);
TO_ENUM(ITEM_NOOMARUBIIZU_1);
TO_ENUM(ITEM_HONOOBIIZU_1);
TO_ENUM(ITEM_MIZUBIIZU_1);
TO_ENUM(ITEM_DENKIBIIZU_1);
TO_ENUM(ITEM_KUSABIIZU_1);
TO_ENUM(ITEM_KOORIBIIZU_1);
TO_ENUM(ITEM_KAKUTOUBIIZU_1);
TO_ENUM(ITEM_DOKUBIIZU_1);
TO_ENUM(ITEM_ZIMENBIIZU_1);
TO_ENUM(ITEM_HIKOUBIIZU_1);
TO_ENUM(ITEM_ESUPAABIIZU_1);
TO_ENUM(ITEM_MUSIBIIZU_1);
TO_ENUM(ITEM_IWABIIZU_1);
TO_ENUM(ITEM_GOOSUTOBIIZU_1);
TO_ENUM(ITEM_DORAGONBIIZU_1);
TO_ENUM(ITEM_AKUBIIZU_1);
TO_ENUM(ITEM_HAGANEBIIZU_1);
TO_ENUM(ITEM_FEARIIBIIZU_1);
TO_ENUM(ITEM_PIKATYUUBIIZU_1);
TO_ENUM(ITEM_GINNOOUKAN);
TO_ENUM(ITEM_KINNOOUKAN);
TO_ENUM(ITEM_ZENRYOKURINGU);
TO_ENUM(ITEM_HUKUROU3BIIZU_1);
TO_ENUM(ITEM_TORA3BIIZU_1);
TO_ENUM(ITEM_ASIKA3BIIZU_1);
TO_ENUM(ITEM_THIKIBIIZU_1);
TO_ENUM(ITEM_HAISINBIIZU_1);
TO_ENUM(ITEM_ARORAIBIIZU_1);
TO_ENUM(ITEM_KABIGONBIIZU_1);
TO_ENUM(ITEM_IIBUIBIIZU_1);
TO_ENUM(ITEM_MYUUBIIZU_1);
TO_ENUM(ITEM_NOOMARUBIIZU);
TO_ENUM(ITEM_HONOOBIIZU);
TO_ENUM(ITEM_MIZUBIIZU);
TO_ENUM(ITEM_DENKIBIIZU);
TO_ENUM(ITEM_KUSABIIZU);
TO_ENUM(ITEM_KOORIBIIZU);
TO_ENUM(ITEM_KAKUTOUBIIZU);
TO_ENUM(ITEM_DOKUBIIZU);
TO_ENUM(ITEM_ZIMENBIIZU);
TO_ENUM(ITEM_HIKOUBIIZU);
TO_ENUM(ITEM_ESUPAABIIZU);
TO_ENUM(ITEM_MUSIBIIZU);
TO_ENUM(ITEM_IWABIIZU);
TO_ENUM(ITEM_GOOSUTOBIIZU);
TO_ENUM(ITEM_DORAGONBIIZU);
TO_ENUM(ITEM_AKUBIIZU);
TO_ENUM(ITEM_HAGANEBIIZU);
TO_ENUM(ITEM_FEARIIBIIZU);
TO_ENUM(ITEM_PIKATYUUBIIZU);
TO_ENUM(ITEM_HUKUROU3BIIZU);
TO_ENUM(ITEM_TORA3BIIZU);
TO_ENUM(ITEM_ASIKA3BIIZU);
TO_ENUM(ITEM_THIKIBIIZU);
TO_ENUM(ITEM_HAISINBIIZU);
TO_ENUM(ITEM_ARORAIBIIZU);
TO_ENUM(ITEM_KABIGONBIIZU);
TO_ENUM(ITEM_IIBUIBIIZU);
TO_ENUM(ITEM_MYUUBIIZU);
TO_ENUM(ITEM_SATOPIKABIIZU);
TO_ENUM(ITEM_SATOPIKABIIZU_1);
TO_ENUM(ITEM_PURIANOHANA);
TO_ENUM(ITEM_BISUKASUNOHANA);
TO_ENUM(ITEM_BATOBARADANOHANA);
TO_ENUM(ITEM_KURAUNNOHANA);
TO_ENUM(ITEM_ZAIRYOUBUKURO);
TO_ENUM(ITEM_TURIZAO);
TO_ENUM(ITEM_HAKASENOHUKUMEN);
TO_ENUM(ITEM_FESUTIKETTO);
TO_ENUM(ITEM_KAGAYAKUISI);
TO_ENUM(ITEM_BIBIRIDAMA);
TO_ENUM(ITEM_ZIGARUDEKYUUBU);
TO_ENUM(ITEM_KANZENKYUUBU);
TO_ENUM(ITEM_KOORINOISI);
TO_ENUM(ITEM_RAIDOGIA);
TO_ENUM(ITEM_URUTORABOORU);
TO_ENUM(ITEM_OOKIIMARASADA);
TO_ENUM(ITEM_KURENAINOMITU);
TO_ENUM(ITEM_YAMABUKINOMITU);
TO_ENUM(ITEM_USUMOMONOMITU);
TO_ENUM(ITEM_MURASAKINOMITU);
TO_ENUM(ITEM_TAIYOUNOHUE);
TO_ENUM(ITEM_TUKINOHUE);
TO_ENUM(ITEM_KUKUINOTEGAMI);
TO_ENUM(ITEM_AYASIIKAADO);
TO_ENUM(ITEM_IBENTODAMII3);
TO_ENUM(ITEM_IBENTODAMII4);
TO_ENUM(ITEM_IBENTODAMII5);
TO_ENUM(ITEM_IBENTODAMII6);
TO_ENUM(ITEM_IBENTODAMII7);
TO_ENUM(ITEM_IBENTODAMII8);
TO_ENUM(ITEM_IBENTODAMII9);
TO_ENUM(ITEM_IBENTODAMII10);
TO_ENUM(ITEM_IBENTODAMII11);
TO_ENUM(ITEM_IBENTODAMII12);
TO_ENUM(ITEM_IBENTODAMII13);
TO_ENUM(ITEM_IBENTODAMII14);
TO_ENUM(ITEM_IBENTODAMII15);
TO_ENUM(ITEM_IBENTODAMII16);
TO_ENUM(ITEM_IBENTODAMII17);
TO_ENUM(ITEM_IBENTODAMII18);
TO_ENUM(ITEM_IBENTODAMII19);
TO_ENUM(ITEM_IBENTODAMII20);
TO_ENUM(ITEM_GURANDOKOOTO);
TO_ENUM(ITEM_BOUGOPATTO);
TO_ENUM(ITEM_EREKISIIDO);
TO_ENUM(ITEM_SAIKOSIIDO);
TO_ENUM(ITEM_MISUTOSIIDO);
TO_ENUM(ITEM_GURASUSIIDO);
TO_ENUM(ITEM_NOOMARUDAMII7);
TO_ENUM(ITEM_NOOMARUDAMII8);
TO_ENUM(ITEM_NOOMARUDAMII9);
TO_ENUM(ITEM_NOOMARUDAMII10);
TO_ENUM(ITEM_NOOMARUDAMII11);
TO_ENUM(ITEM_NOOMARUDAMII12);
TO_ENUM(ITEM_NOOMARUDAMII13);
TO_ENUM(ITEM_NOOMARUDAMII14);
TO_ENUM(ITEM_NOOMARUDAMII15);
TO_ENUM(ITEM_NOOMARUDAMII16);
TO_ENUM(ITEM_NOOMARUDAMII17);
TO_ENUM(ITEM_NOOMARUDAMII18);
TO_ENUM(ITEM_NOOMARUDAMII19);
TO_ENUM(ITEM_NOOMARUDAMII20);
TO_ENUM(ITEM_KAIHUKUDAMII1);
TO_ENUM(ITEM_KAIHUKUDAMII2);
TO_ENUM(ITEM_KAIHUKUDAMII3);
TO_ENUM(ITEM_KAIHUKUDAMII4);
TO_ENUM(ITEM_KAIHUKUDAMII5);
TO_ENUM(ITEM_FAITOMEMORI);
TO_ENUM(ITEM_HURAINGUMEMORI);
TO_ENUM(ITEM_POIZUNMEMORI);
TO_ENUM(ITEM_GURAUNDOMEMORI);
TO_ENUM(ITEM_ROKKUMEMORI);
TO_ENUM(ITEM_BAGUMEMORI);
TO_ENUM(ITEM_GOOSUTOMEMORI);
TO_ENUM(ITEM_SUTIIRUMEMORI);
TO_ENUM(ITEM_FAIYAAMEMORI);
TO_ENUM(ITEM_UOOTAAMEMORI);
TO_ENUM(ITEM_GURASUMEMORI);
TO_ENUM(ITEM_EREKUTOROMEMORI);
TO_ENUM(ITEM_SAIKIKKUMEMORI);
TO_ENUM(ITEM_AISUMEMORI);
TO_ENUM(ITEM_DORAGONMEMORI);
TO_ENUM(ITEM_DAAKUMEMORI);
TO_ENUM(ITEM_FEARIIMEMORI);
TO_ENUM(ITEM_SORUGAREOz_1);
TO_ENUM(ITEM_RUNAAARAz_1);
TO_ENUM(ITEM_NEKUROZUMAz_1);
TO_ENUM(ITEM_MIMIKKYUz_1);
TO_ENUM(ITEM_RUGARUGANz_1);
TO_ENUM(ITEM_ZYARARANGAz_1);
TO_ENUM(ITEM_SORUGAREOz);
TO_ENUM(ITEM_RUNAAARAz);
TO_ENUM(ITEM_NEKUROZUMAz);
TO_ENUM(ITEM_MIMIKKYUz);
TO_ENUM(ITEM_RUGARUGANz);
TO_ENUM(ITEM_ZYARARANGAz);
/*
r522
#define ITEM_IRIMANONOOMARUz		( 947 )		// イリマのノーマルＺ
#define ITEM_AZUKATTABOORU		( 948 )		// あずかったボール
*/
/*
r647
#define ITEM_TAMAGOHUKAPON		( 949 )		// タマゴふかポン
#define ITEM_YASUURIPON		( 950 )		// やすうりポン
#define ITEM_OKODUKAIPON		( 951 )		// おこづかいポン
#define ITEM_KEIKENTIPON		( 952 )		// けいけんちポン
#define ITEM_NATUKIPON		( 953 )		// なつきポン
#define ITEM_SOUGUUPON		( 954 )		// そうぐうポン
#define ITEM_ONMITUPON		( 955 )		// おんみつポン
#define ITEM_KAIHUKUPON		( 956 )		// かいふくポン
#define ITEM_PIIPIIPON		( 957 )		// ピーピーポン
#define ITEM_HOZYOPON		( 958 )		// ほじょポン
#define ITEM_TUKAMAEPON		( 959 )		// つかまえポン
*/
TO_ENUM(ITEM_DATA_MAX);


#undef  ITEM_DUMMY_DATA
#undef  ITEM_MASUTAABOORU
#undef  ITEM_HAIPAABOORU
#undef  ITEM_SUUPAABOORU
#undef  ITEM_MONSUTAABOORU
#undef  ITEM_SAFARIBOORU
#undef  ITEM_NETTOBOORU
#undef  ITEM_DAIBUBOORU
#undef  ITEM_NESUTOBOORU
#undef  ITEM_RIPIITOBOORU
#undef  ITEM_TAIMAABOORU
#undef  ITEM_GOOZYASUBOORU
#undef  ITEM_PUREMIABOORU
#undef  ITEM_DAAKUBOORU
#undef  ITEM_HIIRUBOORU
#undef  ITEM_KUIKKUBOORU
#undef  ITEM_PURESYASUBOORU
#undef  ITEM_KIZUGUSURI
#undef  ITEM_DOKUKESI
#undef  ITEM_YAKEDONAOSI
#undef  ITEM_KOORINAOSI
#undef  ITEM_NEMUKEZAMASI
#undef  ITEM_MAHINAOSI
#undef  ITEM_KAIHUKUNOKUSURI
#undef  ITEM_MANTANNOKUSURI
#undef  ITEM_SUGOIKIZUGUSURI
#undef  ITEM_IIKIZUGUSURI
#undef  ITEM_NANDEMONAOSI
#undef  ITEM_GENKINOKAKERA
#undef  ITEM_GENKINOKATAMARI
#undef  ITEM_OISIIMIZU
#undef  ITEM_SAIKOSOODA
#undef  ITEM_MIKKUSUORE
#undef  ITEM_MOOMOOMIRUKU
#undef  ITEM_TIKARANOKONA
#undef  ITEM_TIKARANONEKKO
#undef  ITEM_BANNOUGONA
#undef  ITEM_HUKKATUSOU
#undef  ITEM_PIIPIIEIDO
#undef  ITEM_PIIPIIRIKABAA
#undef  ITEM_PIIPIIEIDAA
#undef  ITEM_PIIPIIMAKKUSU
#undef  ITEM_HUENSENBEI
#undef  ITEM_KINOMIZYUUSU
#undef  ITEM_SEINARUHAI
#undef  ITEM_MAKKUSUAPPU
#undef  ITEM_TAURIN
#undef  ITEM_BUROMUHEKISIN
#undef  ITEM_INDOMETASIN
#undef  ITEM_RIZOTIUMU
#undef  ITEM_HUSIGINAAME
#undef  ITEM_POINTOAPPU
#undef  ITEM_KITOSAN
#undef  ITEM_POINTOMAKKUSU
#undef  ITEM_MORINOYOUKAN
#undef  ITEM_EFEKUTOGAADO
#undef  ITEM_KURITHIKATTO
#undef  ITEM_PURASUPAWAA
#undef  ITEM_DHIFENDAA
#undef  ITEM_SUPIIDAA
#undef  ITEM_YOKUATAARU
#undef  ITEM_SUPESYARUAPPU
#undef  ITEM_SUPESYARUGAADO
#undef  ITEM_PIPPININGYOU
#undef  ITEM_ENEKONOSIPPO
#undef  ITEM_AOIBIIDORO
#undef  ITEM_KIIROBIIDORO
#undef  ITEM_AKAIBIIDORO
#undef  ITEM_KUROIBIIDORO
#undef  ITEM_SIROIBIIDORO
#undef  ITEM_ASASENOSIO
#undef  ITEM_ASASENOKAIGARA
#undef  ITEM_AKAIKAKERA
#undef  ITEM_AOIKAKERA
#undef  ITEM_KIIROIKAKERA
#undef  ITEM_MIDORINOKAKERA
#undef  ITEM_SIRUBAASUPUREE
#undef  ITEM_GOORUDOSUPUREE
#undef  ITEM_ANANUKENOHIMO
#undef  ITEM_MUSIYOKESUPUREE
#undef  ITEM_TAIYOUNOISI
#undef  ITEM_TUKINOISI
#undef  ITEM_HONOONOISI
#undef  ITEM_KAMINARINOISI
#undef  ITEM_MIZUNOISI
#undef  ITEM_RIIHUNOISI
#undef  ITEM_TIISANAKINOKO
#undef  ITEM_OOKINAKINOKO
#undef  ITEM_SINZYU
#undef  ITEM_OOKINASINZYU
#undef  ITEM_HOSINOSUNA
#undef  ITEM_HOSINOKAKERA
#undef  ITEM_KINNOTAMA
#undef  ITEM_HAATONOUROKO
#undef  ITEM_AMAIMITU
#undef  ITEM_SUKUSUKUKOYASI
#undef  ITEM_ZIMEZIMEKOYASI
#undef  ITEM_NAGANAGAKOYASI
#undef  ITEM_NEBANEBAKOYASI
#undef  ITEM_NEKKONOKASEKI
#undef  ITEM_TUMENOKASEKI
#undef  ITEM_KAINOKASEKI
#undef  ITEM_KOURANOKASEKI
#undef  ITEM_HIMITUNOKOHAKU
#undef  ITEM_TATENOKASEKI
#undef  ITEM_ZUGAINOKASEKI
#undef  ITEM_KITYOUNAHONE
#undef  ITEM_HIKARINOISI
#undef  ITEM_YAMINOISI
#undef  ITEM_MEZAMEISI
#undef  ITEM_MANMARUISI
#undef  ITEM_KANAMEISI
#undef  ITEM_HAKKINDAMA
#undef  ITEM_AKUAKASETTO
#undef  ITEM_INAZUMAKASETTO
#undef  ITEM_BUREIZUKASETTO
#undef  ITEM_HURIIZUKASETTO
#undef  ITEM_HAATOSUIITU
#undef  ITEM_KONGOUDAMA
#undef  ITEM_SIRATAMA
#undef  ITEM_HAZIMETEMEERU
#undef  ITEM_DAISUKIMEERU
#undef  ITEM_OSASOIMEERU
#undef  ITEM_KANSYAMEERU
#undef  ITEM_SITUMONMEERU
#undef  ITEM_OSUSUMEMEERU
#undef  ITEM_OKAESIMEERU
#undef  ITEM_BURIZZIMEERUs
#undef  ITEM_BURIZZIMEERUh
#undef  ITEM_BURIZZIMEERUc
#undef  ITEM_BURIZZIMEERUv
#undef  ITEM_BURIZZIMEERUw
#undef  ITEM_KURABONOMI
#undef  ITEM_KAGONOMI
#undef  ITEM_MOMONNOMI
#undef  ITEM_TIIGONOMI
#undef  ITEM_NANASINOMI
#undef  ITEM_HIMERINOMI
#undef  ITEM_ORENNOMI
#undef  ITEM_KIINOMI
#undef  ITEM_RAMUNOMI
#undef  ITEM_OBONNOMI
#undef  ITEM_FIRANOMI
#undef  ITEM_UINOMI
#undef  ITEM_MAGONOMI
#undef  ITEM_BANZINOMI
#undef  ITEM_IANOMI
#undef  ITEM_ZURINOMI
#undef  ITEM_BURIINOMI
#undef  ITEM_NANANOMI
#undef  ITEM_SESINANOMI
#undef  ITEM_PAIRUNOMI
#undef  ITEM_ZAROKUNOMI
#undef  ITEM_NEKOBUNOMI
#undef  ITEM_TAPORUNOMI
#undef  ITEM_ROMENOMI
#undef  ITEM_UBUNOMI
#undef  ITEM_MATOMANOMI
#undef  ITEM_MOKOSINOMI
#undef  ITEM_GOSUNOMI
#undef  ITEM_RABUTANOMI
#undef  ITEM_NOMERUNOMI
#undef  ITEM_NOWAKINOMI
#undef  ITEM_SIIYANOMI
#undef  ITEM_KAISUNOMI
#undef  ITEM_DORINOMI
#undef  ITEM_BERIBUNOMI
#undef  ITEM_OKKANOMI
#undef  ITEM_ITOKENOMI
#undef  ITEM_SOKUNONOMI
#undef  ITEM_RINDONOMI
#undef  ITEM_YATHENOMI
#undef  ITEM_YOPUNOMI
#undef  ITEM_BIAANOMI
#undef  ITEM_SYUKANOMI
#undef  ITEM_BAKOUNOMI
#undef  ITEM_UTANNOMI
#undef  ITEM_TANGANOMI
#undef  ITEM_YOROGINOMI
#undef  ITEM_KASIBUNOMI
#undef  ITEM_HABANNOMI
#undef  ITEM_NAMONOMI
#undef  ITEM_RIRIBANOMI
#undef  ITEM_HOZUNOMI
#undef  ITEM_TIIRANOMI
#undef  ITEM_RYUGANOMI
#undef  ITEM_KAMURANOMI
#undef  ITEM_YATAPINOMI
#undef  ITEM_ZUANOMI
#undef  ITEM_SANNOMI
#undef  ITEM_SUTAANOMI
#undef  ITEM_NAZONOMI
#undef  ITEM_MIKURUNOMI
#undef  ITEM_IBANNOMI
#undef  ITEM_ZYAPONOMI
#undef  ITEM_RENBUNOMI
#undef  ITEM_HIKARINOKONA
#undef  ITEM_SIROIHAABU
#undef  ITEM_KYOUSEIGIPUSU
#undef  ITEM_GAKUSYUUSOUTI
#undef  ITEM_SENSEINOTUME
#undef  ITEM_YASURAGINOSUZU
#undef  ITEM_MENTARUHAABU
#undef  ITEM_KODAWARIHATIMAKI
#undef  ITEM_OUZYANOSIRUSI
#undef  ITEM_GINNOKONA
#undef  ITEM_OMAMORIKOBAN
#undef  ITEM_KIYOMENOOHUDA
#undef  ITEM_KOKORONOSIZUKU
#undef  ITEM_SINKAINOKIBA
#undef  ITEM_SINKAINOUROKO
#undef  ITEM_KEMURIDAMA
#undef  ITEM_KAWARAZUNOISI
#undef  ITEM_KIAINOHATIMAKI
#undef  ITEM_SIAWASETAMAGO
#undef  ITEM_PINTORENZU
#undef  ITEM_METARUKOOTO
#undef  ITEM_TABENOKOSI
#undef  ITEM_RYUUNOUROKO
#undef  ITEM_DENKIDAMA
#undef  ITEM_YAWARAKAISUNA
#undef  ITEM_KATAIISI
#undef  ITEM_KISEKINOTANE
#undef  ITEM_KUROIMEGANE
#undef  ITEM_KUROOBI
#undef  ITEM_ZISYAKU
#undef  ITEM_SINPINOSIZUKU
#undef  ITEM_SURUDOIKUTIBASI
#undef  ITEM_DOKUBARI
#undef  ITEM_TOKENAIKOORI
#undef  ITEM_NOROINOOHUDA
#undef  ITEM_MAGATTASUPUUN
#undef  ITEM_MOKUTAN
#undef  ITEM_RYUUNOKIBA
#undef  ITEM_SIRUKUNOSUKAAHU
#undef  ITEM_APPUGUREEDO
#undef  ITEM_KAIGARANOSUZU
#undef  ITEM_USIONOOKOU
#undef  ITEM_NONKINOOKOU
#undef  ITEM_RAKKIIPANTI
#undef  ITEM_METARUPAUDAA
#undef  ITEM_HUTOIHONE
#undef  ITEM_NAGANEGI
#undef  ITEM_AKAIBANDANA
#undef  ITEM_AOIBANDANA
#undef  ITEM_PINKUNOBANDANA
#undef  ITEM_MIDORINOBANDANA
#undef  ITEM_KIIRONOBANDANA
#undef  ITEM_KOUKAKURENZU
#undef  ITEM_TIKARANOHATIMAKI
#undef  ITEM_MONOSIRIMEGANE
#undef  ITEM_TATUZINNOOBI
#undef  ITEM_HIKARINONENDO
#undef  ITEM_INOTINOTAMA
#undef  ITEM_PAWAHURUHAABU
#undef  ITEM_DOKUDOKUDAMA
#undef  ITEM_KAENDAMA
#undef  ITEM_SUPIIDOPAUDAA
#undef  ITEM_KIAINOTASUKI
#undef  ITEM_FOOKASURENZU
#undef  ITEM_METORONOOMU
#undef  ITEM_KUROITEKKYUU
#undef  ITEM_KOUKOUNOSIPPO
#undef  ITEM_AKAIITO
#undef  ITEM_KUROIHEDORO
#undef  ITEM_TUMETAIIWA
#undef  ITEM_SARASARAIWA
#undef  ITEM_ATUIIWA
#undef  ITEM_SIMETTAIWA
#undef  ITEM_NEBARINOKAGIDUME
#undef  ITEM_KODAWARISUKAAHU
#undef  ITEM_KUTTUKIBARI
#undef  ITEM_PAWAARISUTO
#undef  ITEM_PAWAABERUTO
#undef  ITEM_PAWAARENZU
#undef  ITEM_PAWAABANDO
#undef  ITEM_PAWAAANKURU
#undef  ITEM_PAWAAUEITO
#undef  ITEM_KIREINANUKEGARA
#undef  ITEM_OOKINANEKKO
#undef  ITEM_KODAWARIMEGANE
#undef  ITEM_HINOTAMAPUREETO
#undef  ITEM_SIZUKUPUREETO
#undef  ITEM_IKAZUTIPUREETO
#undef  ITEM_MIDORINOPUREETO
#undef  ITEM_TURARANOPUREETO
#undef  ITEM_KOBUSINOPUREETO
#undef  ITEM_MOUDOKUPUREETO
#undef  ITEM_DAITINOPUREETO
#undef  ITEM_AOZORAPUREETO
#undef  ITEM_HUSIGINOPUREETO
#undef  ITEM_TAMAMUSIPUREETO
#undef  ITEM_GANSEKIPUREETO
#undef  ITEM_MONONOKEPUREETO
#undef  ITEM_RYUUNOPUREETO
#undef  ITEM_KOWAMOTEPUREETO
#undef  ITEM_KOUTETUPUREETO
#undef  ITEM_AYASIIOKOU
#undef  ITEM_GANSEKIOKOU
#undef  ITEM_MANPUKUOKOU
#undef  ITEM_SAZANAMINOOKOU
#undef  ITEM_OHANANOOKOU
#undef  ITEM_KOUUNNOOKOU
#undef  ITEM_KIYOMENOOKOU
#undef  ITEM_PUROTEKUTAA
#undef  ITEM_EREKIBUUSUTAA
#undef  ITEM_MAGUMABUUSUTAA
#undef  ITEM_AYASIIPATTI
#undef  ITEM_REIKAINONUNO
#undef  ITEM_SURUDOITUME
#undef  ITEM_SURUDOIKIBA
#undef  ITEM_WAZAMASIN01
#undef  ITEM_WAZAMASIN02
#undef  ITEM_WAZAMASIN03
#undef  ITEM_WAZAMASIN04
#undef  ITEM_WAZAMASIN05
#undef  ITEM_WAZAMASIN06
#undef  ITEM_WAZAMASIN07
#undef  ITEM_WAZAMASIN08
#undef  ITEM_WAZAMASIN09
#undef  ITEM_WAZAMASIN10
#undef  ITEM_WAZAMASIN11
#undef  ITEM_WAZAMASIN12
#undef  ITEM_WAZAMASIN13
#undef  ITEM_WAZAMASIN14
#undef  ITEM_WAZAMASIN15
#undef  ITEM_WAZAMASIN16
#undef  ITEM_WAZAMASIN17
#undef  ITEM_WAZAMASIN18
#undef  ITEM_WAZAMASIN19
#undef  ITEM_WAZAMASIN20
#undef  ITEM_WAZAMASIN21
#undef  ITEM_WAZAMASIN22
#undef  ITEM_WAZAMASIN23
#undef  ITEM_WAZAMASIN24
#undef  ITEM_WAZAMASIN25
#undef  ITEM_WAZAMASIN26
#undef  ITEM_WAZAMASIN27
#undef  ITEM_WAZAMASIN28
#undef  ITEM_WAZAMASIN29
#undef  ITEM_WAZAMASIN30
#undef  ITEM_WAZAMASIN31
#undef  ITEM_WAZAMASIN32
#undef  ITEM_WAZAMASIN33
#undef  ITEM_WAZAMASIN34
#undef  ITEM_WAZAMASIN35
#undef  ITEM_WAZAMASIN36
#undef  ITEM_WAZAMASIN37
#undef  ITEM_WAZAMASIN38
#undef  ITEM_WAZAMASIN39
#undef  ITEM_WAZAMASIN40
#undef  ITEM_WAZAMASIN41
#undef  ITEM_WAZAMASIN42
#undef  ITEM_WAZAMASIN43
#undef  ITEM_WAZAMASIN44
#undef  ITEM_WAZAMASIN45
#undef  ITEM_WAZAMASIN46
#undef  ITEM_WAZAMASIN47
#undef  ITEM_WAZAMASIN48
#undef  ITEM_WAZAMASIN49
#undef  ITEM_WAZAMASIN50
#undef  ITEM_WAZAMASIN51
#undef  ITEM_WAZAMASIN52
#undef  ITEM_WAZAMASIN53
#undef  ITEM_WAZAMASIN54
#undef  ITEM_WAZAMASIN55
#undef  ITEM_WAZAMASIN56
#undef  ITEM_WAZAMASIN57
#undef  ITEM_WAZAMASIN58
#undef  ITEM_WAZAMASIN59
#undef  ITEM_WAZAMASIN60
#undef  ITEM_WAZAMASIN61
#undef  ITEM_WAZAMASIN62
#undef  ITEM_WAZAMASIN63
#undef  ITEM_WAZAMASIN64
#undef  ITEM_WAZAMASIN65
#undef  ITEM_WAZAMASIN66
#undef  ITEM_WAZAMASIN67
#undef  ITEM_WAZAMASIN68
#undef  ITEM_WAZAMASIN69
#undef  ITEM_WAZAMASIN70
#undef  ITEM_WAZAMASIN71
#undef  ITEM_WAZAMASIN72
#undef  ITEM_WAZAMASIN73
#undef  ITEM_WAZAMASIN74
#undef  ITEM_WAZAMASIN75
#undef  ITEM_WAZAMASIN76
#undef  ITEM_WAZAMASIN77
#undef  ITEM_WAZAMASIN78
#undef  ITEM_WAZAMASIN79
#undef  ITEM_WAZAMASIN80
#undef  ITEM_WAZAMASIN81
#undef  ITEM_WAZAMASIN82
#undef  ITEM_WAZAMASIN83
#undef  ITEM_WAZAMASIN84
#undef  ITEM_WAZAMASIN85
#undef  ITEM_WAZAMASIN86
#undef  ITEM_WAZAMASIN87
#undef  ITEM_WAZAMASIN88
#undef  ITEM_WAZAMASIN89
#undef  ITEM_WAZAMASIN90
#undef  ITEM_WAZAMASIN91
#undef  ITEM_WAZAMASIN92
#undef  ITEM_HIDENMASIN01
#undef  ITEM_HIDENMASIN02
#undef  ITEM_HIDENMASIN03
#undef  ITEM_HIDENMASIN04
#undef  ITEM_HIDENMASIN05
#undef  ITEM_HIDENMASIN06
#undef  ITEM_TANKENSETTO
#undef  ITEM_TAKARABUKURO
#undef  ITEM_RUURUBUKKU
#undef  ITEM_POKETORE
#undef  ITEM_POINTOKAADO
#undef  ITEM_BOUKENNOOTO
#undef  ITEM_SIIRUIRE
#undef  ITEM_AKUSESARIIIRE
#undef  ITEM_SIIRUBUKURO
#undef  ITEM_TOMODATITETYOU
#undef  ITEM_HATUDENSYOKII
#undef  ITEM_KODAINOOMAMORI
#undef  ITEM_GINGADANNOKAGI
#undef  ITEM_AKAIKUSARI
#undef  ITEM_TAUNMAPPU
#undef  ITEM_BATORUSAATYAA
#undef  ITEM_KOINKEESU
#undef  ITEM_BORONOTURIZAO
#undef  ITEM_IITURIZAO
#undef  ITEM_SUGOITURIZAO
#undef  ITEM_KODAKKUZYOURO
#undef  ITEM_POFINKEESU
#undef  ITEM_ZITENSYA
#undef  ITEM_RUUMUKII
#undef  ITEM_OOKIDONOTEGAMI
#undef  ITEM_MIKADUKINOHANE
#undef  ITEM_MENBAAZUKAADO
#undef  ITEM_TENKAINOHUE
#undef  ITEM_HUNENOTIKETTO
#undef  ITEM_KONTESUTOPASU
#undef  ITEM_KAZANNOOKIISI
#undef  ITEM_OTODOKEMONO
#undef  ITEM_HIKIKAEKEN1
#undef  ITEM_HIKIKAEKEN2
#undef  ITEM_HIKIKAEKEN3
#undef  ITEM_SOUKONOKAGI
#undef  ITEM_HIDENNOKUSURI
#undef  ITEM_BATORUREKOODAA
#undef  ITEM_GURASIDEANOHANA
#undef  ITEM_HIMITUNOKAGI
#undef  ITEM_BONGURIKEESU
#undef  ITEM_ANNOONNOOTO
#undef  ITEM_KINOMIPURANTAA
#undef  ITEM_DAUZINGUMASIN
#undef  ITEM_BURUUKAADO
#undef  ITEM_OISIISIPPO
#undef  ITEM_TOUMEINASUZU
#undef  ITEM_KAADOKII
#undef  ITEM_TIKANOKAGI
#undef  ITEM_ZENIGAMEZYOURO
#undef  ITEM_AKAIUROKO
#undef  ITEM_OTOSIMONO
#undef  ITEM_RINIAPASU
#undef  ITEM_KIKAINOBUHIN
#undef  ITEM_GINIRONOHANE
#undef  ITEM_NIZIIRONOHANE
#undef  ITEM_HUSIGINATAMAGO
#undef  ITEM_AKABONGURI
#undef  ITEM_AOBONGURI
#undef  ITEM_KIBONGURI
#undef  ITEM_MIDOBONGURI
#undef  ITEM_MOMOBONGURI
#undef  ITEM_SIROBONGURI
#undef  ITEM_KUROBONGURI
#undef  ITEM_SUPIIDOBOORU
#undef  ITEM_REBERUBOORU
#undef  ITEM_RUAABOORU
#undef  ITEM_HEBIIBOORU
#undef  ITEM_RABURABUBOORU
#undef  ITEM_HURENDOBOORU
#undef  ITEM_MUUNBOORU
#undef  ITEM_KONPEBOORU
#undef  ITEM_PAAKUBOORU
#undef  ITEM_FOTOARUBAMU
#undef  ITEM_gbPUREIYAA
#undef  ITEM_UMINARINOSUZU
#undef  ITEM_IKARIMANZYUU
#undef  ITEM_DEETAKAADO01
#undef  ITEM_DEETAKAADO02
#undef  ITEM_DEETAKAADO03
#undef  ITEM_DEETAKAADO04
#undef  ITEM_DEETAKAADO05
#undef  ITEM_DEETAKAADO06
#undef  ITEM_DEETAKAADO07
#undef  ITEM_DEETAKAADO08
#undef  ITEM_DEETAKAADO09
#undef  ITEM_DEETAKAADO10
#undef  ITEM_DEETAKAADO11
#undef  ITEM_DEETAKAADO12
#undef  ITEM_DEETAKAADO13
#undef  ITEM_DEETAKAADO14
#undef  ITEM_DEETAKAADO15
#undef  ITEM_DEETAKAADO16
#undef  ITEM_DEETAKAADO17
#undef  ITEM_DEETAKAADO18
#undef  ITEM_DEETAKAADO19
#undef  ITEM_DEETAKAADO20
#undef  ITEM_DEETAKAADO21
#undef  ITEM_DEETAKAADO22
#undef  ITEM_DEETAKAADO23
#undef  ITEM_DEETAKAADO24
#undef  ITEM_DEETAKAADO25
#undef  ITEM_DEETAKAADO26
#undef  ITEM_DEETAKAADO27
#undef  ITEM_MOEGIIRONOTAMA
#undef  ITEM_ROKKUKAPUSERU
#undef  ITEM_BENIIRONOTAMA
#undef  ITEM_AIIRONOTAMA
#undef  ITEM_NAZONOSUISYOU
#undef  ITEM_KIREINAUROKO
#undef  ITEM_SINKANOKISEKI
#undef  ITEM_KARUISI
#undef  ITEM_GOTUGOTUMETTO
#undef  ITEM_HUUSEN
#undef  ITEM_REDDOKAADO
#undef  ITEM_NERAINOMATO
#undef  ITEM_SIMETUKEBANDO
#undef  ITEM_KYUUKON
#undef  ITEM_ZYUUDENTI
#undef  ITEM_DASSYUTUBOTAN
#undef  ITEM_HONOONOZYUERU
#undef  ITEM_MIZUNOZYUERU
#undef  ITEM_DENKINOZYUERU
#undef  ITEM_KUSANOZYUERU
#undef  ITEM_KOORINOZYUERU
#undef  ITEM_KAKUTOUZYUERU
#undef  ITEM_DOKUNOZYUERU
#undef  ITEM_ZIMENNOZYUERU
#undef  ITEM_HIKOUNOZYUERU
#undef  ITEM_ESUPAAZYUERU
#undef  ITEM_MUSINOZYUERU
#undef  ITEM_IWANOZYUERU
#undef  ITEM_GOOSUTOZYUERU
#undef  ITEM_DORAGONZYUERU
#undef  ITEM_AKUNOZYUERU
#undef  ITEM_HAGANENOZYUERU
#undef  ITEM_NOOMARUZYUERU
#undef  ITEM_TAIRYOKUNOHANE
#undef  ITEM_KINRYOKUNOHANE
#undef  ITEM_TEIKOUNOHANE
#undef  ITEM_TIRYOKUNOHANE
#undef  ITEM_SEISINNOHANE
#undef  ITEM_SYUNPATUNOHANE
#undef  ITEM_KIREINAHANE
#undef  ITEM_HUTANOKASEKI
#undef  ITEM_HANENOKASEKI
#undef  ITEM_RIBATHITIKETTO
#undef  ITEM_DERUDAMA
#undef  ITEM_DORIIMUBOORU
#undef  ITEM_POKEZYARASI
#undef  ITEM_GUZZUKEESU
#undef  ITEM_DORAGONNOHONE
#undef  ITEM_KAORUKINOKO
#undef  ITEM_DEKAIKINNOTAMA
#undef  ITEM_ODANGOSINZYU
#undef  ITEM_SUISEINOKAKERA
#undef  ITEM_KODAINODOUKA
#undef  ITEM_KODAINOGINKA
#undef  ITEM_KODAINOKINKA
#undef  ITEM_KODAINOTUBO
#undef  ITEM_KODAINOUDEWA
#undef  ITEM_KODAINOSEKIZOU
#undef  ITEM_KODAINOOUKAN
#undef  ITEM_HIUNAISU
#undef  ITEM_KURITHIKATTO2
#undef  ITEM_SUPIIDAA2
#undef  ITEM_spAPPU2
#undef  ITEM_spGAADO2
#undef  ITEM_DHIFENDAA2
#undef  ITEM_PURASUPAWAA2
#undef  ITEM_YOKUATAARU2
#undef  ITEM_SUPIIDAA3
#undef  ITEM_spAPPU3
#undef  ITEM_spGAADO3
#undef  ITEM_DHIFENDAA3
#undef  ITEM_PURASUPAWAA3
#undef  ITEM_YOKUATAARU3
#undef  ITEM_SUPIIDAA6
#undef  ITEM_spAPPU6
#undef  ITEM_spGAADO6
#undef  ITEM_DHIFENDAA6
#undef  ITEM_PURASUPAWAA6
#undef  ITEM_YOKUATAARU6
#undef  ITEM_SUKIRUKOORU
#undef  ITEM_AITEMUDOROPPU
#undef  ITEM_AITEMUKOORU
#undef  ITEM_HURATTOKOORU
#undef  ITEM_KURITHIKATTO3
#undef  ITEM_RAITOSUTOON
#undef  ITEM_DAAKUSUTOON
#undef  ITEM_WAZAMASIN93
#undef  ITEM_WAZAMASIN94
#undef  ITEM_WAZAMASIN95
#undef  ITEM_RAIBUKYASUTAA
#undef  ITEM_GODDOSUTOON
#undef  ITEM_HAITATUBUTU1
#undef  ITEM_HAITATUBUTU2
#undef  ITEM_HAITATUBUTU3
#undef  ITEM_RAIBUKYASUTAA_1
#undef  ITEM_MEDARUBOKKUSU
#undef  ITEM_IDENSINOKUSABI
#undef  ITEM_IDENSINOKUSABI_1
#undef  ITEM_KYOKASYOU
#undef  ITEM_MARUIOMAMORI
#undef  ITEM_HIKARUOMAMORI
#undef  ITEM_PURAZUMAKAADO
#undef  ITEM_YOGORETAHANKATI
#undef  ITEM_AKUROMAMASIIN
#undef  ITEM_WASUREMONO
#undef  ITEM_WASUREMONO_1
#undef  ITEM_UTUSIKAGAMI
#undef  ITEM_ZYAKUTENHOKEN
#undef  ITEM_TOTUGEKITYOKKI
#undef  ITEM_HOROKYASUTAA
#undef  ITEM_HAKASENOTEGAMI
#undef  ITEM_ROORAASUKEETO
#undef  ITEM_SEIREIPUREETO
#undef  ITEM_TOKUSEIKAPUSERU
#undef  ITEM_HOIPPUPOPPU
#undef  ITEM_NIOIBUKURO
#undef  ITEM_HIKARIGOKE
#undef  ITEM_YUKIDAMA
#undef  ITEM_BOUZINGOOGURU
#undef  ITEM_POKEMONNOHUE
#undef  ITEM_TAWAWAKOYASI
#undef  ITEM_BIKKURIKOYASI
#undef  ITEM_GUNGUNKOYASI
#undef  ITEM_TONDEMOKOYASI
#undef  ITEM_GENGANAITO
#undef  ITEM_SAANAITONAITO
#undef  ITEM_DENRYUUNAITO
#undef  ITEM_HUSIGIBANAITO
#undef  ITEM_RIZAADONAITOx
#undef  ITEM_KAMEKKUSUNAITO
#undef  ITEM_MYUUTUNAITOx
#undef  ITEM_MYUUTUNAITOy
#undef  ITEM_BASYAAMONAITO
#undef  ITEM_TYAAREMUNAITO
#undef  ITEM_HERUGANAITO
#undef  ITEM_BOSUGODORANAITO
#undef  ITEM_ZYUPETTANAITO
#undef  ITEM_BANGIRASUNAITO
#undef  ITEM_HASSAMUNAITO
#undef  ITEM_KAIROSUNAITO
#undef  ITEM_PUTERANAITO
#undef  ITEM_RUKARIONAITO
#undef  ITEM_YUKINOONAITO
#undef  ITEM_GARUURANAITO
#undef  ITEM_GYARADOSUNAITO
#undef  ITEM_ABUSORUNAITO
#undef  ITEM_RIZAADONAITOy
#undef  ITEM_HUUDHINAITO
#undef  ITEM_HERAKUROSUNAITO
#undef  ITEM_KUTIITONAITO
#undef  ITEM_RAIBORUTONAITO
#undef  ITEM_GABURIASUNAITO
#undef  ITEM_RATHIASUNAITO
#undef  ITEM_RATHIOSUNAITO
#undef  ITEM_ROZERUNOMI
#undef  ITEM_AKKINOMI
#undef  ITEM_TARAPUNOMI
#undef  ITEM_HASUBOOZYOURO
#undef  ITEM_WAZAMASIN96
#undef  ITEM_WAZAMASIN97
#undef  ITEM_WAZAMASIN98
#undef  ITEM_WAZAMASIN99
#undef  ITEM_WAZAMASIN100
#undef  ITEM_HATUDENSYOPASU
#undef  ITEM_MEGARINGU
#undef  ITEM_SUGOSOUNAISI
#undef  ITEM_ARIHURETAISI
#undef  ITEM_BAAGENTIKETTO
#undef  ITEM_EREBEETANOKII
#undef  ITEM_tmvPASU
#undef  ITEM_KAROSUENBUREMU
#undef  ITEM_TANKENKOKOROE
#undef  ITEM_HUSIGINAOKIMONO
#undef  ITEM_RENZUKEESU
#undef  ITEM_KOSUMEPOOTI
#undef  ITEM_ISYOUTORANKU
#undef  ITEM_MIAREGARETTO
#undef  ITEM_SYARASABURE
#undef  ITEM_AGONOKASEKI
#undef  ITEM_HIRENOKASEKI
#undef  ITEM_HANSAMUTIKETTO
#undef  ITEM_ZITENSYA_1
#undef  ITEM_HOROKYASUTAA_1
#undef  ITEM_YOUSEIZYUERU
#undef  ITEM_MEGATYAAMU
#undef  ITEM_MEGAGUROOBU
#undef  ITEM_MAHHAZITENSYA
#undef  ITEM_DAATOZITENSYA
#undef  ITEM_HOERUKOZYOURO
#undef  ITEM_DEBONNONIMOTU
#undef  ITEM_HAIBUKURO
#undef  ITEM_TIKANOKAGI_1
#undef  ITEM_POROKKUKITTO
#undef  ITEM_DAIGOHENOTEGAMI
#undef  ITEM_MUGENNOTIKETTO
#undef  ITEM_TANTIKI
#undef  ITEM_GOOGOOGOOGURU
#undef  ITEM_INSEKI
#undef  ITEM_1GOUSITUNOKAGI
#undef  ITEM_2GOUSITUNOKAGI
#undef  ITEM_4GOUSITUNOKAGI
#undef  ITEM_6GOUSITUNOKAGI
#undef  ITEM_SOUKONOKAGI_1
#undef  ITEM_DEBONSUKOOPU
#undef  ITEM_HUNENOTIKETTO_1
#undef  ITEM_HIDENMASIN07
#undef  ITEM_DEBONBONBE
#undef  ITEM_RAIBUSUUTU
#undef  ITEM_RAIBUDORESU
#undef  ITEM_MAGUMASUUTU
#undef  ITEM_AKUASUUTU
#undef  ITEM_PEATIKETTO
#undef  ITEM_MEGABANGURU
#undef  ITEM_MEGANEKKURESU
#undef  ITEM_MEGAGURASU
#undef  ITEM_MEGAANKAA
#undef  ITEM_MEGARABERUPIN
#undef  ITEM_MEGATHIARA
#undef  ITEM_MEGAANKURETTO
#undef  ITEM_INSEKI_1
#undef  ITEM_RAGURAAZINAITO
#undef  ITEM_ZYUKAINNAITO
#undef  ITEM_YAMIRAMINAITO
#undef  ITEM_TIRUTARISUNAITO
#undef  ITEM_ERUREIDONAITO
#undef  ITEM_TABUNNENAITO
#undef  ITEM_METAGUROSUNAITO
#undef  ITEM_SAMEHADANAITO
#undef  ITEM_YADORANNAITO
#undef  ITEM_HAGANEERUNAITO
#undef  ITEM_PIZYOTTONAITO
#undef  ITEM_ONIGOORINAITO
#undef  ITEM_DHIANSINAITO
#undef  ITEM_IMASIMENOTUBO
#undef  ITEM_MEGABURESU
#undef  ITEM_BAKUUDANAITO
#undef  ITEM_MIMIROPPUNAITO
#undef  ITEM_BOOMANDANAITO
#undef  ITEM_SUPIANAITO
#undef  ITEM_INSEKI_2
#undef  ITEM_INSEKI_3
#undef  ITEM_KIISUTOON
#undef  ITEM_INSEKINOKAKERA
#undef  ITEM_MUGENNOHUE
#undef  ITEM_NOOMARUBIIZU_1
#undef  ITEM_HONOOBIIZU_1
#undef  ITEM_MIZUBIIZU_1
#undef  ITEM_DENKIBIIZU_1
#undef  ITEM_KUSABIIZU_1
#undef  ITEM_KOORIBIIZU_1
#undef  ITEM_KAKUTOUBIIZU_1
#undef  ITEM_DOKUBIIZU_1
#undef  ITEM_ZIMENBIIZU_1
#undef  ITEM_HIKOUBIIZU_1
#undef  ITEM_ESUPAABIIZU_1
#undef  ITEM_MUSIBIIZU_1
#undef  ITEM_IWABIIZU_1
#undef  ITEM_GOOSUTOBIIZU_1
#undef  ITEM_DORAGONBIIZU_1
#undef  ITEM_AKUBIIZU_1
#undef  ITEM_HAGANEBIIZU_1
#undef  ITEM_FEARIIBIIZU_1
#undef  ITEM_PIKATYUUBIIZU_1
#undef  ITEM_GINNOOUKAN
#undef  ITEM_KINNOOUKAN
#undef  ITEM_ZENRYOKURINGU
#undef  ITEM_HUKUROU3BIIZU_1
#undef  ITEM_TORA3BIIZU_1
#undef  ITEM_ASIKA3BIIZU_1
#undef  ITEM_THIKIBIIZU_1
#undef  ITEM_HAISINBIIZU_1
#undef  ITEM_ARORAIBIIZU_1
#undef  ITEM_KABIGONBIIZU_1
#undef  ITEM_IIBUIBIIZU_1
#undef  ITEM_MYUUBIIZU_1
#undef  ITEM_NOOMARUBIIZU
#undef  ITEM_HONOOBIIZU
#undef  ITEM_MIZUBIIZU
#undef  ITEM_DENKIBIIZU
#undef  ITEM_KUSABIIZU
#undef  ITEM_KOORIBIIZU
#undef  ITEM_KAKUTOUBIIZU
#undef  ITEM_DOKUBIIZU
#undef  ITEM_ZIMENBIIZU
#undef  ITEM_HIKOUBIIZU
#undef  ITEM_ESUPAABIIZU
#undef  ITEM_MUSIBIIZU
#undef  ITEM_IWABIIZU
#undef  ITEM_GOOSUTOBIIZU
#undef  ITEM_DORAGONBIIZU
#undef  ITEM_AKUBIIZU
#undef  ITEM_HAGANEBIIZU
#undef  ITEM_FEARIIBIIZU
#undef  ITEM_PIKATYUUBIIZU
#undef  ITEM_HUKUROU3BIIZU
#undef  ITEM_TORA3BIIZU
#undef  ITEM_ASIKA3BIIZU
#undef  ITEM_THIKIBIIZU
#undef  ITEM_HAISINBIIZU
#undef  ITEM_ARORAIBIIZU
#undef  ITEM_KABIGONBIIZU
#undef  ITEM_IIBUIBIIZU
#undef  ITEM_MYUUBIIZU
#undef  ITEM_SATOPIKABIIZU
#undef  ITEM_SATOPIKABIIZU_1
#undef  ITEM_PURIANOHANA
#undef  ITEM_BISUKASUNOHANA
#undef  ITEM_BATOBARADANOHANA
#undef  ITEM_KURAUNNOHANA
#undef  ITEM_ZAIRYOUBUKURO
#undef  ITEM_TURIZAO
#undef  ITEM_HAKASENOHUKUMEN
#undef  ITEM_FESUTIKETTO
#undef  ITEM_KAGAYAKUISI
#undef  ITEM_BIBIRIDAMA
#undef  ITEM_ZIGARUDEKYUUBU
#undef  ITEM_KANZENKYUUBU
#undef  ITEM_KOORINOISI
#undef  ITEM_RAIDOGIA
#undef  ITEM_URUTORABOORU
#undef  ITEM_OOKIIMARASADA
#undef  ITEM_KURENAINOMITU
#undef  ITEM_YAMABUKINOMITU
#undef  ITEM_USUMOMONOMITU
#undef  ITEM_MURASAKINOMITU
#undef  ITEM_TAIYOUNOHUE
#undef  ITEM_TUKINOHUE
#undef  ITEM_KUKUINOTEGAMI
#undef  ITEM_AYASIIKAADO
#undef  ITEM_IBENTODAMII3
#undef  ITEM_IBENTODAMII4
#undef  ITEM_IBENTODAMII5
#undef  ITEM_IBENTODAMII6
#undef  ITEM_IBENTODAMII7
#undef  ITEM_IBENTODAMII8
#undef  ITEM_IBENTODAMII9
#undef  ITEM_IBENTODAMII10
#undef  ITEM_IBENTODAMII11
#undef  ITEM_IBENTODAMII12
#undef  ITEM_IBENTODAMII13
#undef  ITEM_IBENTODAMII14
#undef  ITEM_IBENTODAMII15
#undef  ITEM_IBENTODAMII16
#undef  ITEM_IBENTODAMII17
#undef  ITEM_IBENTODAMII18
#undef  ITEM_IBENTODAMII19
#undef  ITEM_IBENTODAMII20
#undef  ITEM_GURANDOKOOTO
#undef  ITEM_BOUGOPATTO
#undef  ITEM_EREKISIIDO
#undef  ITEM_SAIKOSIIDO
#undef  ITEM_MISUTOSIIDO
#undef  ITEM_GURASUSIIDO
#undef  ITEM_NOOMARUDAMII7
#undef  ITEM_NOOMARUDAMII8
#undef  ITEM_NOOMARUDAMII9
#undef  ITEM_NOOMARUDAMII10
#undef  ITEM_NOOMARUDAMII11
#undef  ITEM_NOOMARUDAMII12
#undef  ITEM_NOOMARUDAMII13
#undef  ITEM_NOOMARUDAMII14
#undef  ITEM_NOOMARUDAMII15
#undef  ITEM_NOOMARUDAMII16
#undef  ITEM_NOOMARUDAMII17
#undef  ITEM_NOOMARUDAMII18
#undef  ITEM_NOOMARUDAMII19
#undef  ITEM_NOOMARUDAMII20
#undef  ITEM_KAIHUKUDAMII1
#undef  ITEM_KAIHUKUDAMII2
#undef  ITEM_KAIHUKUDAMII3
#undef  ITEM_KAIHUKUDAMII4
#undef  ITEM_KAIHUKUDAMII5
#undef  ITEM_FAITOMEMORI
#undef  ITEM_HURAINGUMEMORI
#undef  ITEM_POIZUNMEMORI
#undef  ITEM_GURAUNDOMEMORI
#undef  ITEM_ROKKUMEMORI
#undef  ITEM_BAGUMEMORI
#undef  ITEM_GOOSUTOMEMORI
#undef  ITEM_SUTIIRUMEMORI
#undef  ITEM_FAIYAAMEMORI
#undef  ITEM_UOOTAAMEMORI
#undef  ITEM_GURASUMEMORI
#undef  ITEM_EREKUTOROMEMORI
#undef  ITEM_SAIKIKKUMEMORI
#undef  ITEM_AISUMEMORI
#undef  ITEM_DORAGONMEMORI
#undef  ITEM_DAAKUMEMORI
#undef  ITEM_FEARIIMEMORI
#undef  ITEM_SORUGAREOz_1
#undef  ITEM_RUNAAARAz_1
#undef  ITEM_NEKUROZUMAz_1
#undef  ITEM_MIMIKKYUz_1
#undef  ITEM_RUGARUGANz_1
#undef  ITEM_ZYARARANGAz_1
#undef  ITEM_SORUGAREOz
#undef  ITEM_RUNAAARAz
#undef  ITEM_NEKUROZUMAz
#undef  ITEM_MIMIKKYUz
#undef  ITEM_RUGARUGANz
#undef  ITEM_ZYARARANGAz
#undef  ITEM_SORUGAREOz
#undef  ITEM_RUNAAARAz
#undef  ITEM_NEKUROZUMAz
#undef  ITEM_MIMIKKYUz
#undef  ITEM_RUGARUGANz
#undef  ITEM_ZYARARANGAz
#undef  ITEM_zPAWAARINGU
#undef  ITEM_MOMOIROHANABIRA
#undef  ITEM_DAIDAIHANABIRA
#undef  ITEM_AONOHANABIRA
#undef  ITEM_AKANOHANABIRA
#undef  ITEM_MIDORINOHANABIRA
#undef  ITEM_KIIRONOHANABIRA
#undef  ITEM_MURASAKIHANABIRA
#undef  ITEM_NIZIIRONOHANA
#undef  ITEM_SYOOGUNBAZZI
#undef  ITEM_SORUPURASU
#undef  ITEM_RUNAPURASU
#undef  ITEM_SORUPURASU_1
#undef  ITEM_RUNAPURASU_1
#undef  ITEM_IRIMANONOOMARUz
#undef  ITEM_AZUKATTABOORU
#undef  ITEM_TAMAGOHUKAPON
#undef  ITEM_YASUURIPON
#undef  ITEM_OKODUKAIPON
#undef  ITEM_KEIKENTIPON
#undef  ITEM_NATUKIPON
#undef  ITEM_SOUGUUPON
#undef  ITEM_ONMITUPON
#undef  ITEM_KAIHUKUPON
#undef  ITEM_PIIPIIPON
#undef  ITEM_HOZYOPON
#undef  ITEM_TUKAMAEPON

#undef  ITEM_DATA_MAX


/*  break include-gurad */
#undef  ITEMSYM_H_INCLUDED


#endif  /*  #if !defined(REDEFINE_ITEMSYM_H_INCLUDED)  */
