#if !defined(REDEFINE_MSG_PLACE_NAME_OUT_H_INCLUDED)
#define REDEFINE_MSG_PLACE_NAME_OUT_H_INCLUDED
#pragma once
//==============================================================================
/**
 * @file   redefine_msg_place_name_out.h
 * @date   2016/11/09 Wed. 15:39:05
 * @author muto_yu
 * @brief  
 * @par Copyright
 * (C)1995-2015 GAME FREAK inc. All Rights Reserved.
 */
//==============================================================================

#include  "./message/msg_place_name_out.h"

#include  "./redefineMacro.h"




TO_ENUM(MAPNAME_SUTEKINABASYO);
TO_ENUM(MAPNAME_TOOIBASYO_OUT);
TO_ENUM(MAPNAME_EIGA);
TO_ENUM(MAPNAME_EIGA16);
TO_ENUM(MAPNAME_EIGA17);
TO_ENUM(MAPNAME_EIGA18);
TO_ENUM(MAPNAME_EIGA19);
TO_ENUM(MAPNAME_EIGA20);
TO_ENUM(MAPNAME_EIGA21);
TO_ENUM(MAPNAME_POKEMONSENTAH);
TO_ENUM(MAPNAME_POKEMOANIME);
TO_ENUM(MAPNAME_PCTOKYO);
TO_ENUM(MAPNAME_PCOHSAKA);
TO_ENUM(MAPNAME_PCHUKUOKA);
TO_ENUM(MAPNAME_PCNAGOYA);
TO_ENUM(MAPNAME_PCSAPPORO);
TO_ENUM(MAPNAME_PCYOKOHAMA);
TO_ENUM(MAPNAME_PCTOHOKU);
TO_ENUM(MAPNAME_PCTOKYOBAY);
TO_ENUM(MAPNAME_PCHIROSHIMA);
TO_ENUM(MAPNAME_PCKYOTO);
TO_ENUM(MAPNAME_PCSKYTREETOWN);
TO_ENUM(MAPNAME_POKESTORE);
TO_ENUM(MAPNAME_WCS);
TO_ENUM(MAPNAME_WCS16);
TO_ENUM(MAPNAME_WCS17);
TO_ENUM(MAPNAME_WCS18);
TO_ENUM(MAPNAME_WCS19);
TO_ENUM(MAPNAME_WCS20);
TO_ENUM(MAPNAME_WCS21);
TO_ENUM(MAPNAME_WORLDS);
TO_ENUM(MAPNAME_WORLDS16);
TO_ENUM(MAPNAME_WORLDS17);
TO_ENUM(MAPNAME_WORLDS18);
TO_ENUM(MAPNAME_WORLDS19);
TO_ENUM(MAPNAME_WORLDS20);
TO_ENUM(MAPNAME_WORLDS21);
TO_ENUM(MAPNAME_VGE);
TO_ENUM(MAPNAME_VGE16);
TO_ENUM(MAPNAME_VGE17);
TO_ENUM(MAPNAME_VGE18);
TO_ENUM(MAPNAME_VGE19);
TO_ENUM(MAPNAME_VGE20);
TO_ENUM(MAPNAME_VGE21);
TO_ENUM(MAPNAME_POKEMONIBENTO);
TO_ENUM(MAPNAME_BATORUTAIKAI);
TO_ENUM(MAPNAME_GEHMUIBENTO);
TO_ENUM(MAPNAME_DAISUKIKURABU);
TO_ENUM(MAPNAME_POKEMONBANGUMI);
TO_ENUM(MAPNAME_KONSAHTO);
TO_ENUM(MAPNAME_ONRAINPUREZENTO);
TO_ENUM(MAPNAME_PGL);
TO_ENUM(MAPNAME_POKEMONIBENTO16);
TO_ENUM(MAPNAME_POKEMONIBENTO17);
TO_ENUM(MAPNAME_POKEMONIBENTO18);
TO_ENUM(MAPNAME_POKEMONIBENTO19);
TO_ENUM(MAPNAME_POKEMONIBENTO20);
TO_ENUM(MAPNAME_POKEMONIBENTO21);
TO_ENUM(MAPNAME_POKEMONFYESUTA);
TO_ENUM(MAPNAME_POKEMONFYESUTA16);
TO_ENUM(MAPNAME_POKEMONFYESUTA17);
TO_ENUM(MAPNAME_POKEMONFYESUTA18);
TO_ENUM(MAPNAME_POKEMONFYESUTA19);
TO_ENUM(MAPNAME_POKEMONFYESUTA20);
TO_ENUM(MAPNAME_POKEMONFYESUTA21);
TO_ENUM(MAPNAME_POKEPAHKU);
TO_ENUM(MAPNAME_POKEPAHKU16);
TO_ENUM(MAPNAME_POKEPAHKU17);
TO_ENUM(MAPNAME_POKEPAHKU18);
TO_ENUM(MAPNAME_POKEPAHKU19);
TO_ENUM(MAPNAME_POKEPAHKU20);
TO_ENUM(MAPNAME_POKEPAHKU21);
TO_ENUM(MAPNAME_IBENTOKAIZYOU);
TO_ENUM(MAPNAME_GEEMUFURIIKU);
TO_ENUM(MAPNAME_SUTAJIAMU);
TO_ENUM(MAPNAME_VGC);
TO_ENUM(MAPNAME_VGC16);
TO_ENUM(MAPNAME_VGC17);
TO_ENUM(MAPNAME_VGC18);
TO_ENUM(MAPNAME_VGC19);
TO_ENUM(MAPNAME_VGC20);
TO_ENUM(MAPNAME_VGC21);
TO_ENUM(MAPNAME_VC);
TO_ENUM(MAPNAME_PMGO);
TO_ENUM(MAPNAME_PMBANK);
TO_ENUM(MAPNAME_PMSHOP);
TO_ENUM(MAPNAME_TAIKENBAN);
TO_ENUM(MAPNAME_PMTRAINERCLUB);

TO_ENUM(msg_place_name_out_max);




#undef	MAPNAME_SUTEKINABASYO
#undef	MAPNAME_TOOIBASYO_OUT
#undef	MAPNAME_EIGA
#undef	MAPNAME_EIGA16
#undef	MAPNAME_EIGA17
#undef	MAPNAME_EIGA18
#undef	MAPNAME_EIGA19
#undef	MAPNAME_EIGA20
#undef	MAPNAME_EIGA21
#undef	MAPNAME_POKEMONSENTAH
#undef	MAPNAME_POKEMOANIME
#undef	MAPNAME_PCTOKYO
#undef	MAPNAME_PCOHSAKA
#undef	MAPNAME_PCHUKUOKA
#undef	MAPNAME_PCNAGOYA
#undef	MAPNAME_PCSAPPORO
#undef	MAPNAME_PCYOKOHAMA
#undef	MAPNAME_PCTOHOKU
#undef	MAPNAME_PCTOKYOBAY
#undef	MAPNAME_PCHIROSHIMA
#undef	MAPNAME_PCKYOTO
#undef	MAPNAME_PCSKYTREETOWN
#undef	MAPNAME_POKESTORE
#undef	MAPNAME_WCS
#undef	MAPNAME_WCS16
#undef	MAPNAME_WCS17
#undef	MAPNAME_WCS18
#undef	MAPNAME_WCS19
#undef	MAPNAME_WCS20
#undef	MAPNAME_WCS21
#undef	MAPNAME_WORLDS
#undef	MAPNAME_WORLDS16
#undef	MAPNAME_WORLDS17
#undef	MAPNAME_WORLDS18
#undef	MAPNAME_WORLDS19
#undef	MAPNAME_WORLDS20
#undef	MAPNAME_WORLDS21
#undef	MAPNAME_VGE
#undef	MAPNAME_VGE16
#undef	MAPNAME_VGE17
#undef	MAPNAME_VGE18
#undef	MAPNAME_VGE19
#undef	MAPNAME_VGE20
#undef	MAPNAME_VGE21
#undef	MAPNAME_POKEMONIBENTO
#undef	MAPNAME_BATORUTAIKAI
#undef	MAPNAME_GEHMUIBENTO
#undef	MAPNAME_DAISUKIKURABU
#undef	MAPNAME_POKEMONBANGUMI
#undef	MAPNAME_KONSAHTO
#undef	MAPNAME_ONRAINPUREZENTO
#undef	MAPNAME_PGL
#undef	MAPNAME_POKEMONIBENTO16
#undef	MAPNAME_POKEMONIBENTO17
#undef	MAPNAME_POKEMONIBENTO18
#undef	MAPNAME_POKEMONIBENTO19
#undef	MAPNAME_POKEMONIBENTO20
#undef	MAPNAME_POKEMONIBENTO21
#undef	MAPNAME_POKEMONFYESUTA
#undef	MAPNAME_POKEMONFYESUTA16
#undef	MAPNAME_POKEMONFYESUTA17
#undef	MAPNAME_POKEMONFYESUTA18
#undef	MAPNAME_POKEMONFYESUTA19
#undef	MAPNAME_POKEMONFYESUTA20
#undef	MAPNAME_POKEMONFYESUTA21
#undef	MAPNAME_POKEPAHKU
#undef	MAPNAME_POKEPAHKU16
#undef	MAPNAME_POKEPAHKU17
#undef	MAPNAME_POKEPAHKU18
#undef	MAPNAME_POKEPAHKU19
#undef	MAPNAME_POKEPAHKU20
#undef	MAPNAME_POKEPAHKU21
#undef	MAPNAME_IBENTOKAIZYOU
#undef	MAPNAME_GEEMUFURIIKU
#undef	MAPNAME_SUTAJIAMU
#undef	MAPNAME_VGC
#undef	MAPNAME_VGC16
#undef	MAPNAME_VGC17
#undef	MAPNAME_VGC18
#undef	MAPNAME_VGC19
#undef	MAPNAME_VGC20
#undef	MAPNAME_VGC21
#undef	MAPNAME_VC
#undef	MAPNAME_PMGO
#undef	MAPNAME_PMBANK
#undef	MAPNAME_PMSHOP
#undef	MAPNAME_TAIKENBAN
#undef	MAPNAME_PMTRAINERCLUB

#undef	msg_place_name_out_max





/*  break include-gurad */
#undef  __MSG_PLACE_NAME_OUT_H__


#endif  /*  #if !defined(REDEFINE_MSG_PLACE_NAME_OUT_H_INCLUDED)  */
