#if !defined(DRESSUP_ITEM_ID_HEROINE_SITU_H)
#define DRESSUP_ITEM_ID_HEROINE_SITU_H

#define DRESSUP_ITEM_ID_P2_SITU_RIDESEA01 0
#define DRESSUP_ITEM_ID_P2_SITU_RIDELS01 1
#define DRESSUP_ITEM_ID_P2_SITU_MMJ_RIDEDIVE01 2
#define DRESSUP_ITEM_ID_HEROINE_SITU_COUNT 3

#endif // #if !defined(DRESSUP_ITEM_ID_HEROINE_SITU_H)
