#if !defined(DRESSUP_ITEM_ID_HERO_FACE_H)
#define DRESSUP_ITEM_ID_HERO_FACE_H

#define DRESSUP_ITEM_ID_P1_FACE01 0
#define DRESSUP_ITEM_ID_HERO_FACE_COUNT 1

#endif // #if !defined(DRESSUP_ITEM_ID_HERO_FACE_H)
