#if !defined(DRESSUP_ITEM_ID_HEROINE_FACE_H)
#define DRESSUP_ITEM_ID_HEROINE_FACE_H

#define DRESSUP_ITEM_ID_P2_FACE01 0
#define DRESSUP_ITEM_ID_HEROINE_FACE_COUNT 1

#endif // #if !defined(DRESSUP_ITEM_ID_HEROINE_FACE_H)
