#if !defined(DRESSUP_ITEM_ID_HERO_ACCEYE_H)
#define DRESSUP_ITEM_ID_HERO_ACCEYE_H

#define DRESSUP_ITEM_ID_P1_ACCEYE_METAL01 0
#define DRESSUP_ITEM_ID_P1_ACCEYE_METAL02 1
#define DRESSUP_ITEM_ID_P1_ACCEYE_METAL03 2
#define DRESSUP_ITEM_ID_P1_ACCEYE_METAL04 3
#define DRESSUP_ITEM_ID_P1_ACCEYE_METAL05 4
#define DRESSUP_ITEM_ID_P1_ACCEYE_SUNGLASS01_YE 5
#define DRESSUP_ITEM_ID_P1_ACCEYE_SUNGLASS01_RD 6
#define DRESSUP_ITEM_ID_P1_ACCEYE_SUNGLASS01_BL 7
#define DRESSUP_ITEM_ID_P1_ACCEYE_SUNGLASS01_GR 8
#define DRESSUP_ITEM_ID_P1_ACCEYE_SUNGLASS01_WH 9
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_WH 10
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_BK 11
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_RD 12
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_YE 13
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_GR 14
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_BL 15
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_OR 16
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_NB 17
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_PP 18
#define DRESSUP_ITEM_ID_P1_ACCEYE_WELL01_PN 19
#define DRESSUP_ITEM_ID_P1_ACCEYE_MMJ_AGENT01 20
#define DRESSUP_ITEM_ID_HERO_ACCEYE_COUNT 21

#endif // #if !defined(DRESSUP_ITEM_ID_HERO_ACCEYE_H)
