/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 *
 * $Revision: 4097$
 * $Date: 2009-03-27$
 */

#ifndef SVNREH_H
#define SVNREV_H

#define SVN_REV		4097
#define SVN_REVSTR	"4097"
#define SVN_REVDATE	"2009-03-27"
#define SVN_REVSTAMP	20090327L
#define SVN_MODIFIED	0

#endif /* SVNREV_H */
