//==============================================================================
/**
 * @file		fade_bg_upper.h
 * @brief		gfl::grp::g2d::LytSys内の個々のresourceを指定する為の定義です。
 *
 * Output Converter GFL_LytSysDatConverter.rb
 *
 */
//==============================================================================
#if !defined(__FADE_BG_UPPER_H__) 
#define __FADE_BG_UPPER_H__ 

enum {
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_FADE_01_IN_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_FADE_01_OUT_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WB_IN_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WB_OUT_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WC_IN_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WC_OUT_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WR_IN_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WR_OUT_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WS_IN_HIDARI_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WS_IN_MIGI_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WS_IN_SHITA_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WS_IN_UE_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WS_OUT_HIDARI_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WS_OUT_MIGI_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WS_OUT_SHITA_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_WS_OUT_UE_BCLAN,
  LYTRES_FADE_BG_UPPER_FADE_BG_UPPER_BCLYT,
  LYTRES_FADE_BG_UPPER_DOOR_L_BCLIM,
  LYTRES_FADE_BG_UPPER_DOOR_R_BCLIM,
  LYTRES_FADE_BG_UPPER_MAP_FADE_DOT_BCLIM,
  LYTRES_FADE_BG_UPPER_MAP_FADE_MARU_BCLIM,
  LYTRES_FADE_BG_UPPER_MAP_FADE_MARU_2_BCLIM,
  LYTRES_FADE_BG_UPPER_MAP_FADE_MARU_BALL_BCLIM,
  LYTRES_FADE_BG_UPPER_END, // 終端
};
#endif // __FADE_BG_UPPER_H__ 

