//==============================================================================
/**
 * @file		msg_place_name_out.h
 * @brief		メッセージID参照用ヘッダファイル
 *
 * このファイルはコンバータにより自動生成されています
 */
//==============================================================================
#if !defined(__MSG_PLACE_NAME_OUT_H__)
#define __MSG_PLACE_NAME_OUT_H__

#define	MAPNAME_SUTEKINABASYO		(0)
#define	MAPNAME_TOOIBASYO_OUT		(1)
#define	MAPNAME_EIGA		(2)
#define	MAPNAME_EIGA16		(3)
#define	MAPNAME_EIGA17		(4)
#define	MAPNAME_EIGA18		(5)
#define	MAPNAME_EIGA19		(6)
#define	MAPNAME_EIGA20		(7)
#define	MAPNAME_EIGA21		(8)
#define	MAPNAME_POKEMONSENTAH		(9)
#define	MAPNAME_POKEMOANIME		(10)
#define	MAPNAME_PCTOKYO		(11)
#define	MAPNAME_PCOHSAKA		(12)
#define	MAPNAME_PCHUKUOKA		(13)
#define	MAPNAME_PCNAGOYA		(14)
#define	MAPNAME_PCSAPPORO		(15)
#define	MAPNAME_PCYOKOHAMA		(16)
#define	MAPNAME_PCTOHOKU		(17)
#define	MAPNAME_PCTOKYOBAY		(18)
#define	MAPNAME_PCHIROSHIMA		(19)
#define	MAPNAME_PCKYOTO		(20)
#define	MAPNAME_PCSKYTREETOWN		(21)
#define	MAPNAME_POKESTORE		(22)
#define	MAPNAME_WCS		(23)
#define	MAPNAME_WCS16		(24)
#define	MAPNAME_WCS17		(25)
#define	MAPNAME_WCS18		(26)
#define	MAPNAME_WCS19		(27)
#define	MAPNAME_WCS20		(28)
#define	MAPNAME_WCS21		(29)
#define	MAPNAME_WORLDS		(30)
#define	MAPNAME_WORLDS16		(31)
#define	MAPNAME_WORLDS17		(32)
#define	MAPNAME_WORLDS18		(33)
#define	MAPNAME_WORLDS19		(34)
#define	MAPNAME_WORLDS20		(35)
#define	MAPNAME_WORLDS21		(36)
#define	MAPNAME_VGE		(37)
#define	MAPNAME_VGE16		(38)
#define	MAPNAME_VGE17		(39)
#define	MAPNAME_VGE18		(40)
#define	MAPNAME_VGE19		(41)
#define	MAPNAME_VGE20		(42)
#define	MAPNAME_VGE21		(43)
#define	MAPNAME_POKEMONIBENTO		(44)
#define	MAPNAME_BATORUTAIKAI		(45)
#define	MAPNAME_GEHMUIBENTO		(46)
#define	MAPNAME_DAISUKIKURABU		(47)
#define	MAPNAME_POKEMONBANGUMI		(48)
#define	MAPNAME_KONSAHTO		(49)
#define	MAPNAME_ONRAINPUREZENTO		(50)
#define	MAPNAME_PGL		(51)
#define	MAPNAME_POKEMONIBENTO16		(52)
#define	MAPNAME_POKEMONIBENTO17		(53)
#define	MAPNAME_POKEMONIBENTO18		(54)
#define	MAPNAME_POKEMONIBENTO19		(55)
#define	MAPNAME_POKEMONIBENTO20		(56)
#define	MAPNAME_POKEMONIBENTO21		(57)
#define	MAPNAME_POKEMONFYESUTA		(58)
#define	MAPNAME_POKEMONFYESUTA16		(59)
#define	MAPNAME_POKEMONFYESUTA17		(60)
#define	MAPNAME_POKEMONFYESUTA18		(61)
#define	MAPNAME_POKEMONFYESUTA19		(62)
#define	MAPNAME_POKEMONFYESUTA20		(63)
#define	MAPNAME_POKEMONFYESUTA21		(64)
#define	MAPNAME_POKEPAHKU		(65)
#define	MAPNAME_POKEPAHKU16		(66)
#define	MAPNAME_POKEPAHKU17		(67)
#define	MAPNAME_POKEPAHKU18		(68)
#define	MAPNAME_POKEPAHKU19		(69)
#define	MAPNAME_POKEPAHKU20		(70)
#define	MAPNAME_POKEPAHKU21		(71)
#define	MAPNAME_IBENTOKAIZYOU		(72)
#define	MAPNAME_GEEMUFURIIKU		(73)
#define	MAPNAME_SUTAJIAMU		(74)
#define	MAPNAME_VGC		(75)
#define	MAPNAME_VGC16		(76)
#define	MAPNAME_VGC17		(77)
#define	MAPNAME_VGC18		(78)
#define	MAPNAME_VGC19		(79)
#define	MAPNAME_VGC20		(80)
#define	MAPNAME_VGC21		(81)
#define	MAPNAME_VC		(82)
#define	MAPNAME_PMGO		(83)
#define	MAPNAME_PMBANK		(84)
#define	MAPNAME_PMSHOP		(85)
#define	MAPNAME_TAIKENBAN		(86)
#define	MAPNAME_PMTRAINERCLUB		(87)

#define	msg_place_name_out_max		(88)

#endif
