#ifdef  GF_PLATFORM_CTR
// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler version 3.7.1.2001

#include <OnlineCore/src/DDLTypes/CGCoreExports.h>
#include <NetZ/NetZ.h>
#include <OnlineCore/src/Core/PseudoGlobalVariable.h>
#include "AutoMatchmakeDDF.h"
#include "NetZ/src/Core/DOCore/DOCoreDDF.h"
#include "NetZ/src/Core/HostMigration/HostMigrationExtDDF.h"
#include "OnlineCore/src/DDLTypes/OnlineCoreDDF.h"
USING_NAMESPACE_NEX
BEGIN_NAMESPACE_NEX

PseudoGlobalVariable<AutoMatchmakeDDLDeclarations> g_ddlAutoMatchmake;
namespace AutoMatchmake_DDF {
	static qByte s_byParseTree[] = {
		 205,101, 35, 18,  0,  0,  0,  0,  3,  0,  0,  0,  7,  0,  0,  0,  1,  0,  0,  7,209
		,  0,  0,  0,  3, 19,  0,  0,  0, 13, 65,117,116,111, 77, 97,116, 99,104,109, 97,107
		,101,  0,  0,  0, 13, 65,117,116,111, 77, 97,116, 99,104,109, 97,107,101,  0,  0,  0
		, 13, 65,117,116,111, 77, 97,116, 99,104,109, 97,107,101,  0,  0,  0,  0,  0,  0,  0
		, 13, 65,117,116,111, 77, 97,116, 99,104,109, 97,107,101,  0,  0,  0,  0, 18,  0,  0
		,  0, 17,113,108,105,115,116, 60,115,116, 97,116,105,111,110,117,114,108, 62,  0,  0
		,  0, 17,113,108,105,115,116, 60,115,116, 97,116,105,111,110,117,114,108, 62,  0,  0
		,  0,  0,  0,  0,  0,  0,  0,  0,  0,  5,113,108,105,115,116,  0,  0,  0,  1,  0,  0
		,  0, 10,115,116, 97,116,105,111,110,117,114,108, 18,  0,  0,  0, 15,113,118,101, 99
		,116,111,114, 60,117,105,110,116, 51, 50, 62,  0,  0,  0, 15,113,118,101, 99,116,111
		,114, 60,117,105,110,116, 51, 50, 62,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  7
		,113,118,101, 99,116,111,114,  0,  0,  0,  1,  0,  0,  0,  6,117,105,110,116, 51, 50
	};
}

void AutoMatchmakeDDLDeclarations::Register() {
	g_ddlAutoMatchmake.GetValue().RegisterIfRequired();
}

void AutoMatchmakeDDLDeclarations::Init() {
	//Skip Class HostMigrationNotifier
	//Skip Class IDGenerator
	//Skip Class PromotionReferee
	//Skip Class RootDO
	//Skip Class Session
	//Skip Class Station
	//Owner Class 0 Total Class 6
}

void AutoMatchmakeDDLDeclarations::RegisterParseTree() {
	DOCoreDDLDeclarations::RegisterParseTree();
	HostMigrationExtDDLDeclarations::RegisterParseTree();
	OnlineCoreDDLDeclarations::RegisterParseTree();
	OnlineCoreDDLDeclarations::RegisterParseTree();
	DynamicRunTimeInterface::RegisterParseTree(AutoMatchmake_DDF::s_byParseTree,252);
}


void InitDOClasses() {
	ProcessAuthentication::SetTitle(_T("AutoMatchmake"));
	DOCoreDDLDeclarations::Register();
	HostMigrationExtDDLDeclarations::Register();
	OnlineCoreDDLDeclarations::Register();
	AutoMatchmakeDDLDeclarations::Register();
}

END_NAMESPACE_NEX
#endif