#ifdef  GF_PLATFORM_CTR
// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler version 3.7.1.2001

#ifndef _Quazal_AutoMatchmakeDDF_H_
#define _Quazal_AutoMatchmakeDDF_H_
#if defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 5000000)
#pragma push
#pragma diag_suppress 228,381,550,1300,1301,2530
#endif // defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 5000000)


#include <OnlineCore/src/DDLTypes/CGCoreExports.h>
#include <NetZ/NetZ.h>

BEGIN_NAMESPACE_NEX


class AutoMatchmakeDDLDeclarations : public DDLDeclarations {
	public:
		static void Register();
		static void RegisterParseTree();
		virtual void Init();
};

void InitDOClasses();


END_NAMESPACE_NEX

#if defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 5000000)
#pragma pop
#endif // defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 5000000)
#endif // _Quazal_AutoMatchmakeDDF.h_H_
#endif
