// このファイルは tool/Binlinker/binlinder.rb から出力されています。
#ifndef __BLOOM_RESOURCE_PACK__
#define __BLOOM_RESOURCE_PACK__

enum {
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOMLUMINANCE_GFVSH,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOMLUMINANCE_GFFSH,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOMSCALE_GFVSH,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOMSCALE_GFFSH,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOMBLUR_GFVSH,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOMBLUR_GFFSH,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOMADD_GFVSH,
	BL_IDX_BLOOM_RESOURCE_PACK_BLOOMADD_GFFSH,
	BL_IDX_BLOOM_RESOURCE_PACK_MAX,
};



#endif // BLOOM_RESOURCE_PACK
