//==============================================================
/**
 * @file	monsno_def.h
 * @bfief	ポケモンNoのDefine定義ファイル
 * @author	PersonalConverter
 * @note personal_conv.rb から生成されました
*/
//==============================================================
#if !defined __MONSNODEF_H__
#define __MONSNODEF_H__

enum MonsNo {
  MONSNO_NULL					= 0,
  MONSNO_HUSIGIDANE		= 1,
  MONSNO_HUSIGISOU		= 2,
  MONSNO_HUSIGIBANA		= 3,
  MONSNO_HITOKAGE			= 4,
  MONSNO_RIZAADO			= 5,
  MONSNO_RIZAADON			= 6,
  MONSNO_ZENIGAME			= 7,
  MONSNO_KAMEERU			= 8,
  MONSNO_KAMEKKUSU		= 9,
  MONSNO_KYATAPII			= 10,
  MONSNO_TORANSERU		= 11,
  MONSNO_BATAHURII		= 12,
  MONSNO_BIIDORU			= 13,
  MONSNO_KOKUUN				= 14,
  MONSNO_SUPIAA				= 15,
  MONSNO_POPPO				= 16,
  MONSNO_PIZYON				= 17,
  MONSNO_PIZYOTTO			= 18,
  MONSNO_KORATTA			= 19,
  MONSNO_RATTA				= 20,
  MONSNO_ONISUZUME		= 21,
  MONSNO_ONIDORIRU		= 22,
  MONSNO_AABO					= 23,
  MONSNO_AABOKKU			= 24,
  MONSNO_PIKATYUU			= 25,
  MONSNO_RAITYUU			= 26,
  MONSNO_SANDO				= 27,
  MONSNO_SANDOPAN			= 28,
  MONSNO_NIDORAN_F		= 29,
  MONSNO_NIDORIINA		= 30,
  MONSNO_NIDOKUIN			= 31,
  MONSNO_NIDORAN_M		= 32,
  MONSNO_NIDORIINO		= 33,
  MONSNO_NIDOKINGU		= 34,
  MONSNO_PIPPI				= 35,
  MONSNO_PIKUSII			= 36,
  MONSNO_ROKON				= 37,
  MONSNO_KYUUKON			= 38,
  MONSNO_PURIN				= 39,
  MONSNO_PUKURIN			= 40,
  MONSNO_ZUBATTO			= 41,
  MONSNO_GORUBATTO		= 42,
  MONSNO_NAZONOKUSA		= 43,
  MONSNO_KUSAIHANA		= 44,
  MONSNO_RAHURESIA		= 45,
  MONSNO_PARASU				= 46,
  MONSNO_PARASEKUTO		= 47,
  MONSNO_KONPAN				= 48,
  MONSNO_MORUFON			= 49,
  MONSNO_DHIGUDA			= 50,
  MONSNO_DAGUTORIO		= 51,
  MONSNO_NYAASU				= 52,
  MONSNO_PERUSIAN			= 53,
  MONSNO_KODAKKU			= 54,
  MONSNO_GORUDAKKU		= 55,
  MONSNO_MANKII				= 56,
  MONSNO_OKORIZARU		= 57,
  MONSNO_GAADHI				= 58,
  MONSNO_UINDHI				= 59,
  MONSNO_NYOROMO			= 60,
  MONSNO_NYOROZO			= 61,
  MONSNO_NYOROBON			= 62,
  MONSNO_KEESHI				= 63,
  MONSNO_YUNGERAA			= 64,
  MONSNO_HUUDHIN			= 65,
  MONSNO_WANRIKII			= 66,
  MONSNO_GOORIKII			= 67,
  MONSNO_KAIRIKII			= 68,
  MONSNO_MADATUBOMI		= 69,
  MONSNO_UTUDON				= 70,
  MONSNO_UTUBOTTO			= 71,
  MONSNO_MENOKURAGE		= 72,
  MONSNO_DOKUKURAGE		= 73,
  MONSNO_ISITUBUTE		= 74,
  MONSNO_GOROON				= 75,
  MONSNO_GOROONYA			= 76,
  MONSNO_PONIITA			= 77,
  MONSNO_GYAROPPU			= 78,
  MONSNO_YADON				= 79,
  MONSNO_YADORAN			= 80,
  MONSNO_KOIRU				= 81,
  MONSNO_REAKOIRU			= 82,
  MONSNO_KAMONEGI			= 83,
  MONSNO_DOODOO				= 84,
  MONSNO_DOODORIO			= 85,
  MONSNO_PAUWAU				= 86,
  MONSNO_ZYUGON				= 87,
  MONSNO_BETOBETAA		= 88,
  MONSNO_BETOBETON		= 89,
  MONSNO_SHERUDAA			= 90,
  MONSNO_PARUSHEN			= 91,
  MONSNO_GOOSU				= 92,
  MONSNO_GOOSUTO			= 93,
  MONSNO_GENGAA				= 94,
  MONSNO_IWAAKU				= 95,
  MONSNO_SURIIPU			= 96,
  MONSNO_SURIIPAA			= 97,
  MONSNO_KURABU				= 98,
  MONSNO_KINGURAA			= 99,
  MONSNO_BIRIRIDAMA		= 100,
  MONSNO_MARUMAIN			= 101,
  MONSNO_TAMATAMA			= 102,
  MONSNO_NASSII				= 103,
  MONSNO_KARAKARA			= 104,
  MONSNO_GARAGARA			= 105,
  MONSNO_SAWAMURAA		= 106,
  MONSNO_EBIWARAA			= 107,
  MONSNO_BERORINGA		= 108,
  MONSNO_DOGAASU			= 109,
  MONSNO_MATADOGASU		= 110,
  MONSNO_SAIHOON			= 111,
  MONSNO_SAIDON				= 112,
  MONSNO_RAKKII				= 113,
  MONSNO_MONZYARA			= 114,
  MONSNO_GARUURA			= 115,
  MONSNO_TATTUU				= 116,
  MONSNO_SIIDORA			= 117,
  MONSNO_TOSAKINTO		= 118,
  MONSNO_AZUMAOU			= 119,
  MONSNO_HITODEMAN		= 120,
  MONSNO_SUTAAMII			= 121,
  MONSNO_BARIYAADO		= 122,
  MONSNO_SUTORAIKU		= 123,
  MONSNO_RUUZYURA			= 124,
  MONSNO_EREBUU				= 125,
  MONSNO_BUUBAA				= 126,
  MONSNO_KAIROSU			= 127,
  MONSNO_KENTAROSU		= 128,
  MONSNO_KOIKINGU			= 129,
  MONSNO_GYARADOSU		= 130,
  MONSNO_RAPURASU			= 131,
  MONSNO_METAMON			= 132,
  MONSNO_IIBUI				= 133,
  MONSNO_SYAWAAZU			= 134,
  MONSNO_SANDAASU			= 135,
  MONSNO_BUUSUTAA			= 136,
  MONSNO_PORIGON			= 137,
  MONSNO_OMUNAITO			= 138,
  MONSNO_OMUSUTAA			= 139,
  MONSNO_KABUTO				= 140,
  MONSNO_KABUTOPUSU		= 141,
  MONSNO_PUTERA				= 142,
  MONSNO_KABIGON			= 143,
  MONSNO_HURIIZAA			= 144,
  MONSNO_SANDAA				= 145,
  MONSNO_FAIYAA				= 146,
  MONSNO_MINIRYUU			= 147,
  MONSNO_HAKURYUU			= 148,
  MONSNO_KAIRYUU			= 149,
  MONSNO_MYUUTUU			= 150,
  MONSNO_MYUU					= 151,
  MONSNO_TIKORIITA		= 152,
  MONSNO_BEIRIIHU			= 153,
  MONSNO_MEGANIUMU		= 154,
  MONSNO_HINOARASI		= 155,
  MONSNO_MAGUMARASI		= 156,
  MONSNO_BAKUHUUN			= 157,
  MONSNO_WANINOKO			= 158,
  MONSNO_ARIGEITU			= 159,
  MONSNO_OODAIRU			= 160,
  MONSNO_OTATI				= 161,
  MONSNO_OOTATI				= 162,
  MONSNO_HOOHOO				= 163,
  MONSNO_YORUNOZUKU		= 164,
  MONSNO_REDHIBA			= 165,
  MONSNO_REDHIAN			= 166,
  MONSNO_ITOMARU			= 167,
  MONSNO_ARIADOSU			= 168,
  MONSNO_KUROBATTO		= 169,
  MONSNO_TYONTII			= 170,
  MONSNO_RANTAAN			= 171,
  MONSNO_PITYUU				= 172,
  MONSNO_PHI					= 173,
  MONSNO_PUPURIN			= 174,
  MONSNO_TOGEPII			= 175,
  MONSNO_TOGETIKKU		= 176,
  MONSNO_NEITHI				= 177,
  MONSNO_NEITHIO			= 178,
  MONSNO_MERIIPU			= 179,
  MONSNO_MOKOKO				= 180,
  MONSNO_DENRYUU			= 181,
  MONSNO_KIREIHANA		= 182,
  MONSNO_MARIRU				= 183,
  MONSNO_MARIRURI			= 184,
  MONSNO_USOKKII			= 185,
  MONSNO_NYOROTONO		= 186,
  MONSNO_HANEKKO			= 187,
  MONSNO_POPOKKO			= 188,
  MONSNO_WATAKKO			= 189,
  MONSNO_EIPAMU				= 190,
  MONSNO_HIMANATTU		= 191,
  MONSNO_KIMAWARI			= 192,
  MONSNO_YANYANMA			= 193,
  MONSNO_UPAA					= 194,
  MONSNO_NUOO					= 195,
  MONSNO_EEFI					= 196,
  MONSNO_BURAKKII			= 197,
  MONSNO_YAMIKARASU		= 198,
  MONSNO_YADOKINGU		= 199,
  MONSNO_MUUMA				= 200,
  MONSNO_ANNOON				= 201,
  MONSNO_SOONANSU			= 202,
  MONSNO_KIRINRIKI		= 203,
  MONSNO_KUNUGIDAMA		= 204,
  MONSNO_FORETOSU			= 205,
  MONSNO_NOKOTTI			= 206,
  MONSNO_GURAIGAA			= 207,
  MONSNO_HAGANEERU		= 208,
  MONSNO_BURUU				= 209,
  MONSNO_GURANBURU		= 210,
  MONSNO_HARIISEN			= 211,
  MONSNO_HASSAMU			= 212,
  MONSNO_TUBOTUBO			= 213,
  MONSNO_HERAKUROSU		= 214,
  MONSNO_NYUURA				= 215,
  MONSNO_HIMEGUMA			= 216,
  MONSNO_RINGUMA			= 217,
  MONSNO_MAGUMAGGU		= 218,
  MONSNO_MAGUKARUGO		= 219,
  MONSNO_URIMUU				= 220,
  MONSNO_INOMUU				= 221,
  MONSNO_SANIIGO			= 222,
  MONSNO_TEPPOUO			= 223,
  MONSNO_OKUTAN				= 224,
  MONSNO_DERIBAADO		= 225,
  MONSNO_MANTAIN			= 226,
  MONSNO_EAAMUDO			= 227,
  MONSNO_DERUBIRU			= 228,
  MONSNO_HERUGAA			= 229,
  MONSNO_KINGUDORA		= 230,
  MONSNO_GOMAZOU			= 231,
  MONSNO_DONFAN				= 232,
  MONSNO_PORIGON2			= 233,
  MONSNO_ODOSISI			= 234,
  MONSNO_DOOBURU			= 235,
  MONSNO_BARUKII			= 236,
  MONSNO_KAPOERAA			= 237,
  MONSNO_MUTYUURU			= 238,
  MONSNO_EREKIDDO			= 239,
  MONSNO_BUBHI				= 240,
  MONSNO_MIRUTANKU		= 241,
  MONSNO_HAPINASU			= 242,
  MONSNO_RAIKOU				= 243,
  MONSNO_ENTEI				= 244,
  MONSNO_SUIKUN				= 245,
  MONSNO_YOOGIRASU		= 246,
  MONSNO_SANAGIRASU		= 247,
  MONSNO_BANGIRASU		= 248,
  MONSNO_RUGIA				= 249,
  MONSNO_HOUOU				= 250,
  MONSNO_SEREBHI			= 251,
  MONSNO_KIMORI				= 252,
  MONSNO_ZYUPUTORU		= 253,
  MONSNO_ZYUKAIN			= 254,
  MONSNO_ATYAMO				= 255,
  MONSNO_WAKASYAMO		= 256,
  MONSNO_BASYAAMO			= 257,
  MONSNO_MIZUGOROU		= 258,
  MONSNO_NUMAKUROO		= 259,
  MONSNO_RAGURAAZI		= 260,
  MONSNO_POTIENA			= 261,
  MONSNO_GURAENA			= 262,
  MONSNO_ZIGUZAGUMA		= 263,
  MONSNO_MASSUGUMA		= 264,
  MONSNO_KEMUSSO			= 265,
  MONSNO_KARASARISU		= 266,
  MONSNO_AGEHANTO			= 267,
  MONSNO_MAYURUDO			= 268,
  MONSNO_DOKUKEIRU		= 269,
  MONSNO_HASUBOO			= 270,
  MONSNO_HASUBURERO		= 271,
  MONSNO_RUNPAPPA			= 272,
  MONSNO_TANEBOO			= 273,
  MONSNO_KONOHANA			= 274,
  MONSNO_DAATENGU			= 275,
  MONSNO_SUBAME				= 276,
  MONSNO_OOSUBAME			= 277,
  MONSNO_KYAMOME			= 278,
  MONSNO_PERIPPAA			= 279,
  MONSNO_RARUTOSU			= 280,
  MONSNO_KIRURIA			= 281,
  MONSNO_SAANAITO			= 282,
  MONSNO_AMETAMA			= 283,
  MONSNO_AMEMOOSU			= 284,
  MONSNO_KINOKOKO			= 285,
  MONSNO_KINOGASSA		= 286,
  MONSNO_NAMAKERO			= 287,
  MONSNO_YARUKIMONO		= 288,
  MONSNO_KEKKINGU			= 289,
  MONSNO_TUTININ			= 290,
  MONSNO_TEKKANIN			= 291,
  MONSNO_NUKENIN			= 292,
  MONSNO_GONYONYO			= 293,
  MONSNO_DOGOOMU			= 294,
  MONSNO_BAKUONGU			= 295,
  MONSNO_MAKUNOSITA		= 296,
  MONSNO_HARITEYAMA		= 297,
  MONSNO_RURIRI				= 298,
  MONSNO_NOZUPASU			= 299,
  MONSNO_ENEKO				= 300,
  MONSNO_ENEKORORO		= 301,
  MONSNO_YAMIRAMI			= 302,
  MONSNO_KUTIITO			= 303,
  MONSNO_KOKODORA			= 304,
  MONSNO_KODORA				= 305,
  MONSNO_BOSUGODORA		= 306,
  MONSNO_ASANAN				= 307,
  MONSNO_TYAAREMU			= 308,
  MONSNO_RAKURAI			= 309,
  MONSNO_RAIBORUTO		= 310,
  MONSNO_PURASURU			= 311,
  MONSNO_MAINAN				= 312,
  MONSNO_BARUBIITO		= 313,
  MONSNO_IRUMIIZE			= 314,
  MONSNO_ROZERIA			= 315,
  MONSNO_GOKURIN			= 316,
  MONSNO_MARUNOOMU		= 317,
  MONSNO_KIBANIA			= 318,
  MONSNO_SAMEHADAA		= 319,
  MONSNO_HOERUKO			= 320,
  MONSNO_HOERUOO			= 321,
  MONSNO_DONMERU			= 322,
  MONSNO_BAKUUDA			= 323,
  MONSNO_KOOTASU			= 324,
  MONSNO_BANEBUU			= 325,
  MONSNO_BUUPIGGU			= 326,
  MONSNO_PATTIIRU			= 327,
  MONSNO_NAKKURAA			= 328,
  MONSNO_BIBURAABA		= 329,
  MONSNO_HURAIGON			= 330,
  MONSNO_SABONEA			= 331,
  MONSNO_NOKUTASU			= 332,
  MONSNO_TIRUTTO			= 333,
  MONSNO_TIRUTARISU		= 334,
  MONSNO_ZANGUUSU			= 335,
  MONSNO_HABUNEEKU		= 336,
  MONSNO_RUNATOON			= 337,
  MONSNO_SORUROKKU		= 338,
  MONSNO_DOZYOTTI			= 339,
  MONSNO_NAMAZUN			= 340,
  MONSNO_HEIGANI			= 341,
  MONSNO_SIZARIGAA		= 342,
  MONSNO_YAZIRON			= 343,
  MONSNO_NENDOORU			= 344,
  MONSNO_RIRIIRA			= 345,
  MONSNO_YUREIDORU		= 346,
  MONSNO_ANOPUSU			= 347,
  MONSNO_AAMARUDO			= 348,
  MONSNO_HINBASU			= 349,
  MONSNO_MIROKAROSU		= 350,
  MONSNO_POWARUN			= 351,
  MONSNO_KAKUREON			= 352,
  MONSNO_KAGEBOUZU		= 353,
  MONSNO_ZYUPETTA			= 354,
  MONSNO_YOMAWARU			= 355,
  MONSNO_SAMAYOORU		= 356,
  MONSNO_TOROPIUSU		= 357,
  MONSNO_TIRIIN				= 358,
  MONSNO_ABUSORU			= 359,
  MONSNO_SOONANO			= 360,
  MONSNO_YUKIWARASI		= 361,
  MONSNO_ONIGOORI			= 362,
  MONSNO_TAMAZARASI		= 363,
  MONSNO_TODOGURAA		= 364,
  MONSNO_TODOZERUGA		= 365,
  MONSNO_PAARURU			= 366,
  MONSNO_HANTEERU			= 367,
  MONSNO_SAKURABISU		= 368,
  MONSNO_ZIIRANSU			= 369,
  MONSNO_RABUKASU			= 370,
  MONSNO_TATUBEI			= 371,
  MONSNO_KOMORUU			= 372,
  MONSNO_BOOMANDA			= 373,
  MONSNO_DANBARU			= 374,
  MONSNO_METANGU			= 375,
  MONSNO_METAGUROSU		= 376,
  MONSNO_REZIROKKU		= 377,
  MONSNO_REZIAISU			= 378,
  MONSNO_REZISUTIRU		= 379,
  MONSNO_RATHIASU			= 380,
  MONSNO_RATHIOSU			= 381,
  MONSNO_KAIOOGA			= 382,
  MONSNO_GURAADON			= 383,
  MONSNO_REKKUUZA			= 384,
  MONSNO_ZIRAATI			= 385,
  MONSNO_DEOKISISU		= 386,
  MONSNO_NAETORU			= 387,
  MONSNO_HAYASIGAME		= 388,
  MONSNO_DODAITOSU		= 389,
  MONSNO_HIKOZARU			= 390,
  MONSNO_MOUKAZARU		= 391,
  MONSNO_GOUKAZARU		= 392,
  MONSNO_POTTYAMA			= 393,
  MONSNO_POTTAISI			= 394,
  MONSNO_ENPERUTO			= 395,
  MONSNO_MUKKURU			= 396,
  MONSNO_MUKUBAADO		= 397,
  MONSNO_MUKUHOOKU		= 398,
  MONSNO_BIPPA				= 399,
  MONSNO_BIIDARU			= 400,
  MONSNO_KOROBOOSI		= 401,
  MONSNO_KOROTOKKU		= 402,
  MONSNO_KORINKU			= 403,
  MONSNO_RUKUSIO			= 404,
  MONSNO_RENTORAA			= 405,
  MONSNO_SUBOMII			= 406,
  MONSNO_ROZUREIDO		= 407,
  MONSNO_ZUGAIDOSU		= 408,
  MONSNO_RAMUPARUDO		= 409,
  MONSNO_TATETOPUSU		= 410,
  MONSNO_TORIDEPUSU		= 411,
  MONSNO_MINOMUTTI		= 412,
  MONSNO_MINOMADAMU		= 413,
  MONSNO_GAAMEIRU			= 414,
  MONSNO_MITUHANII		= 415,
  MONSNO_BIIKUIN			= 416,
  MONSNO_PATIRISU			= 417,
  MONSNO_BUIZERU			= 418,
  MONSNO_HUROOZERU		= 419,
  MONSNO_THERINBO			= 420,
  MONSNO_THERIMU			= 421,
  MONSNO_KARANAKUSI		= 422,
  MONSNO_TORITODON		= 423,
  MONSNO_ETEBOOSU			= 424,
  MONSNO_HUWANTE			= 425,
  MONSNO_HUWARAIDO		= 426,
  MONSNO_MIMIRORU			= 427,
  MONSNO_MIMIROPPU		= 428,
  MONSNO_MUUMAAZI			= 429,
  MONSNO_DONKARASU		= 430,
  MONSNO_NYARUMAA			= 431,
  MONSNO_BUNYATTO			= 432,
  MONSNO_RIISYAN			= 433,
  MONSNO_SUKANPUU			= 434,
  MONSNO_SUKATANKU		= 435,
  MONSNO_DOOMIRAA			= 436,
  MONSNO_DOOTAKUN			= 437,
  MONSNO_USOHATI			= 438,
  MONSNO_MANENE				= 439,
  MONSNO_PINPUKU			= 440,
  MONSNO_PERAPPU			= 441,
  MONSNO_MIKARUGE			= 442,
  MONSNO_HUKAMARU			= 443,
  MONSNO_GABAITO			= 444,
  MONSNO_GABURIASU		= 445,
  MONSNO_GONBE				= 446,
  MONSNO_RIORU				= 447,
  MONSNO_RUKARIO			= 448,
  MONSNO_HIPOPOTASU		= 449,
  MONSNO_KABARUDON		= 450,
  MONSNO_SUKORUPI			= 451,
  MONSNO_DORAPION			= 452,
  MONSNO_GUREGGURU		= 453,
  MONSNO_DOKUROGGU		= 454,
  MONSNO_MASUKIPPA		= 455,
  MONSNO_KEIKOUO			= 456,
  MONSNO_NEORANTO			= 457,
  MONSNO_TAMANTA			= 458,
  MONSNO_YUKIKABURI		= 459,
  MONSNO_YUKINOOO			= 460,
  MONSNO_MANYUURA			= 461,
  MONSNO_ZIBAKOIRU		= 462,
  MONSNO_BEROBERUTO		= 463,
  MONSNO_DOSAIDON			= 464,
  MONSNO_MOZYANBO			= 465,
  MONSNO_EREKIBURU		= 466,
  MONSNO_BUUBAAN			= 467,
  MONSNO_TOGEKISSU		= 468,
  MONSNO_MEGAYANMA		= 469,
  MONSNO_RIIFIA				= 470,
  MONSNO_GUREISIA			= 471,
  MONSNO_GURAION			= 472,
  MONSNO_MANMUU				= 473,
  MONSNO_PORIGONz			= 474,
  MONSNO_ERUREIDO			= 475,
  MONSNO_DAINOOZU			= 476,
  MONSNO_YONOWAARU		= 477,
  MONSNO_YUKIMENOKO		= 478,
  MONSNO_ROTOMU				= 479,
  MONSNO_YUKUSII			= 480,
  MONSNO_EMURITTO			= 481,
  MONSNO_AGUNOMU			= 482,
  MONSNO_DHIARUGA			= 483,
  MONSNO_PARUKIA			= 484,
  MONSNO_HIIDORAN			= 485,
  MONSNO_REZIGIGASU		= 486,
  MONSNO_GIRATHINA		= 487,
  MONSNO_KURESERIA		= 488,
  MONSNO_FIONE				= 489,
  MONSNO_MANAFI				= 490,
  MONSNO_DAAKURAI			= 491,
  MONSNO_SHEIMI				= 492,
  MONSNO_ARUSEUSU			= 493,
  MONSNO_BIKUTHINI		= 494,
  MONSNO_TUTAAZYA			= 495,
  MONSNO_ZYANOBII			= 496,
  MONSNO_ZYAROODA			= 497,
  MONSNO_POKABU				= 498,
  MONSNO_TYAOBUU			= 499,
  MONSNO_ENBUOO				= 500,
  MONSNO_MIZYUMARU		= 501,
  MONSNO_HUTATIMARU		= 502,
  MONSNO_DAIKENKI			= 503,
  MONSNO_MINEZUMI			= 504,
  MONSNO_MIRUHOGGU		= 505,
  MONSNO_YOOTERII			= 506,
  MONSNO_HAADERIA			= 507,
  MONSNO_MUURANDO			= 508,
  MONSNO_TYORONEKO		= 509,
  MONSNO_REPARUDASU		= 510,
  MONSNO_YANAPPU			= 511,
  MONSNO_YANAKKII			= 512,
  MONSNO_BAOPPU				= 513,
  MONSNO_BAOKKII			= 514,
  MONSNO_HIYAPPU			= 515,
  MONSNO_HIYAKKII			= 516,
  MONSNO_MUNNA				= 517,
  MONSNO_MUSYAANA			= 518,
  MONSNO_MAMEPATO			= 519,
  MONSNO_HATOOBOO			= 520,
  MONSNO_KENHOROU			= 521,
  MONSNO_SIMAMA				= 522,
  MONSNO_ZEBURAIKA		= 523,
  MONSNO_DANGORO			= 524,
  MONSNO_GANTORU			= 525,
  MONSNO_GIGAIASU			= 526,
  MONSNO_KOROMORI			= 527,
  MONSNO_KOKOROMORI		= 528,
  MONSNO_MOGURYUU			= 529,
  MONSNO_DORYUUZU			= 530,
  MONSNO_TABUNNE			= 531,
  MONSNO_DOKKORAA			= 532,
  MONSNO_DOTEKKOTU		= 533,
  MONSNO_ROOBUSIN			= 534,
  MONSNO_OTAMARO			= 535,
  MONSNO_GAMAGARU			= 536,
  MONSNO_GAMAGEROGE		= 537,
  MONSNO_NAGEKI				= 538,
  MONSNO_DAGEKI				= 539,
  MONSNO_KURUMIRU			= 540,
  MONSNO_KURUMAYU			= 541,
  MONSNO_HAHAKOMORI		= 542,
  MONSNO_HUSIDE				= 543,
  MONSNO_HOIIGA				= 544,
  MONSNO_PENDORAA			= 545,
  MONSNO_MONMEN				= 546,
  MONSNO_ERUHUUN			= 547,
  MONSNO_TYURINE			= 548,
  MONSNO_DOREDHIA			= 549,
  MONSNO_BASURAO			= 550,
  MONSNO_MEGUROKO			= 551,
  MONSNO_WARUBIRU			= 552,
  MONSNO_WARUBIARU		= 553,
  MONSNO_DARUMAKKA		= 554,
  MONSNO_HIHIDARUMA		= 555,
  MONSNO_MARAKATTI		= 556,
  MONSNO_ISIZUMAI			= 557,
  MONSNO_IWAPARESU		= 558,
  MONSNO_ZURUGGU			= 559,
  MONSNO_ZURUZUKIN		= 560,
  MONSNO_SINBORAA			= 561,
  MONSNO_DESUMASU			= 562,
  MONSNO_DESUKAAN			= 563,
  MONSNO_PUROTOOGA		= 564,
  MONSNO_ABAGOORA			= 565,
  MONSNO_AAKEN				= 566,
  MONSNO_AAKEOSU			= 567,
  MONSNO_YABUKURON		= 568,
  MONSNO_DASUTODASU		= 569,
  MONSNO_ZOROA				= 570,
  MONSNO_ZOROAAKU			= 571,
  MONSNO_TIRAAMHI			= 572,
  MONSNO_TIRATIINO		= 573,
  MONSNO_GOTIMU				= 574,
  MONSNO_GOTIMIRU			= 575,
  MONSNO_GOTIRUZERU		= 576,
  MONSNO_YUNIRAN			= 577,
  MONSNO_DABURAN			= 578,
  MONSNO_RANKURUSU		= 579,
  MONSNO_KOARUHII			= 580,
  MONSNO_SUWANNA			= 581,
  MONSNO_BANIPUTTI		= 582,
  MONSNO_BANIRITTI		= 583,
  MONSNO_BAIBANIRA		= 584,
  MONSNO_SIKIZIKA			= 585,
  MONSNO_MEBUKIZIKA		= 586,
  MONSNO_EMONGA				= 587,
  MONSNO_KABURUMO			= 588,
  MONSNO_SYUBARUGO		= 589,
  MONSNO_TAMAGETAKE		= 590,
  MONSNO_MOROBARERU		= 591,
  MONSNO_PURURIRU			= 592,
  MONSNO_BURUNGERU		= 593,
  MONSNO_MAMANBOU			= 594,
  MONSNO_BATYURU			= 595,
  MONSNO_DENTYURA			= 596,
  MONSNO_TESSIIDO			= 597,
  MONSNO_NATTOREI			= 598,
  MONSNO_GIARU				= 599,
  MONSNO_GIGIARU			= 600,
  MONSNO_GIGIGIARU		= 601,
  MONSNO_SIBISIRASU		= 602,
  MONSNO_SIBIBIIRU		= 603,
  MONSNO_SIBIRUDON		= 604,
  MONSNO_RIGUREE			= 605,
  MONSNO_OOBEMU				= 606,
  MONSNO_HITOMOSI			= 607,
  MONSNO_RANPURAA			= 608,
  MONSNO_SYANDERA			= 609,
  MONSNO_KIBAGO				= 610,
  MONSNO_ONONDO				= 611,
  MONSNO_ONONOKUSU		= 612,
  MONSNO_KUMASYUN			= 613,
  MONSNO_TUNBEAA			= 614,
  MONSNO_HURIIZIO			= 615,
  MONSNO_TYOBOMAKI		= 616,
  MONSNO_AGIRUDAA			= 617,
  MONSNO_MAGGYO				= 618,
  MONSNO_KOZYOHUU			= 619,
  MONSNO_KOZYONDO			= 620,
  MONSNO_KURIMUGAN		= 621,
  MONSNO_GOBITTO			= 622,
  MONSNO_GORUUGU			= 623,
  MONSNO_KOMATANA			= 624,
  MONSNO_KIRIKIZAN		= 625,
  MONSNO_BAHHURON			= 626,
  MONSNO_WASIBON			= 627,
  MONSNO_WHOOGURU			= 628,
  MONSNO_BARUTYAI			= 629,
  MONSNO_BARUZIINA		= 630,
  MONSNO_KUITARAN			= 631,
  MONSNO_AIANTO				= 632,
  MONSNO_MONOZU				= 633,
  MONSNO_ZIHEDDO			= 634,
  MONSNO_SAZANDORA		= 635,
  MONSNO_MERARUBA			= 636,
  MONSNO_URUGAMOSU		= 637,
  MONSNO_KOBARUON			= 638,
  MONSNO_TERAKION			= 639,
  MONSNO_BIRIZION			= 640,
  MONSNO_TORUNEROSU		= 641,
  MONSNO_BORUTOROSU		= 642,
  MONSNO_RESIRAMU			= 643,
  MONSNO_ZEKUROMU			= 644,
  MONSNO_RANDOROSU		= 645,
  MONSNO_KYUREMU			= 646,
  MONSNO_KERUDHIO			= 647,
  MONSNO_MEROETTA			= 648,
  MONSNO_GENOSEKUTO		= 649,
  MONSNO_HARIMARON		= 650,
  MONSNO_HARIBOOGU		= 651,
  MONSNO_BURIGARON		= 652,
  MONSNO_FOKKO				= 653,
  MONSNO_TEERUNAA			= 654,
  MONSNO_MAFOKUSII		= 655,
  MONSNO_KEROMATU			= 656,
  MONSNO_GEKOGASIRA		= 657,
  MONSNO_GEKKOUGA			= 658,
  MONSNO_HORUBII			= 659,
  MONSNO_HORUUDO			= 660,
  MONSNO_YAYAKOMA			= 661,
  MONSNO_HINOYAKOMA		= 662,
  MONSNO_FAIAROO			= 663,
  MONSNO_KOHUKIMUSI		= 664,
  MONSNO_KOHUURAI			= 665,
  MONSNO_BIBIYON			= 666,
  MONSNO_SISIKO				= 667,
  MONSNO_KAENZISI			= 668,
  MONSNO_HURABEBE			= 669,
  MONSNO_HURAETTE			= 670,
  MONSNO_HURAAJESU		= 671,
  MONSNO_MHEEKURU			= 672,
  MONSNO_GOOGOOTO			= 673,
  MONSNO_YANTYAMU			= 674,
  MONSNO_GORONDA			= 675,
  MONSNO_TORIMIAN			= 676,
  MONSNO_NYASUPAA			= 677,
  MONSNO_NYAONIKUSU		= 678,
  MONSNO_HITOTUKI			= 679,
  MONSNO_NIDANGIRU		= 680,
  MONSNO_GIRUGARUDO		= 681,
  MONSNO_SYUSYUPU			= 682,
  MONSNO_HUREHUWAN		= 683,
  MONSNO_PEROPPAHU		= 684,
  MONSNO_PERORIIMU		= 685,
  MONSNO_MAAIIKA			= 686,
  MONSNO_KARAMANERO		= 687,
  MONSNO_KAMETETE			= 688,
  MONSNO_GAMENODESU		= 689,
  MONSNO_KUZUMOO			= 690,
  MONSNO_DORAMIDORO		= 691,
  MONSNO_UDEPPOU			= 692,
  MONSNO_BUROSUTAA		= 693,
  MONSNO_ERIKITERU		= 694,
  MONSNO_EREZAADO			= 695,
  MONSNO_TIGORASU			= 696,
  MONSNO_GATIGORASU		= 697,
  MONSNO_AMARUSU			= 698,
  MONSNO_AMARURUGA		= 699,
  MONSNO_NINFIA				= 700,
  MONSNO_RUTYABURU		= 701,
  MONSNO_DEDENNE			= 702,
  MONSNO_MERESII			= 703,
  MONSNO_NUMERA				= 704,
  MONSNO_NUMEIRU			= 705,
  MONSNO_NUMERUGON		= 706,
  MONSNO_KUREHFI			= 707,
  MONSNO_BOKUREE			= 708,
  MONSNO_OOROTTO			= 709,
  MONSNO_BAKETTYA			= 710,
  MONSNO_PANPUZIN			= 711,
  MONSNO_KATIKOORU		= 712,
  MONSNO_KUREBEESU		= 713,
  MONSNO_ONBATTO			= 714,
  MONSNO_ONBAAN				= 715,
  MONSNO_ZERUNEASU		= 716,
  MONSNO_IBERUTARU		= 717,
  MONSNO_ZIGARUDE			= 718,
  MONSNO_DHIANSII			= 719,
  MONSNO_HUUPA				= 720,
  MONSNO_BORUKENION		= 721,
  MONSNO_HUKUROU1			= 722,
  MONSNO_HUKUROU2			= 723,
  MONSNO_HUKUROU3			= 724,
  MONSNO_TORA1				= 725,
  MONSNO_TORA2				= 726,
  MONSNO_TORA3				= 727,
  MONSNO_ASIKA1				= 728,
  MONSNO_ASIKA2				= 729,
  MONSNO_ASIKA3				= 730,
  MONSNO_KUTIBASI1		= 731,
  MONSNO_KUTIBASI2		= 732,
  MONSNO_KUTIBASI3		= 733,
  MONSNO_MANGUUSU1		= 734,
  MONSNO_MANGUUSU2		= 735,
  MONSNO_KUWAGATA1		= 736,
  MONSNO_KUWAGATA2		= 737,
  MONSNO_KUWAGATA3		= 738,
  MONSNO_YASIGANI1		= 739,
  MONSNO_YASIGANI2		= 740,
  MONSNO_MITUSUI			= 741,
  MONSNO_ABU1					= 742,
  MONSNO_ABU2					= 743,
  MONSNO_OOKAMI1			= 744,
  MONSNO_OOKAMI2			= 745,
  MONSNO_YOWASI				= 746,
  MONSNO_ONIHITODE1		= 747,
  MONSNO_ONIHITODE2		= 748,
  MONSNO_ROBA1				= 749,
  MONSNO_ROBA2				= 750,
  MONSNO_MIZUGUMO1		= 751,
  MONSNO_MIZUGUMO2		= 752,
  MONSNO_HANAKAMA1		= 753,
  MONSNO_HANAKAMA2		= 754,
  MONSNO_RANPUDAKE1		= 755,
  MONSNO_RANPUDAKE2		= 756,
  MONSNO_DOKUTOKAGE1	= 757,
  MONSNO_DOKUTOKAGE2	= 758,
  MONSNO_RESSAA1			= 759,
  MONSNO_RESSAA2			= 760,
  MONSNO_HURUUTU1			= 761,
  MONSNO_HURUUTU2			= 762,
  MONSNO_HURUUTU3			= 763,
  MONSNO_REI					= 764,
  MONSNO_UUTAN				= 765,
  MONSNO_HUTTOSARU		= 766,
  MONSNO_GUSOKUMUSI1	= 767,
  MONSNO_GUSOKUMUSI2	= 768,
  MONSNO_SUNABA1			= 769,
  MONSNO_SUNABA2			= 770,
  MONSNO_NAMAKO				= 771,
  MONSNO_GURIPUSU1		= 772,
  MONSNO_GURIPUSU2		= 773,
  MONSNO_NAGAREBOSI		= 774,
  MONSNO_KOARA				= 775,
  MONSNO_MATAMATA			= 776,
  MONSNO_NIZITYUU			= 777,
  MONSNO_HORAA				= 778,
  MONSNO_KAWAHAGI			= 779,
  MONSNO_DORAGON			= 780,
  MONSNO_DARIN				= 781,
  MONSNO_UROKO1				= 782,
  MONSNO_UROKO2				= 783,
  MONSNO_UROKO3				= 784,
  MONSNO_THIKITORI		= 785,
  MONSNO_THIKITYOU		= 786,
  MONSNO_THIKIUSI			= 787,
  MONSNO_THIKISAKANA	= 788,
  MONSNO_BEBII				= 789,
  MONSNO_MAYU					= 790,
  MONSNO_NIKKOU				= 791,
  MONSNO_GEKKOU				= 792,
  MONSNO_BIISUTOr			= 793,
  MONSNO_BIISUTOy			= 794,
  MONSNO_BIISUTOb			= 795,
  MONSNO_BIISUTOg			= 796,
  MONSNO_BIISUTOp			= 797,
  MONSNO_BIISUTOi			= 798,
  MONSNO_BIISUTOo			= 799,
  MONSNO_PURIZUMU			= 800,
  MONSNO_MABOROSI16		= 801,
  MONSNO_MABOROSI17		= 802,
  MONSNO_BIISUTOd1		= 803,
  MONSNO_BIISUTOd2		= 804,
  MONSNO_BIISUTOs			= 805,
  MONSNO_BIISUTOh			= 806,
  MONSNO_MABOROSI18		= 807,
  MONSNO_TAMAGO				= 808,
  MONSNO_DAMETAMAGO		= 809,
  MONSNO_END					= 807,
  MONSNO_MAX					= 809,
};

//別フォルム定義
//フシギバナ
#define		FORMNO_HUSIGIBANA_NORMAL				( 0 )
#define		FORMNO_HUSIGIBANA_MEGA				( 1 )
#define		FORMNO_HUSIGIBANA_MAX				( 2 )

//リザードン
#define		FORMNO_RIZAADON_NORMAL				( 0 )
#define		FORMNO_RIZAADON_MEGAX				( 1 )
#define		FORMNO_RIZAADON_MEGAY				( 2 )
#define		FORMNO_RIZAADON_MAX				( 3 )

//カメックス
#define		FORMNO_KAMEKKUSU_NORMAL				( 0 )
#define		FORMNO_KAMEKKUSU_MEGA				( 1 )
#define		FORMNO_KAMEKKUSU_MAX				( 2 )

//スピアー
#define		FORMNO_SUPIAA_NORMAL				( 0 )
#define		FORMNO_SUPIAA_MEGA				( 1 )
#define		FORMNO_SUPIAA_MAX				( 2 )

//ピジョット
#define		FORMNO_PIZYOTTO_NORMAL				( 0 )
#define		FORMNO_PIZYOTTO_MEGA				( 1 )
#define		FORMNO_PIZYOTTO_MAX				( 2 )

//コラッタ
#define		FORMNO_KORATTA_NORMAL				( 0 )
#define		FORMNO_KORATTA_ALOLA				( 1 )
#define		FORMNO_KORATTA_MAX				( 2 )

//ラッタ
#define		FORMNO_RATTA_NORMAL				( 0 )
#define		FORMNO_RATTA_ALOLA				( 1 )
#define		FORMNO_RATTA_NUSHI				( 2 )
#define		FORMNO_RATTA_MAX				( 3 )

//ピカチュウ
#define		FORMNO_PIKATYUU_NORMAL				( 0 )
#define		FORMNO_PIKATYUU_SATOPIKAMU				( 1 )
#define		FORMNO_PIKATYUU_SATOPIKAAG				( 2 )
#define		FORMNO_PIKATYUU_SATOPIKADP				( 3 )
#define		FORMNO_PIKATYUU_SATOPIKABW				( 4 )
#define		FORMNO_PIKATYUU_SATOPIKAXY				( 5 )
#define		FORMNO_PIKATYUU_SATOPIKASM				( 6 )
#define		FORMNO_PIKATYUU_SATOPIKA20				( 7 )
#define		FORMNO_PIKATYUU_MAX				( 8 )

//ライチュウ
#define		FORMNO_RAITYUU_NORMAL				( 0 )
#define		FORMNO_RAITYUU_ALOLA				( 1 )
#define		FORMNO_RAITYUU_MAX				( 2 )

//サンド
#define		FORMNO_SANDO_NORMAL				( 0 )
#define		FORMNO_SANDO_ALOLA				( 1 )
#define		FORMNO_SANDO_MAX				( 2 )

//サンドパン
#define		FORMNO_SANDOPAN_NORMAL				( 0 )
#define		FORMNO_SANDOPAN_ALOLA				( 1 )
#define		FORMNO_SANDOPAN_MAX				( 2 )

//ロコン
#define		FORMNO_ROKON_NORMAL				( 0 )
#define		FORMNO_ROKON_ALOLA				( 1 )
#define		FORMNO_ROKON_MAX				( 2 )

//キュウコン
#define		FORMNO_KYUUKON_NORMAL				( 0 )
#define		FORMNO_KYUUKON_ALOLA				( 1 )
#define		FORMNO_KYUUKON_MAX				( 2 )

//ディグダ
#define		FORMNO_DHIGUDA_NORMAL				( 0 )
#define		FORMNO_DHIGUDA_ALOLA				( 1 )
#define		FORMNO_DHIGUDA_MAX				( 2 )

//ダグトリオ
#define		FORMNO_DAGUTORIO_NORMAL				( 0 )
#define		FORMNO_DAGUTORIO_ALOLA				( 1 )
#define		FORMNO_DAGUTORIO_MAX				( 2 )

//ニャース
#define		FORMNO_NYAASU_NORMAL				( 0 )
#define		FORMNO_NYAASU_ALOLA				( 1 )
#define		FORMNO_NYAASU_MAX				( 2 )

//ペルシアン
#define		FORMNO_PERUSIAN_NORMAL				( 0 )
#define		FORMNO_PERUSIAN_ALOLA				( 1 )
#define		FORMNO_PERUSIAN_MAX				( 2 )

//フーディン
#define		FORMNO_HUUDHIN_NORMAL				( 0 )
#define		FORMNO_HUUDHIN_MEGA				( 1 )
#define		FORMNO_HUUDHIN_MAX				( 2 )

//イシツブテ
#define		FORMNO_ISITUBUTE_NORMAL				( 0 )
#define		FORMNO_ISITUBUTE_ALOLA				( 1 )
#define		FORMNO_ISITUBUTE_MAX				( 2 )

//ゴローン
#define		FORMNO_GOROON_NORMAL				( 0 )
#define		FORMNO_GOROON_ALOLA				( 1 )
#define		FORMNO_GOROON_MAX				( 2 )

//ゴローニャ
#define		FORMNO_GOROONYA_NORMAL				( 0 )
#define		FORMNO_GOROONYA_ALOLA				( 1 )
#define		FORMNO_GOROONYA_MAX				( 2 )

//ヤドラン
#define		FORMNO_YADORAN_NORMAL				( 0 )
#define		FORMNO_YADORAN_MEGA				( 1 )
#define		FORMNO_YADORAN_MAX				( 2 )

//ベトベター
#define		FORMNO_BETOBETAA_NORMAL				( 0 )
#define		FORMNO_BETOBETAA_ALOLA				( 1 )
#define		FORMNO_BETOBETAA_MAX				( 2 )

//ベトベトン
#define		FORMNO_BETOBETON_NORMAL				( 0 )
#define		FORMNO_BETOBETON_ALOLA				( 1 )
#define		FORMNO_BETOBETON_MAX				( 2 )

//ゲンガー
#define		FORMNO_GENGAA_NORMAL				( 0 )
#define		FORMNO_GENGAA_MEGA				( 1 )
#define		FORMNO_GENGAA_MAX				( 2 )

//ナッシー
#define		FORMNO_NASSII_NORMAL				( 0 )
#define		FORMNO_NASSII_ALOLA				( 1 )
#define		FORMNO_NASSII_MAX				( 2 )

//ガラガラ
#define		FORMNO_GARAGARA_NORMAL				( 0 )
#define		FORMNO_GARAGARA_ALOLA				( 1 )
#define		FORMNO_GARAGARA_NUSHI				( 2 )
#define		FORMNO_GARAGARA_MAX				( 3 )

//ガルーラ
#define		FORMNO_GARUURA_NORMAL				( 0 )
#define		FORMNO_GARUURA_MEGA				( 1 )
#define		FORMNO_GARUURA_MAX				( 2 )

//カイロス
#define		FORMNO_KAIROSU_NORMAL				( 0 )
#define		FORMNO_KAIROSU_MEGA				( 1 )
#define		FORMNO_KAIROSU_MAX				( 2 )

//ギャラドス
#define		FORMNO_GYARADOSU_NORMAL				( 0 )
#define		FORMNO_GYARADOSU_MEGA				( 1 )
#define		FORMNO_GYARADOSU_MAX				( 2 )

//プテラ
#define		FORMNO_PUTERA_NORMAL				( 0 )
#define		FORMNO_PUTERA_MEGA				( 1 )
#define		FORMNO_PUTERA_MAX				( 2 )

//ミュウツー
#define		FORMNO_MYUUTUU_NORMAL				( 0 )
#define		FORMNO_MYUUTUU_MEGAX				( 1 )
#define		FORMNO_MYUUTUU_MEGAY				( 2 )
#define		FORMNO_MYUUTUU_MAX				( 3 )

//デンリュウ
#define		FORMNO_DENRYUU_NORMAL				( 0 )
#define		FORMNO_DENRYUU_MEGA				( 1 )
#define		FORMNO_DENRYUU_MAX				( 2 )

//アンノーン
#define		FORMNO_ANNOON_UNA				( 0 )
#define		FORMNO_ANNOON_UNB				( 1 )
#define		FORMNO_ANNOON_UNC				( 2 )
#define		FORMNO_ANNOON_UND				( 3 )
#define		FORMNO_ANNOON_UNE				( 4 )
#define		FORMNO_ANNOON_UNF				( 5 )
#define		FORMNO_ANNOON_UNG				( 6 )
#define		FORMNO_ANNOON_UNH				( 7 )
#define		FORMNO_ANNOON_UNI				( 8 )
#define		FORMNO_ANNOON_UNJ				( 9 )
#define		FORMNO_ANNOON_UNK				( 10 )
#define		FORMNO_ANNOON_UNL				( 11 )
#define		FORMNO_ANNOON_UNM				( 12 )
#define		FORMNO_ANNOON_UNN				( 13 )
#define		FORMNO_ANNOON_UNO				( 14 )
#define		FORMNO_ANNOON_UNP				( 15 )
#define		FORMNO_ANNOON_UNQ				( 16 )
#define		FORMNO_ANNOON_UNR				( 17 )
#define		FORMNO_ANNOON_UNS				( 18 )
#define		FORMNO_ANNOON_UNT				( 19 )
#define		FORMNO_ANNOON_UNU				( 20 )
#define		FORMNO_ANNOON_UNV				( 21 )
#define		FORMNO_ANNOON_UNW				( 22 )
#define		FORMNO_ANNOON_UNX				( 23 )
#define		FORMNO_ANNOON_UNY				( 24 )
#define		FORMNO_ANNOON_UNZ				( 25 )
#define		FORMNO_ANNOON_EXC				( 26 )
#define		FORMNO_ANNOON_QUE				( 27 )
#define		FORMNO_ANNOON_MAX				( 28 )

//ハガネール
#define		FORMNO_HAGANEERU_NORMAL				( 0 )
#define		FORMNO_HAGANEERU_MEGA				( 1 )
#define		FORMNO_HAGANEERU_MAX				( 2 )

//ハッサム
#define		FORMNO_HASSAMU_NORMAL				( 0 )
#define		FORMNO_HASSAMU_MEGA				( 1 )
#define		FORMNO_HASSAMU_MAX				( 2 )

//ヘラクロス
#define		FORMNO_HERAKUROSU_NORMAL				( 0 )
#define		FORMNO_HERAKUROSU_MEGA				( 1 )
#define		FORMNO_HERAKUROSU_MAX				( 2 )

//ヘルガー
#define		FORMNO_HERUGAA_NORMAL				( 0 )
#define		FORMNO_HERUGAA_MEGA				( 1 )
#define		FORMNO_HERUGAA_MAX				( 2 )

//バンギラス
#define		FORMNO_BANGIRASU_NORMAL				( 0 )
#define		FORMNO_BANGIRASU_MEGA				( 1 )
#define		FORMNO_BANGIRASU_MAX				( 2 )

//ジュカイン
#define		FORMNO_ZYUKAIN_NORMAL				( 0 )
#define		FORMNO_ZYUKAIN_MEGA				( 1 )
#define		FORMNO_ZYUKAIN_MAX				( 2 )

//バシャーモ
#define		FORMNO_BASYAAMO_NORMAL				( 0 )
#define		FORMNO_BASYAAMO_MEGA				( 1 )
#define		FORMNO_BASYAAMO_MAX				( 2 )

//ラグラージ
#define		FORMNO_RAGURAAZI_NORMAL				( 0 )
#define		FORMNO_RAGURAAZI_MEGA				( 1 )
#define		FORMNO_RAGURAAZI_MAX				( 2 )

//サーナイト
#define		FORMNO_SAANAITO_NORMAL				( 0 )
#define		FORMNO_SAANAITO_MEGA				( 1 )
#define		FORMNO_SAANAITO_MAX				( 2 )

//ヤミラミ
#define		FORMNO_YAMIRAMI_NORMAL				( 0 )
#define		FORMNO_YAMIRAMI_MEGA				( 1 )
#define		FORMNO_YAMIRAMI_MAX				( 2 )

//クチート
#define		FORMNO_KUTIITO_NORMAL				( 0 )
#define		FORMNO_KUTIITO_MEGA				( 1 )
#define		FORMNO_KUTIITO_MAX				( 2 )

//ボスゴドラ
#define		FORMNO_BOSUGODORA_NORMAL				( 0 )
#define		FORMNO_BOSUGODORA_MEGA				( 1 )
#define		FORMNO_BOSUGODORA_MAX				( 2 )

//チャーレム
#define		FORMNO_TYAAREMU_NORMAL				( 0 )
#define		FORMNO_TYAAREMU_MEGA				( 1 )
#define		FORMNO_TYAAREMU_MAX				( 2 )

//ライボルト
#define		FORMNO_RAIBORUTO_NORMAL				( 0 )
#define		FORMNO_RAIBORUTO_MEGA				( 1 )
#define		FORMNO_RAIBORUTO_MAX				( 2 )

//サメハダー
#define		FORMNO_SAMEHADAA_NORMAL				( 0 )
#define		FORMNO_SAMEHADAA_MEGA				( 1 )
#define		FORMNO_SAMEHADAA_MAX				( 2 )

//バクーダ
#define		FORMNO_BAKUUDA_NORMAL				( 0 )
#define		FORMNO_BAKUUDA_MEGA				( 1 )
#define		FORMNO_BAKUUDA_MAX				( 2 )

//チルタリス
#define		FORMNO_TIRUTARISU_NORMAL				( 0 )
#define		FORMNO_TIRUTARISU_MEGA				( 1 )
#define		FORMNO_TIRUTARISU_MAX				( 2 )

//ポワルン
#define		FORMNO_POWARUN_NORMAL				( 0 )
#define		FORMNO_POWARUN_SUN				( 1 )
#define		FORMNO_POWARUN_RAIN				( 2 )
#define		FORMNO_POWARUN_SNOW				( 3 )
#define		FORMNO_POWARUN_MAX				( 4 )

//ジュペッタ
#define		FORMNO_ZYUPETTA_NORMAL				( 0 )
#define		FORMNO_ZYUPETTA_MEGA				( 1 )
#define		FORMNO_ZYUPETTA_MAX				( 2 )

//アブソル
#define		FORMNO_ABUSORU_NORMAL				( 0 )
#define		FORMNO_ABUSORU_MEGA				( 1 )
#define		FORMNO_ABUSORU_MAX				( 2 )

//オニゴーリ
#define		FORMNO_ONIGOORI_NORMAL				( 0 )
#define		FORMNO_ONIGOORI_MEGA				( 1 )
#define		FORMNO_ONIGOORI_MAX				( 2 )

//ボーマンダ
#define		FORMNO_BOOMANDA_NORMAL				( 0 )
#define		FORMNO_BOOMANDA_MEGA				( 1 )
#define		FORMNO_BOOMANDA_MAX				( 2 )

//メタグロス
#define		FORMNO_METAGUROSU_NORMAL				( 0 )
#define		FORMNO_METAGUROSU_MEGA				( 1 )
#define		FORMNO_METAGUROSU_MAX				( 2 )

//ラティアス
#define		FORMNO_RATHIASU_NORMAL				( 0 )
#define		FORMNO_RATHIASU_MEGA				( 1 )
#define		FORMNO_RATHIASU_MAX				( 2 )

//ラティオス
#define		FORMNO_RATHIOSU_NORMAL				( 0 )
#define		FORMNO_RATHIOSU_MEGA				( 1 )
#define		FORMNO_RATHIOSU_MAX				( 2 )

//カイオーガ
#define		FORMNO_KAIOOGA_NORMAL				( 0 )
#define		FORMNO_KAIOOGA_ALPHA				( 1 )
#define		FORMNO_KAIOOGA_MAX				( 2 )

//グラードン
#define		FORMNO_GURAADON_NORMAL				( 0 )
#define		FORMNO_GURAADON_OMEGA				( 1 )
#define		FORMNO_GURAADON_MAX				( 2 )

//レックウザ
#define		FORMNO_REKKUUZA_NORMAL				( 0 )
#define		FORMNO_REKKUUZA_DELTA				( 1 )
#define		FORMNO_REKKUUZA_MAX				( 2 )

//デオキシス
#define		FORMNO_DEOKISISU_NORMAL				( 0 )
#define		FORMNO_DEOKISISU_ATTACK				( 1 )
#define		FORMNO_DEOKISISU_DEFENCE				( 2 )
#define		FORMNO_DEOKISISU_SPEED				( 3 )
#define		FORMNO_DEOKISISU_MAX				( 4 )

//ミノムッチ
#define		FORMNO_MINOMUTTI_KUSA				( 0 )
#define		FORMNO_MINOMUTTI_SUNA				( 1 )
#define		FORMNO_MINOMUTTI_GOMI				( 2 )
#define		FORMNO_MINOMUTTI_MAX				( 3 )

//ミノマダム
#define		FORMNO_MINOMADAMU_KUSA				( 0 )
#define		FORMNO_MINOMADAMU_JIMEN				( 1 )
#define		FORMNO_MINOMADAMU_HAGANE				( 2 )
#define		FORMNO_MINOMADAMU_MAX				( 3 )

//ガーメイル
#define		FORMNO_GAAMEIRU_KUSA				( 0 )
#define		FORMNO_GAAMEIRU_SUNA				( 1 )
#define		FORMNO_GAAMEIRU_GOMI				( 2 )
#define		FORMNO_GAAMEIRU_MAX				( 3 )

//チェリム
#define		FORMNO_THERIMU_NEGA				( 0 )
#define		FORMNO_THERIMU_POSI				( 1 )
#define		FORMNO_THERIMU_MAX				( 2 )

//カラナクシ
#define		FORMNO_KARANAKUSI_WEST				( 0 )
#define		FORMNO_KARANAKUSI_EAST				( 1 )
#define		FORMNO_KARANAKUSI_MAX				( 2 )

//トリトドン
#define		FORMNO_TORITODON_WEST				( 0 )
#define		FORMNO_TORITODON_EAST				( 1 )
#define		FORMNO_TORITODON_MAX				( 2 )

//ミミロップ
#define		FORMNO_MIMIROPPU_NORMAL				( 0 )
#define		FORMNO_MIMIROPPU_MEGA				( 1 )
#define		FORMNO_MIMIROPPU_MAX				( 2 )

//ガブリアス
#define		FORMNO_GABURIASU_NORMAL				( 0 )
#define		FORMNO_GABURIASU_MEGA				( 1 )
#define		FORMNO_GABURIASU_MAX				( 2 )

//ルカリオ
#define		FORMNO_RUKARIO_NORMAL				( 0 )
#define		FORMNO_RUKARIO_MEGA				( 1 )
#define		FORMNO_RUKARIO_MAX				( 2 )

//ユキノオー
#define		FORMNO_YUKINOOO_NORMAL				( 0 )
#define		FORMNO_YUKINOOO_MEGA				( 1 )
#define		FORMNO_YUKINOOO_MAX				( 2 )

//エルレイド
#define		FORMNO_ERUREIDO_NORMAL				( 0 )
#define		FORMNO_ERUREIDO_MEGA				( 1 )
#define		FORMNO_ERUREIDO_MAX				( 2 )

//ロトム
#define		FORMNO_ROTOMU_NORMAL				( 0 )
#define		FORMNO_ROTOMU_HOT				( 1 )
#define		FORMNO_ROTOMU_WASH				( 2 )
#define		FORMNO_ROTOMU_COLD				( 3 )
#define		FORMNO_ROTOMU_FAN				( 4 )
#define		FORMNO_ROTOMU_CUT				( 5 )
#define		FORMNO_ROTOMU_MAX				( 6 )

//ギラティナ
#define		FORMNO_GIRATHINA_ANOTHER				( 0 )
#define		FORMNO_GIRATHINA_ORIGIN				( 1 )
#define		FORMNO_GIRATHINA_MAX				( 2 )

//シェイミ
#define		FORMNO_SHEIMI_LAND				( 0 )
#define		FORMNO_SHEIMI_SKY				( 1 )
#define		FORMNO_SHEIMI_MAX				( 2 )

//アルセウス
#define		FORMNO_ARUSEUSU_NORMAL				( 0 )
#define		FORMNO_ARUSEUSU_BATTLE				( 1 )
#define		FORMNO_ARUSEUSU_HIKOU				( 2 )
#define		FORMNO_ARUSEUSU_POISON				( 3 )
#define		FORMNO_ARUSEUSU_JIMEN				( 4 )
#define		FORMNO_ARUSEUSU_IWA				( 5 )
#define		FORMNO_ARUSEUSU_MUSHI				( 6 )
#define		FORMNO_ARUSEUSU_GHOST				( 7 )
#define		FORMNO_ARUSEUSU_METAL				( 8 )
#define		FORMNO_ARUSEUSU_FIRE				( 9 )
#define		FORMNO_ARUSEUSU_WATER				( 10 )
#define		FORMNO_ARUSEUSU_KUSA				( 11 )
#define		FORMNO_ARUSEUSU_ELECTRIC				( 12 )
#define		FORMNO_ARUSEUSU_ESPER				( 13 )
#define		FORMNO_ARUSEUSU_KOORI				( 14 )
#define		FORMNO_ARUSEUSU_DRAGON				( 15 )
#define		FORMNO_ARUSEUSU_AKU				( 16 )
#define		FORMNO_ARUSEUSU_FAIRY				( 17 )
#define		FORMNO_ARUSEUSU_MAX				( 18 )

//タブンネ
#define		FORMNO_TABUNNE_NORMAL				( 0 )
#define		FORMNO_TABUNNE_MEGA				( 1 )
#define		FORMNO_TABUNNE_MAX				( 2 )

//バスラオ
#define		FORMNO_BASURAO_BLACK				( 0 )
#define		FORMNO_BASURAO_WHITE				( 1 )
#define		FORMNO_BASURAO_MAX				( 2 )

//ヒヒダルマ
#define		FORMNO_HIHIDARUMA_ACTION				( 0 )
#define		FORMNO_HIHIDARUMA_MEDITATION				( 1 )
#define		FORMNO_HIHIDARUMA_MAX				( 2 )

//シキジカ
#define		FORMNO_SIKIZIKA_SPRING				( 0 )
#define		FORMNO_SIKIZIKA_SUMMER				( 1 )
#define		FORMNO_SIKIZIKA_AUTUMN				( 2 )
#define		FORMNO_SIKIZIKA_WINTER				( 3 )
#define		FORMNO_SIKIZIKA_MAX				( 4 )

//メブキジカ
#define		FORMNO_MEBUKIZIKA_SPRING				( 0 )
#define		FORMNO_MEBUKIZIKA_SUMMER				( 1 )
#define		FORMNO_MEBUKIZIKA_AUTUMN				( 2 )
#define		FORMNO_MEBUKIZIKA_WINTER				( 3 )
#define		FORMNO_MEBUKIZIKA_MAX				( 4 )

//トルネロス
#define		FORMNO_TORUNEROSU_NORMAL				( 0 )
#define		FORMNO_TORUNEROSU_AR				( 1 )
#define		FORMNO_TORUNEROSU_MAX				( 2 )

//ボルトロス
#define		FORMNO_BORUTOROSU_NORMAL				( 0 )
#define		FORMNO_BORUTOROSU_AR				( 1 )
#define		FORMNO_BORUTOROSU_MAX				( 2 )

//ランドロス
#define		FORMNO_RANDOROSU_NORMAL				( 0 )
#define		FORMNO_RANDOROSU_AR				( 1 )
#define		FORMNO_RANDOROSU_MAX				( 2 )

//キュレム
#define		FORMNO_KYUREMU_A				( 0 )
#define		FORMNO_KYUREMU_WHITE				( 1 )
#define		FORMNO_KYUREMU_BLACK				( 2 )
#define		FORMNO_KYUREMU_MAX				( 3 )

//ケルディオ
#define		FORMNO_KERUDHIO_NORMAL				( 0 )
#define		FORMNO_KERUDHIO_SWORD				( 1 )
#define		FORMNO_KERUDHIO_MAX				( 2 )

//メロエッタ
#define		FORMNO_MEROETTA_VOICE				( 0 )
#define		FORMNO_MEROETTA_STEP				( 1 )
#define		FORMNO_MEROETTA_MAX				( 2 )

//ゲノセクト
#define		FORMNO_GENOSEKUTO_NORMAL				( 0 )
#define		FORMNO_GENOSEKUTO_AQUA				( 1 )
#define		FORMNO_GENOSEKUTO_INAZUMA				( 2 )
#define		FORMNO_GENOSEKUTO_BLAZE				( 3 )
#define		FORMNO_GENOSEKUTO_FREEZE				( 4 )
#define		FORMNO_GENOSEKUTO_MAX				( 5 )

//ゲッコウガ
#define		FORMNO_GEKKOUGA_NORMAL				( 0 )
#define		FORMNO_GEKKOUGA_GEKKOUGA2				( 1 )
#define		FORMNO_GEKKOUGA_SATOSHI				( 2 )
#define		FORMNO_GEKKOUGA_MAX				( 3 )

//コフキムシ
#define		FORMNO_KOHUKIMUSI_AREA1				( 0 )
#define		FORMNO_KOHUKIMUSI_AREA2				( 1 )
#define		FORMNO_KOHUKIMUSI_AREA3				( 2 )
#define		FORMNO_KOHUKIMUSI_AREA4				( 3 )
#define		FORMNO_KOHUKIMUSI_AREA5				( 4 )
#define		FORMNO_KOHUKIMUSI_AREA6				( 5 )
#define		FORMNO_KOHUKIMUSI_AREA7				( 6 )
#define		FORMNO_KOHUKIMUSI_AREA8				( 7 )
#define		FORMNO_KOHUKIMUSI_AREA9				( 8 )
#define		FORMNO_KOHUKIMUSI_AREA10				( 9 )
#define		FORMNO_KOHUKIMUSI_AREA11				( 10 )
#define		FORMNO_KOHUKIMUSI_AREA12				( 11 )
#define		FORMNO_KOHUKIMUSI_AREA13				( 12 )
#define		FORMNO_KOHUKIMUSI_AREA14				( 13 )
#define		FORMNO_KOHUKIMUSI_AREA15				( 14 )
#define		FORMNO_KOHUKIMUSI_AREA16				( 15 )
#define		FORMNO_KOHUKIMUSI_AREA17				( 16 )
#define		FORMNO_KOHUKIMUSI_AREA18				( 17 )
#define		FORMNO_KOHUKIMUSI_AREA19				( 18 )
#define		FORMNO_KOHUKIMUSI_AREA20				( 19 )
#define		FORMNO_KOHUKIMUSI_MAX				( 20 )

//コフーライ
#define		FORMNO_KOHUURAI_AREA1				( 0 )
#define		FORMNO_KOHUURAI_AREA2				( 1 )
#define		FORMNO_KOHUURAI_AREA3				( 2 )
#define		FORMNO_KOHUURAI_AREA4				( 3 )
#define		FORMNO_KOHUURAI_AREA5				( 4 )
#define		FORMNO_KOHUURAI_AREA6				( 5 )
#define		FORMNO_KOHUURAI_AREA7				( 6 )
#define		FORMNO_KOHUURAI_AREA8				( 7 )
#define		FORMNO_KOHUURAI_AREA9				( 8 )
#define		FORMNO_KOHUURAI_AREA10				( 9 )
#define		FORMNO_KOHUURAI_AREA11				( 10 )
#define		FORMNO_KOHUURAI_AREA12				( 11 )
#define		FORMNO_KOHUURAI_AREA13				( 12 )
#define		FORMNO_KOHUURAI_AREA14				( 13 )
#define		FORMNO_KOHUURAI_AREA15				( 14 )
#define		FORMNO_KOHUURAI_AREA16				( 15 )
#define		FORMNO_KOHUURAI_AREA17				( 16 )
#define		FORMNO_KOHUURAI_AREA18				( 17 )
#define		FORMNO_KOHUURAI_AREA19				( 18 )
#define		FORMNO_KOHUURAI_AREA20				( 19 )
#define		FORMNO_KOHUURAI_MAX				( 20 )

//ビビヨン
#define		FORMNO_BIBIYON_AREA1				( 0 )
#define		FORMNO_BIBIYON_AREA2				( 1 )
#define		FORMNO_BIBIYON_AREA3				( 2 )
#define		FORMNO_BIBIYON_AREA4				( 3 )
#define		FORMNO_BIBIYON_AREA5				( 4 )
#define		FORMNO_BIBIYON_AREA6				( 5 )
#define		FORMNO_BIBIYON_AREA7				( 6 )
#define		FORMNO_BIBIYON_AREA8				( 7 )
#define		FORMNO_BIBIYON_AREA9				( 8 )
#define		FORMNO_BIBIYON_AREA10				( 9 )
#define		FORMNO_BIBIYON_AREA11				( 10 )
#define		FORMNO_BIBIYON_AREA12				( 11 )
#define		FORMNO_BIBIYON_AREA13				( 12 )
#define		FORMNO_BIBIYON_AREA14				( 13 )
#define		FORMNO_BIBIYON_AREA15				( 14 )
#define		FORMNO_BIBIYON_AREA16				( 15 )
#define		FORMNO_BIBIYON_AREA17				( 16 )
#define		FORMNO_BIBIYON_AREA18				( 17 )
#define		FORMNO_BIBIYON_AREA19				( 18 )
#define		FORMNO_BIBIYON_AREA20				( 19 )
#define		FORMNO_BIBIYON_MAX				( 20 )

//フラベベ
#define		FORMNO_HURABEBE_RED				( 0 )
#define		FORMNO_HURABEBE_YELLOW				( 1 )
#define		FORMNO_HURABEBE_ORANGE				( 2 )
#define		FORMNO_HURABEBE_BLUE				( 3 )
#define		FORMNO_HURABEBE_WHITE				( 4 )
#define		FORMNO_HURABEBE_MAX				( 5 )

//フラエッテ
#define		FORMNO_HURAETTE_RED				( 0 )
#define		FORMNO_HURAETTE_YELLOW				( 1 )
#define		FORMNO_HURAETTE_ORANGE				( 2 )
#define		FORMNO_HURAETTE_BLUE				( 3 )
#define		FORMNO_HURAETTE_WHITE				( 4 )
#define		FORMNO_HURAETTE_HAKAI				( 5 )
#define		FORMNO_HURAETTE_MAX				( 6 )

//フラージェス
#define		FORMNO_HURAAJESU_RED				( 0 )
#define		FORMNO_HURAAJESU_YELLOW				( 1 )
#define		FORMNO_HURAAJESU_ORANGE				( 2 )
#define		FORMNO_HURAAJESU_BLUE				( 3 )
#define		FORMNO_HURAAJESU_WHITE				( 4 )
#define		FORMNO_HURAAJESU_MAX				( 5 )

//トリミアン
#define		FORMNO_TORIMIAN_NORMAL				( 0 )
#define		FORMNO_TORIMIAN_HEART				( 1 )
#define		FORMNO_TORIMIAN_STAR				( 2 )
#define		FORMNO_TORIMIAN_DIAMOND				( 3 )
#define		FORMNO_TORIMIAN_YOUNGLADY				( 4 )
#define		FORMNO_TORIMIAN_LADY				( 5 )
#define		FORMNO_TORIMIAN_GENTLEMAN				( 6 )
#define		FORMNO_TORIMIAN_ANTOINETTE				( 7 )
#define		FORMNO_TORIMIAN_RENJISHI				( 8 )
#define		FORMNO_TORIMIAN_SPHINX				( 9 )
#define		FORMNO_TORIMIAN_MAX				( 10 )

//ニャオニクス
#define		FORMNO_NYAONIKUSU_MALE				( 0 )
#define		FORMNO_NYAONIKUSU_FEMALE				( 1 )
#define		FORMNO_NYAONIKUSU_MAX				( 2 )

//ギルガルド
#define		FORMNO_GIRUGARUDO_TATE				( 0 )
#define		FORMNO_GIRUGARUDO_HOKO				( 1 )
#define		FORMNO_GIRUGARUDO_MAX				( 2 )

//バケッチャ
#define		FORMNO_BAKETTYA_NORMAL				( 0 )
#define		FORMNO_BAKETTYA_SMALL				( 1 )
#define		FORMNO_BAKETTYA_BIG				( 2 )
#define		FORMNO_BAKETTYA_KING				( 3 )
#define		FORMNO_BAKETTYA_MAX				( 4 )

//パンプジン
#define		FORMNO_PANPUZIN_NORMAL				( 0 )
#define		FORMNO_PANPUZIN_SMALL				( 1 )
#define		FORMNO_PANPUZIN_BIG				( 2 )
#define		FORMNO_PANPUZIN_KING				( 3 )
#define		FORMNO_PANPUZIN_MAX				( 4 )

//ゼルネアス
#define		FORMNO_ZERUNEASU_NORMAL				( 0 )
#define		FORMNO_ZERUNEASU_RADIATION				( 1 )
#define		FORMNO_ZERUNEASU_MAX				( 2 )

//ジガルデ
#define		FORMNO_ZIGARUDE_50PER				( 0 )
#define		FORMNO_ZIGARUDE_10PER				( 1 )
#define		FORMNO_ZIGARUDE_SW10PER				( 2 )
#define		FORMNO_ZIGARUDE_SW50PER				( 3 )
#define		FORMNO_ZIGARUDE_100PER				( 4 )
#define		FORMNO_ZIGARUDE_MAX				( 5 )

//ディアンシー
#define		FORMNO_DHIANSII_NORMAL				( 0 )
#define		FORMNO_DHIANSII_MEGA				( 1 )
#define		FORMNO_DHIANSII_MAX				( 2 )

//フーパ
#define		FORMNO_HUUPA_NORMAL				( 0 )
#define		FORMNO_HUUPA_EARNEST				( 1 )
#define		FORMNO_HUUPA_MAX				( 2 )

//デカグース
#define		FORMNO_MANGUUSU2_NORMAL				( 0 )
#define		FORMNO_MANGUUSU2_NUSHI				( 1 )
#define		FORMNO_MANGUUSU2_MAX				( 2 )

//クワガノン
#define		FORMNO_KUWAGATA3_NORMAL				( 0 )
#define		FORMNO_KUWAGATA3_NUSHI				( 1 )
#define		FORMNO_KUWAGATA3_MAX				( 2 )

//オドリドリ
#define		FORMNO_MITUSUI_FLAMENCO				( 0 )
#define		FORMNO_MITUSUI_CHEER				( 1 )
#define		FORMNO_MITUSUI_HULA				( 2 )
#define		FORMNO_MITUSUI_NICHIBU				( 3 )
#define		FORMNO_MITUSUI_MAX				( 4 )

//アブリボン
#define		FORMNO_ABU2_NORMAL				( 0 )
#define		FORMNO_ABU2_NUSHI				( 1 )
#define		FORMNO_ABU2_MAX				( 2 )

//イワンコ
#define		FORMNO_OOKAMI1_NORMAL				( 0 )
#define		FORMNO_OOKAMI1_TWILIGHT				( 1 )
#define		FORMNO_OOKAMI1_MAX				( 2 )

//ルガルガン
#define		FORMNO_OOKAMI2_MIDDAY				( 0 )
#define		FORMNO_OOKAMI2_MIDNIGHT				( 1 )
#define		FORMNO_OOKAMI2_TWILIGHT				( 2 )
#define		FORMNO_OOKAMI2_MAX				( 3 )

//ヨワシ
#define		FORMNO_YOWASI_NORMAL				( 0 )
#define		FORMNO_YOWASI_GYOGUN_L				( 1 )
#define		FORMNO_YOWASI_MAX				( 2 )

//オニシズクモ
#define		FORMNO_MIZUGUMO2_NORMAL				( 0 )
#define		FORMNO_MIZUGUMO2_NUSHI				( 1 )
#define		FORMNO_MIZUGUMO2_MAX				( 2 )

//ラランテス
#define		FORMNO_HANAKAMA2_NORMAL				( 0 )
#define		FORMNO_HANAKAMA2_NUSHI				( 1 )
#define		FORMNO_HANAKAMA2_MAX				( 2 )

//エンニュート
#define		FORMNO_DOKUTOKAGE2_NORMAL				( 0 )
#define		FORMNO_DOKUTOKAGE2_NUSHI				( 1 )
#define		FORMNO_DOKUTOKAGE2_MAX				( 2 )

//シルヴァディ
#define		FORMNO_GURIPUSU2_NORMAL				( 0 )
#define		FORMNO_GURIPUSU2_BATTLE				( 1 )
#define		FORMNO_GURIPUSU2_HIKOU				( 2 )
#define		FORMNO_GURIPUSU2_POISON				( 3 )
#define		FORMNO_GURIPUSU2_JIMEN				( 4 )
#define		FORMNO_GURIPUSU2_IWA				( 5 )
#define		FORMNO_GURIPUSU2_MUSHI				( 6 )
#define		FORMNO_GURIPUSU2_GHOST				( 7 )
#define		FORMNO_GURIPUSU2_METAL				( 8 )
#define		FORMNO_GURIPUSU2_FIRE				( 9 )
#define		FORMNO_GURIPUSU2_WATER				( 10 )
#define		FORMNO_GURIPUSU2_KUSA				( 11 )
#define		FORMNO_GURIPUSU2_ELECTRIC				( 12 )
#define		FORMNO_GURIPUSU2_ESPER				( 13 )
#define		FORMNO_GURIPUSU2_KOORI				( 14 )
#define		FORMNO_GURIPUSU2_DRAGON				( 15 )
#define		FORMNO_GURIPUSU2_AKU				( 16 )
#define		FORMNO_GURIPUSU2_FAIRY				( 17 )
#define		FORMNO_GURIPUSU2_MAX				( 18 )

//メテノ
#define		FORMNO_NAGAREBOSI_M_RED				( 0 )
#define		FORMNO_NAGAREBOSI_M_ORANGE				( 1 )
#define		FORMNO_NAGAREBOSI_M_YELLOW				( 2 )
#define		FORMNO_NAGAREBOSI_M_GREEN				( 3 )
#define		FORMNO_NAGAREBOSI_M_BLUE				( 4 )
#define		FORMNO_NAGAREBOSI_M_INDIGO				( 5 )
#define		FORMNO_NAGAREBOSI_M_PURPLE				( 6 )
#define		FORMNO_NAGAREBOSI_RED				( 7 )
#define		FORMNO_NAGAREBOSI_ORANGE				( 8 )
#define		FORMNO_NAGAREBOSI_YELLOW				( 9 )
#define		FORMNO_NAGAREBOSI_GREEN				( 10 )
#define		FORMNO_NAGAREBOSI_BLUE				( 11 )
#define		FORMNO_NAGAREBOSI_INDIGO				( 12 )
#define		FORMNO_NAGAREBOSI_PURPLE				( 13 )
#define		FORMNO_NAGAREBOSI_MAX				( 14 )

//トゲデマル
#define		FORMNO_NIZITYUU_NORMAL				( 0 )
#define		FORMNO_NIZITYUU_NUSHI				( 1 )
#define		FORMNO_NIZITYUU_MAX				( 2 )

//ミミッキュ
#define		FORMNO_HORAA_NORMAL				( 0 )
#define		FORMNO_HORAA_KUBIORE				( 1 )
#define		FORMNO_HORAA_NORMAL_NUSHI				( 2 )
#define		FORMNO_HORAA_KUBIORE_NUSHI				( 3 )
#define		FORMNO_HORAA_MAX				( 4 )

//ジャラランガ
#define		FORMNO_UROKO3_NORMAL				( 0 )
#define		FORMNO_UROKO3_NUSHI				( 1 )
#define		FORMNO_UROKO3_MAX				( 2 )

//ネクロズマ
#define		FORMNO_PURIZUMU_NORMAL				( 0 )
#define		FORMNO_PURIZUMU_FORM_S				( 1 )
#define		FORMNO_PURIZUMU_FORM_L				( 2 )
#define		FORMNO_PURIZUMU_FORM_N				( 3 )
#define		FORMNO_PURIZUMU_MAX				( 4 )

//マギアナ
#define		FORMNO_MABOROSI16_PRESENT				( 0 )
#define		FORMNO_MABOROSI16_PAST				( 1 )
#define		FORMNO_MABOROSI16_MAX				( 2 )

#define		FORMNO_TAMAGO_NORMAL				( 0 )
#define		FORMNO_TAMAGO_MANAFI				( 1 )
#define		FORMNO_TAMAGO_MAX				( 2 )

#define OTHER_FORM_MAX  ( 309 )

// １種族あたりのフォルム数の最大値
#define MAX_FORM_NUM ( 28 )

#endif  // __MONSNODEF_H__
