// このファイルは tool/Binlinker/binlinder.rb から出力されています。
#ifndef __MOBICLIP_RESOURCE_PACK__
#define __MOBICLIP_RESOURCE_PACK__

enum {
	BL_IDX_MOBICLIP_RESOURCE_PACK_SIMPLE_BOARD_MODEL_CTR_GFBMDL,
	BL_IDX_MOBICLIP_RESOURCE_PACK_FILLSCREAN_CTR_GFBVSH,
	BL_IDX_MOBICLIP_RESOURCE_PACK_COMB1_MANUAL_CTR_GFBFSH,
	BL_IDX_MOBICLIP_RESOURCE_PACK_SIMPLE_DUMMY_TEX_CTR_BTEX,
	BL_IDX_MOBICLIP_RESOURCE_PACK_MAX,
};



#endif // MOBICLIP_RESOURCE_PACK
