//==============================================================================
/**
 @file    ZukanViewLaunch.cpp
 @author  kawada_koji@gamefreak.co.jp
 @date    2015.08.18
 @brief   図鑑の起動画面のビュー
 */
//==============================================================================


// gfl2のインクルード
#include <ui/include/gfl2_UI.h>
#include <Layout/include/gfl2_Layout.h>

// nijiのインクルード
#include "AppLib/include/Tool/app_tool_ButtonManager.h"

#include <Sound/include/Sound.h>

// nijiのデータのヘッダーファイルのインクルード
#include <niji_conv_header/app/zukan/launch.h>
#include <niji_conv_header/app/zukan/launch_pane.h>
#include <niji_conv_header/app/zukan/launch_anim_list.h>

// 図鑑のインクルード
#include "ZukanType.h"
#include "ZukanViewLaunch.h"




GFL_NAMESPACE_BEGIN(app)
GFL_NAMESPACE_BEGIN(zukan)


//==============================================================================
//
//  ZukanViewLaunch
//
//==============================================================================
const ZukanType::ButtonConstInfo ZukanViewLaunch::BUTTON_CONST_INFO[BUTTON_ID_NUM] =
{
  {
    BUTTON_ID_ALOLA_TOP,
    PANENAME_ZUKAN_MIN_LOW_001_PANE_PLATE_00,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_MAIN,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_BOUND_00,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_NULL_CUR,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_00_TOUCH,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_00_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_00_CANSEL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_00_TOUCH_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_00_ACTIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_00_PASSIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_00_STATUS_NORMAL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_00_STATUS_SILVER,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_00_STATUS_GOLD,
    false,
    gfl2::ui::BUTTON_INVALID,
    app::tool::ButtonManager::BIND_KEY_MODE_TRIGGER,
    SEQ_SE_DECIDE1
  }, 
  {
    BUTTON_ID_ISLAND1_TOP,
    PANENAME_ZUKAN_MIN_LOW_001_PANE_PLATE_01,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_MAIN,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_BOUND_00,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_NULL_CUR,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_01_TOUCH,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_01_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_01_CANSEL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_01_TOUCH_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_01_ACTIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_01_PASSIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_01_STATUS_NORMAL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_01_STATUS_SILVER,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_01_STATUS_GOLD,
    false,
    gfl2::ui::BUTTON_INVALID,
    app::tool::ButtonManager::BIND_KEY_MODE_TRIGGER,
    SEQ_SE_DECIDE1
  },
  {
    BUTTON_ID_ISLAND2_TOP,
    PANENAME_ZUKAN_MIN_LOW_001_PANE_PLATE_02,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_MAIN,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_BOUND_00,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_NULL_CUR,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_02_TOUCH,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_02_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_02_CANSEL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_02_TOUCH_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_02_ACTIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_02_PASSIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_02_STATUS_NORMAL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_02_STATUS_SILVER,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_02_STATUS_GOLD,
    false,
    gfl2::ui::BUTTON_INVALID,
    app::tool::ButtonManager::BIND_KEY_MODE_TRIGGER,
    SEQ_SE_DECIDE1
  },
  {
    BUTTON_ID_ISLAND3_TOP,
    PANENAME_ZUKAN_MIN_LOW_001_PANE_PLATE_03,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_MAIN,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_BOUND_00,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_NULL_CUR,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_03_TOUCH,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_03_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_03_CANSEL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_03_TOUCH_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_03_ACTIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_03_PASSIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_03_STATUS_NORMAL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_03_STATUS_SILVER,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_03_STATUS_GOLD,
    false,
    gfl2::ui::BUTTON_INVALID,
    app::tool::ButtonManager::BIND_KEY_MODE_TRIGGER,
    SEQ_SE_DECIDE1
  },
  {
    BUTTON_ID_ISLAND4_TOP,
    PANENAME_ZUKAN_MIN_LOW_001_PANE_PLATE_04,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_MAIN,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_BOUND_00,
    PANENAME_ZUKAN_BTN_LOW_001_PANE_NULL_CUR,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_04_TOUCH,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_04_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_04_CANSEL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_04_TOUCH_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_04_ACTIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_04_PASSIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_04_STATUS_NORMAL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_04_STATUS_SILVER,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PLATE_04_STATUS_GOLD,
    false,
    gfl2::ui::BUTTON_INVALID,
    app::tool::ButtonManager::BIND_KEY_MODE_TRIGGER,
    SEQ_SE_DECIDE1
  }, 
  {
    BUTTON_ID_ADMIRE,
    PANENAME_ZUKAN_MIN_LOW_001_PANE_PARTS_00,
    PANENAME_ZUKAN_BTN_LOW_002_PANE_MAIN,
    PANENAME_ZUKAN_BTN_LOW_002_PANE_BOUND_00,
    PANENAME_ZUKAN_BTN_LOW_002_PANE_NULL_CUR,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PARTS_00_TOUCH,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PARTS_00_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PARTS_00_CANSEL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PARTS_00_TOUCH_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PARTS_00_ACTIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__PARTS_00_PASSIVE,
    app::tool::ButtonManager::ANIMATION_NULL,
    app::tool::ButtonManager::ANIMATION_NULL,
    app::tool::ButtonManager::ANIMATION_NULL,
    false,
    gfl2::ui::BUTTON_INVALID,
    app::tool::ButtonManager::BIND_KEY_MODE_TRIGGER,
    SEQ_SE_DECIDE1
  }, 
  {
    BUTTON_ID_BACK,
    PANENAME_ZUKAN_MIN_LOW_001_PANE_BTN_BACK,
    PANENAME_COMMON_BTN_LOW_000_PANE_MAIN,
    PANENAME_COMMON_BTN_LOW_000_PANE_BOUND_00,
    gfl2::lyt::LYTSYS_PANEINDEX_ERROR,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__BTN_BACK_TOUCH,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__BTN_BACK_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__BTN_BACK_CANSEL,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__BTN_BACK_TOUCH_RELEASE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__BTN_BACK_ACTIVE,
    LA_LAUNCH_ZUKAN_MIN_LOW_001__BTN_BACK_PASSIVE,
    app::tool::ButtonManager::ANIMATION_NULL,
    app::tool::ButtonManager::ANIMATION_NULL,
    app::tool::ButtonManager::ANIMATION_NULL,
    true,
    gfl2::ui::BUTTON_B,
    app::tool::ButtonManager::BIND_KEY_MODE_TRIGGER,
    SEQ_SE_CANCEL1
  }, 
};


GFL_NAMESPACE_END(zukan)
GFL_NAMESPACE_END(app)

