//==============================================================================
/**
 @file    ZukanViewIslandTop.cpp
 @author  kawada_koji@gamefreak.co.jp
 @date    2015.08.18
 @brief   図鑑の島図鑑トップ画面のビュー
 */
//==============================================================================


// gfl2のインクルード
#include <ui/include/gfl2_UI.h>
#include <Layout/include/gfl2_Layout.h>

// nijiのインクルード
#include "AppLib/include/Tool/app_tool_ButtonManager.h"

#include <Sound/include/Sound.h>

// nijiのデータのヘッダーファイルのインクルード
#include <niji_conv_header/app/zukan/island_top.h>
#include <niji_conv_header/app/zukan/island_top_pane.h>
#include <niji_conv_header/app/zukan/island_top_anim_list.h>

// 図鑑のインクルード
#include "ZukanType.h"
#include "ZukanViewIslandTop.h"




GFL_NAMESPACE_BEGIN(app)
GFL_NAMESPACE_BEGIN(zukan)


//==============================================================================
//
//  ZukanViewIslandTop
//
//==============================================================================


// ボタンアニメなしのところに何も動きがないアニメreleaseを入れている。アニメが変わったら要注意。
#define APP_ZUKAN_ISLAND_TOP_POKE_BUTTON(buttonId,paneName) \
  {                                                              \
    buttonId,                                                    \
    PANENAME_ZUKAN_MIN_LOW_003_PANE_##paneName,                  \
    PANENAME_ZUKAN_BTN_LOW_005_PANE_POKE_ICON,                   \
    PANENAME_ZUKAN_BTN_LOW_005_PANE_BOUND_00,                    \
    gfl2::lyt::LYTSYS_PANEINDEX_ERROR,                           \
    /* @fix NMCat[1886] 島図鑑でポケモンアイコンをタッチリリース直後にポケモン情報画面に遷移する  →「カーソル合わせタッチ」と「決定タッチ」を分ける。 */ \
    /*      ボタンには何も変化の生じないアニメを設定しておき、決定したら自前でアニメを再生する。 */                                                       \
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__##paneName##_RELEASE,       \
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__##paneName##_RELEASE,       \
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__##paneName##_RELEASE,       \
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__##paneName##_RELEASE,       \
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__##paneName##_RELEASE,       \
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__##paneName##_RELEASE,       \
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__##paneName##_STATUS,        \
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__##paneName##_TOUCH_RELEASE, \
    app::tool::ButtonManager::ANIMATION_NULL,                    \
    false,                                                       \
    gfl2::ui::BUTTON_INVALID,                                    \
    app::tool::ButtonManager::BIND_KEY_MODE_TRIGGER,             \
    app::tool::ButtonManager::SE_NULL                            \
  }
 

const ZukanType::ButtonConstInfo ZukanViewIslandTop::BUTTON_CONST_INFO[BUTTON_ID_NUM] =
{
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 0, A_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 1, A_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 2, A_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 3, A_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 4, A_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 5, A_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 6, A_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 7, A_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 8, A_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 9, A_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 10, A_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 11, A_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 12, A_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 13, A_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 14, A_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 15, B_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 16, B_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 17, B_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 18, B_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 19, B_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 20, B_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 21, B_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 22, B_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 23, B_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 24, B_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 25, B_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 26, B_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 27, B_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 28, B_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 29, B_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 30, C_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 31, C_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 32, C_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 33, C_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 34, C_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 35, C_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 36, C_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 37, C_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 38, C_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 39, C_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 40, C_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 41, C_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 42, C_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 43, C_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 44, C_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 45, D_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 46, D_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 47, D_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 48, D_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 49, D_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 50, D_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 51, D_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 52, D_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 53, D_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 54, D_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 55, D_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 56, D_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 57, D_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 58, D_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 59, D_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 60, E_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 61, E_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 62, E_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 63, E_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 64, E_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 65, E_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 66, E_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 67, E_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 68, E_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 69, E_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 70, E_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 71, E_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 72, E_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 73, E_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 74, E_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 75, F_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 76, F_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 77, F_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 78, F_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 79, F_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 80, F_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 81, F_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 82, F_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 83, F_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 84, F_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 85, F_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 86, F_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 87, F_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 88, F_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 89, F_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 90, G_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 91, G_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 92, G_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 93, G_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 94, G_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 95, G_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 96, G_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 97, G_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 98, G_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 99, G_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 100, G_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 101, G_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 102, G_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 103, G_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 104, G_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 105, H_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 106, H_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 107, H_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 108, H_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 109, H_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 110, H_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 111, H_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 112, H_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 113, H_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 114, H_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 115, H_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 116, H_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 117, H_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 118, H_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 119, H_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 120, I_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 121, I_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 122, I_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 123, I_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 124, I_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 125, I_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 126, I_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 127, I_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 128, I_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 129, I_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 130, I_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 131, I_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 132, I_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 133, I_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 134, I_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 135, J_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 136, J_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 137, J_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 138, J_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 139, J_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 140, J_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 141, J_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 142, J_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 143, J_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 144, J_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 145, J_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 146, J_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 147, J_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 148, J_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 149, J_14),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 150, K_00),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 151, K_01),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 152, K_02),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 153, K_03),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 154, K_04),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 155, K_05),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 156, K_06),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 157, K_07),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 158, K_08),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 159, K_09),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 160, K_10),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 161, K_11),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 162, K_12),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 163, K_13),
  APP_ZUKAN_ISLAND_TOP_POKE_BUTTON( 164, K_14),
  {
    BUTTON_ID_BACK,
    PANENAME_ZUKAN_MIN_LOW_003_PANE_BACK,
    PANENAME_COMMON_BTN_LOW_000_PANE_MAIN,
    PANENAME_COMMON_BTN_LOW_000_PANE_BOUND_00,
    gfl2::lyt::LYTSYS_PANEINDEX_ERROR,
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__BACK_TOUCH,
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__BACK_RELEASE,
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__BACK_CANSEL,
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__BACK_TOUCH_RELEASE,
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__BACK_ACTIVE,
    LA_ISLAND_TOP_ZUKAN_MIN_LOW_003__BACK_PASSIVE,
    app::tool::ButtonManager::ANIMATION_NULL,
    app::tool::ButtonManager::ANIMATION_NULL,
    app::tool::ButtonManager::ANIMATION_NULL,
    true,
    gfl2::ui::BUTTON_B,
    app::tool::ButtonManager::BIND_KEY_MODE_TRIGGER,
    SEQ_SE_CANCEL1
  }, 
};


#undef APP_ZUKAN_ISLAND_TOP_POKE_BUTTON


GFL_NAMESPACE_END(zukan)
GFL_NAMESPACE_END(app)

